### ISSUE TITLE
有新待审批文件时，右上角显示图标提示，点击进入收件箱

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1002]

**Comment by yinlianghui** [comment]
测试要点:
1. 目前有两个APP需要上述功能，Workflow/CMS，都需要测试。
2. 只有相关APP的Badge（待处理数量）值大于0时才显示相应的APP图标。
3. 点击图标会进入相应APP界面，Workflow是进入待审核，CMS是进入知识库根目录。
4. 每个APP都可以在右上角看到相应图标，且都可以点击跳转到第3点所述目录。
5. 我只测试了chrome，请重点测试IE/Edge/手机APP/PC客户端。
