### ISSUE TITLE
签核历程中传阅给部分账户，处理人名称为空，但是功能都正常。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1006]
![](https://static.dingtalk.com/media/lALOq1i5ks0BF80DCQ_777_279.png_620x10000q90g.jpg)

![image](https://cloud.githubusercontent.com/assets/6219465/23535729/305a558c-fffb-11e6-976b-86f66d0a7395.png)

上述测试是在21服务器库中。

**Comment by yinlianghui** [comment]
经与孙确认，是因为user.name为空，而approve.handler_name是取自user.name。
孙找到目前库中有几十个账户的user.name为空，认为是BUG。

**Comment by sunhaolin** [comment]
```
db.users.find({
    name: {
        $exists: false
    }
}).forEach(function(u) {
    if (u.steedos_id) {
        print(u.steedos_id);
        user_name = u.steedos_id.split("@")[0];
        db.users.update({
            _id: u._id
        }, {
            $set: {
                name: user_name
            }
        })
    }
})
```
