### ISSUE TITLE
IE 在线编辑无法使用

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1016]

**Comment by chenzhipei** [comment]
需要测试一下ie11浏览器上各个word版本在线编辑的情况（重点word2007，客户在使用），测试前加入信任站点，需安装控件（自动弹出）

**Comment by chenzhipei** [comment]
测试2003、2007、2010、2013、2016，其中2003和2016不支持，和黄怡确认客户都在使用2007版本，更新包后再测试处理

**Comment by chenzhipei** [comment]
1、先将服务的url添加到“可信任站点”；
2、然后官网下载修复工具安装后，重启ie浏览器，就可以使用在线编辑了
http://www.ntko.com/demo/faq/tools/Repairoffice2013and2016.zip
