### ISSUE TITLE
账户设置，邮件应添加对已有邮箱的删除功能

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#1017]
![s70304-16374447](https://cloud.githubusercontent.com/assets/23308088/23577401/21ed6d1e-00f9-11e7-8644-9aad6521f757.jpg)
想删除已添加的错误邮箱地址

**Comment by yinlianghui** [comment]
需要删除邮箱功能，但是不着急，可以排在很后面。
做的时候请多方面考虑该问题，比如最后一个邮箱不允许被删除，删除邮箱前需要检查其他平台关联性账户问题，比如云盘，确定可以被删除才删除。

**Comment by steedos** [comment]
暂停，转移到看板中跟踪
