### ISSUE TITLE
手机app申请人提交申请单，下一步处理人恰好审批王处于打开状态时，下一步处理人的ios app会刷新

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1018]
1. 测试的时候是用电脑新建申请单，在草稿中把单子提交给下一步处理人，会把下一步骤处理人的手机APP强行跳转到待审核相应单子。
2. 因为下一步骤处理人可能正在写新的申请单，所以问题较为严重。
3. 如果下一步处理人用的是android手机或网页不会出现上述问题，只有ios上的APP（测试时用的是iphone7/iphone 6s）才会有问题。
4. iphone 6s上开发版APP没有上述问题。

**Comment by yinlianghui** [comment]
去掉推送通知那段代码中window.open instance_url语句就能解决问题（我打包到21上测试过），但是要等庄总一定确定该代码的功能，是否可以直接注释掉。

**Comment by zhemingloveme** [comment]
经测试：iphone 7plus 客户端打开申请单，新建申请单，当有发来需要审批的申请单时，手机屏幕会出现短暂的闪烁情况，但是不会刷新了！
