### ISSUE TITLE
FSSH：第一次使用向导界面，大字体问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1022]
![](https://static.dingtalk.com/media/lALOrHS1T80Be80CYw_611_379.png_620x10000q90g.jpg)

**Comment by yinlianghui** [comment]
1. 内部没有放大为指定大小，在modal-body中增加字体缩放样式类modal-zoom就行。
2. 样式错乱，这是大字体时modal-dialog宽度不足引起的，需要单独为两种大字体单独设置modal-dialog的    min-width属性。

**Comment by chenzhipei** [comment]
请测试chrome浏览器、桌面客户端、ie浏览器下各字体模式下的弹出样式：在控制台输入Modal.show("accounts_guide_modal")弹出第一次向导界面

**Comment by zhemingloveme** [comment]
经测试：Chrome浏览器、桌面客户端、IE11  标准字体，大字体、超大字体在控制台中输入Modal.show("accounts_guide_modal")调用邮箱验证向导窗口，此窗口显示样式正常
