### ISSUE TITLE
在线编辑在网络状况不好的情况下会死机

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1032]
![default](https://cloud.githubusercontent.com/assets/15027092/23691873/42917190-0406-11e7-8041-2fe2bd75eb42.png)

**Comment by zhemingloveme** [comment]
目前测试结果是：window客户端连接21，使用在线编辑，2种情况
**1、未点击在线编辑，网路断开的情况下，右上角红色窗口弹窗提醒
![image](https://cloud.githubusercontent.com/assets/23308088/24034146/1a9280f4-0b2b-11e7-9326-4635668f6d78.png)
**

2、在点击在线编辑后，网络断开，客户端一直处于loading状态，网络自动连接好后，客户端会恢复自动打开文档
