### ISSUE TITLE
多次重复传阅给同一人，签核历程中看到的是多次重复传阅的审批单，都是同一审批内容

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#1035]
重复传阅给同一个人，被传阅人只能收到第一次传阅的文件。签批后，在这张申请单签核历程中看到的是多次重复传阅的审批单，都是同一审批内容
![default](https://cloud.githubusercontent.com/assets/23308088/23694079/d19635fe-0412-11e7-92cd-b203cc468ebb.png)

**Comment by steedos** [comment]
暂不处理
