### ISSUE TITLE
转发邮件时：邮件附件大的时候应该有个加载进度提示或者文字提示

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1036]

**Comment by zhangshanshan2016** [comment]
需要测试各种情况：1，在邮件加载附件时，不能发送和存草稿；2.附件加载完后，发送 和存草稿，添加新附件是否正常；3.新建邮件是否能正常发送邮件和存草稿，添加新附件等；4.从草稿箱中发送邮件和存草稿，添加新附件是否正常；

**Comment by zhemingloveme** [comment]
经测试：在邮件中转发，若有较大的附件会由提示
![image](https://cloud.githubusercontent.com/assets/23308088/24283765/900d84ec-10a2-11e7-9575-cac37cc0caed.png)
在邮件加载附件时，不能发送和存草稿
加载完成后，可以储存为草稿，打开此草稿，还会出现邮件加载中
其他功能可以正常使用
