### ISSUE TITLE
选人界面，手机端偶尔会这样

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1042]
![image](https://cloud.githubusercontent.com/assets/3104826/23779554/1a0727de-057c-11e7-91c2-712290bd2894.png)

可以找找原因，还有初始默认高度可以调高。

**Comment by yinlianghui** [comment]
经调式查看代码，感觉不大可能有上述问题，因为高度是由$(window).height() - 180 - 25计算得来的，也就是说除非$(window).height()计算有误，不应该出面上述问题。
后续重现后再处理。
