### ISSUE TITLE
android/ios手机APP中关闭浏览器记住最后一个APP地址，重新进入时直接进入上次关闭的地址功能无效

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1043]
1. 这个是手机APP不支持或不完全支持关闭事件造成的。
2. 改成Route变更时，判断如果进入非steedos开头的Route则作为最后一个APP地址记住，然后再次再进入时直接进入最后一次记住的地址就行。
3. 这样改的话，无论关闭还是注销都能记住最后一次进入的地址了。
4. 原来最后一个地址只记录APP根目录，这条规则保持不变。
5. 改好后要注意测试不应该把steedos开头的地址也记住，比如登录/注册/忘记密码等。

**Comment by chenzhipei** [comment]
请测试浏览器端和手机端的效果

**Comment by zhemingloveme** [comment]
经测试，浏览器关闭后，再次打开会进去上次关闭的路径  
              手机app，结束后台进程，再次打开会进入上次的根目录
