### ISSUE TITLE
部分申请单，没有选中下一步骤时,下一步处理人列表为空（一定为空，非概率事件）

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1045]
![image](https://cloud.githubusercontent.com/assets/6219465/23838202/0a24e4ec-07ce-11e7-867a-e4af54704c10.png)

但是从一个没有问题的申请单中点开过下一步处理人列表，然后再去点开之前有问题的申请单中的下一步骤列表又变正常了。

**Comment by yinlianghui** [comment]
经查，是因为没有选中下一步骤的原因造成的，只要选择了下一步骤就不会有问题。
应该在点击下一步骤处理人时，先判断下一步骤是否为空，如果为空就在右上角提示不能为空，而不是弹出选人控件。

**Comment by yinlianghui** [comment]
测试要点:
重点测试手机APP/ie11/edge上有没有问题

**Comment by zhemingloveme** [comment]
流程中，设置为多个审批节点，新建申请单，在下一步骤可以看到请选择，此时下一步处理人是不可选的状态.（IE11、Edge浏览器）
手机端点击后无响应
