### ISSUE TITLE
集成 wekan

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1048]
- [x] wekan 运行需要 users.profile 字段，目前Steedos没有自动创建，需要调整相关代码，自动给默认值 profile: {}

升级脚本

db.users.update({profile:{$exists:false}},{$set:{profile:{}}}, {multi:true})

**Comment by sunhaolin** [comment]
写users表的observechange，当users变化时做wekan相关处理，比如：增加wekan需要的字段等。
