### ISSUE TITLE
表单描述中换行，前台不生效，多行文本能生效

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1049]
![image](https://cloud.githubusercontent.com/assets/15027092/23843522/6749206a-07f7-11e7-9473-9b8b62875f53.png)

![image](https://cloud.githubusercontent.com/assets/15027092/23843539/7e9a7296-07f7-11e7-9c0c-2159720da63e.png)

**Comment by chenzhipei** [comment]
请测试三种情况：页面为只读、可编辑和打印情况下的情况

**Comment by zhemingloveme** [comment]
在流程设计器中，添加换行表单描述，新建申请单，手机客户端，windows客户端，IE11 Edge 可以正常显示
在只读，可编辑和打印情况下，也可以显示多行表单描述
