### ISSUE TITLE
当一个用户不属性任何工作区时，会无法加载审批王

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1050]
![](https://static.dingtalk.com/media/lALPAsaK8WrlQaPNAgnNBHQ_1140_521.png_620x10000q90g.jpg)

![](https://static.dingtalk.com/media/lALPAsaK8WrlfhjNAVnNBA0_1037_345.png_620x10000q90g.jpg)

测试账户：litant@hotoa.com 123456
测试数据库：21数据库

**Comment by yinlianghui** [comment]
FSSH目前会弹出窗口提示没有权限进入工作平台，但是我们的steedos是允许不属性任何工作区时使用的，所以需要额外处理。

**Comment by yinlianghui** [comment]
关联任务：新增工作区信息页面 #688 ，新建工作区功能 #635

**Comment by yinlianghui** [comment]
暂不处理，等任务：新注册用户功能优化 #1076 完成后再处理。
即如果遇到这种情况，比如，一个用户被其唯一的工作区踢出后，就不属性任何工作区，这里就按新注册用户功能优化 #1076方式一样处理。

**Comment by steedos** [comment]
转移到 看板中排队

**Comment by steedos** [comment]
https://cn.steedos.com/kanban/b/fMYefy8GamcN6zRoy/steedos/4S2xtzeEkng3xkLYj
