### ISSUE TITLE
表单模式，大字体，超大字体情况下，日期控件显示不全

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#1053]
![2017-03-14 9 41 38](https://cloud.githubusercontent.com/assets/23308088/23882364/148feac6-089b-11e7-9f53-39d33e2b66e2.png)

**Comment by yinlianghui** [comment]
测试要点：
1. 请测试日期/日期时间两种控件。
2. 似乎只有表格模式才会有问题，但是请把表格及默认两种样式情况下都测试下。
3. 需要测试客户端及edge/ie11浏览器。
4. 请测试确认日期/日期时间两种控件可能在表单的任意位置（比如在左侧/右侧，最顶部/底部等）都能正常显示不会出现上述问题。

**Comment by zhemingloveme** [comment]
调整屏幕的大小，日期控件可以正常显示。不影响使用，另行处理
