### ISSUE TITLE
角色改成岗位，岗位改成岗位人员

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1054]
![image](https://cloud.githubusercontent.com/assets/6219465/23883849/8a557eb6-08a4-11e7-9343-c294e4212048.png)

1.中英文都要改。
2.帮助文档也要改。

**Comment by zhangshanshan2016** [comment]
界面中“角色”已经改成了“岗位”，“岗位”改成了“岗位成员”，但是帮助文档没有做，新建了一个issue，用来修改帮助文档

**Comment by zhemingloveme** [comment]
经测试：审批王角色和岗位已经修改
![image](https://cloud.githubusercontent.com/assets/23308088/23987693/b9fe2c22-0a65-11e7-82d2-7cc92e9e159f.png)
