### ISSUE TITLE
Portal同步请求改成异步请求以实现性能优化

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1060]
三件事：
1. 第一次打开portal时，先生成空的框架界面，然后再开始ajax抓取数据。
2. ajax抓取数据那块改成异步请求（async设置为true），并且请求完成后不要执行界面生成脚本，而是设置isDatasourceChanged变量为true。
3. 专门开一个新的定时器timeoutTagForPage，2秒执行一次，当isDatasourceChanged变量为true时执行界面生成脚本，并把isDatasourceChanged变量设置为false。
4. 判断是否正在抓取数据，显示小的loading图标，判断方法：
Portal.Datasources[dashboardId][datasource.name]记录的是某个datasource的请求结果，当某个datasource.name正在抓取数据时，设置Portal.Datasources[dashboardId]["loading_datasources"].push(datasource.name)，数据抓取完成时，就remove(datasource.name)
然后就可以根据Portal.Datasources[dashboardId]["loading_datasources"]的数组长度来判断是否正常抓取数据。
5. 类似第4点，判断是否抓取数据出现异常，之前的方法是异常时直接清空相应datasource的结果，改成异常时提示相应接口异常，方法：
当某个datasource.name抓取数据出现error时，设置Portal.Datasources[dashboardId]["exceptional_datasources"].push(datasource.name)，下次成功时就remove(datasource.name)。
如果有异常，右上角提示：”待办结果获取失败，可能是网络故障”，如果可以指定具体接口，提示：”xxx结果获取失败，可能是网络故障”。

**Comment by chenzhipei** [comment]
抚顺服务更新后重新导入面板：
[dashboard-fssh20170317-2(json).txt](https://github.com/steedos/apps/files/850254/dashboard-fssh20170317-2.json.txt)
