### ISSUE TITLE
大字体下审批王待审核顶部下拉菜单在手机上显示不全。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1061]
![image](https://cloud.githubusercontent.com/assets/6219465/23946375/1fc4c400-09b5-11e7-843e-d2117dff6319.png)

**Comment by yinlianghui** [comment]
在Iphone5s/iphone6s都有上述问题，只要屏幕不够大就有问题。

**Comment by yinlianghui** [comment]
.workflow-menu {
    width: 300px;
    left: 50%;
    margin-left: -150px;
    overflow-y: auto;
}

把300px改成适当大小，比如280px，然后margin-left也相应改为一半大小，对应280px为-140px。

**Comment by yinlianghui** [comment]
@media screen and (max-width: 767px){
    .zoom-large,.zoom-extra-large{
        .workflow-menu{
            width: 300px;
            margin-left: -150px;
        }
    }
}
手机上才修正宽度。

**Comment by zhemingloveme** [comment]
经测试：大字体和超大字体的情况下，待审核顶部下拉菜单可以正常显示
