### ISSUE TITLE
CMS 使用小蓝点标记未读

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1070]
- CMS 使用小蓝点标记未读
- 已读文章标题也用粗体
- 栏目名称用粗体

**Comment by zhusijia** [comment]
测试要点：在IE，火狐，手机端进行兼容性测试

**Comment by zhusijia** [comment]
已读文章标题改成粗体，栏目名称用粗体

**Comment by zhemingloveme** [comment]
通过测试：兼容手机客户端和桌面客户端
CMS 使用小蓝点标记未读
已读文章标题也用粗体
栏目名称用粗体
