### ISSUE TITLE
在同一步骤上传附件，不会覆盖老版本

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1071]
![image](https://cloud.githubusercontent.com/assets/15027092/24030284/23a2918e-0b17-11e7-8c35-76a2c286fba7.png)

**Comment by steedos** [comment]
是为了与老版本兼容，设计的一个定时脚本导致的。是不是应该关闭那个脚本了？ @sunhaolin

**Comment by sunhaolin** [comment]
经确认 此情况属正常，不做修改

**Comment by zhemingloveme** [comment]
此情况属正常，不做修改
