### ISSUE TITLE
把系统设置改成动态菜单

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1081]
设置教程见wiki：https://github.com/steedos/apps/wiki/%E7%B3%BB%E7%BB%9F%E5%8A%A8%E6%80%81%E8%8F%9C%E5%8D%95%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by zhusijia** [comment]
https://github.com/steedos/apps/wiki/%E8%AF%BB%E5%8F%96%E6%95%B0%E6%8D%AE%E8%A1%A8%E5%8A%A8%E6%80%81%E7%94%9F%E6%88%90%E8%AE%BE%E7%BD%AE%E9%9D%A2%E6%9D%BF%E4%B8%AD%E7%9A%84%E5%90%84%E4%B8%AA%E5%8A%9F%E8%83%BD%E9%80%89%E9%A1%B9

测试要点：用户所拥有的权限是否可以使用设置面板中的功能，或是遗漏功能没有显示

**Comment by yinlianghui** [comment]
关于组织机构权限单独处理：
动态菜单没有判断isNotSync，即imo/qq/dingtalk账户等同步账户不需要显示组织机构 #1098

**Comment by yinlianghui** [comment]
请参考wiki中【系统动态菜单配置说明】，测试要点：
1. 确保所有菜单链接都可以正常工作（一个一个菜单点击）。
2. 确保所有菜单显示权限正常。

**Comment by zhemingloveme** [comment]
点击设置，普通用户显示：工作区信息
                  管理员用户显示：组织架构、自定义应用、账务、岗位、岗位成员、流程设计器
                 付费用户显示：管理员用户显示+流程脚本和图片签名
