### ISSUE TITLE
测试客户端在线编辑

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1096]
准备工作：
1、先将本地分支切换到office-edit-online
2、将客户端安装路径下vbs文件夹中的edit.vbs文件替换为附件中的vbs（在客户端控制台输入process.cwd()查看安装路径）
[edit.zip](https://github.com/steedos/apps/files/869886/edit.zip)

测试要点：
1、测试doc、docx格式文件点击、查看、编辑和下载情况
2、点击查看时，文档应该为最终状态（不显示修订痕迹），关闭时不做上传
3、点击编辑即之前的在线编辑，在线编辑显示修订痕迹，关闭时提示上传文件
4、点击下载即下载文件
5、点击列表中的附件弹出版本信息
6、版本信息中的原文件连接移除，添加下载和查看按钮
7、点击版本页中的查看则查看对应版本的文档，点击下载即下载对应版本的文档
8、点击版本页中的编辑默认编辑最新版本的文档

注：还需测试手机和浏览器上的情况，因为对原界面有修改，以免影响原来的功能

**Comment by zhemingloveme** [comment]
## 客户端：点击查看，自动打开office，为只读状态，可编辑显示修订痕迹，关闭不保存
              点击编辑，客户端显示已被锁定，office自动打开，显示修订痕迹，关闭前若不点击保存，会自动保存
              点击下载，弹出提示存储路径窗口
              点击文件名，弹出窗口，显示版本信息，有查看，下载按钮，左下角有编辑按钮和申请单页面的            编辑功能一样
## IE11:  使用在线编辑功能，需要添加信任站点，然后去http://www.ntko.com/demo/faq/index.html，找到常见问题文件读取错误，下载注册表补丁安装，
          点击编辑，可以在浏览器中调用office，打开文档
          点击下载，可以弹出存储路径

**Comment by zhemingloveme** [comment]
**Android**
上传附件为.doc或.docx格式文件，点击文件名，会弹出android打开方式，点击下载会跳转链接，显示空白界面
**Ios**
上传附件为.doc或.docx格式文件，点击文件名，弹出版本信息窗口，## 窗口右上角加号，可以上传新的文件，但是会覆盖此.doc或者.docx的文件
