### ISSUE TITLE
动态菜单没有判断isNotSync，即imo/qq/dingtalk账户等同步账户不需要显示组织机构

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1098]

**Comment by yinlianghui** [comment]
当因isNotSync没有权限显示组织机构菜单时，依然显示其菜单，但是点击是不显示组织机构，并且右上角提示：“第三方同步账户无法使用该功能”

**Comment by yinlianghui** [comment]
Router中判断Steedos.isNotSync()为true才显示右侧 组织机构功能。

**Comment by zhemingloveme** [comment]
需兼容手机app

**Comment by yinlianghui** [comment]
有两个地方存在组织构架，一个是系统设置，一个是联系人，都要测试。

**Comment by zhemingloveme** [comment]
桌面客户端，手机apps，会提示“您的账户与第三方系统自动同步，无法在Steedos中维护组织结构。”
