### ISSUE TITLE
有权限的情况下移动用户，提示错误：“不能设置管理员或拥有者为无效”

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1102]
![image](https://cloud.githubusercontent.com/assets/6219465/24391319/f73b30ee-13c0-11e7-994c-10bc935a58fc.png)

移动用户操作方法：组织架构中拖动用户列表中用户到左侧组织列表某个组织，或者直接编辑用户列表中用户的所属组织。

**Comment by zhemingloveme** [comment]
经测试：拥有者或管理员在组织架构下对人员进行移动，可以正常移动。提示移动用户成功
