### ISSUE TITLE
流程设计器打不开

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1104]
是因为url中没有正确编译参数：http://192.168.0.21/packages/steedos_admin/assets/designer/index.html?locale={{locale}}&space={{spaceId}}

**Comment by yinlianghui** [comment]
需要打包测试。

**Comment by zhemingloveme** [comment]
打包21，流程设计器可以正常打开

**Comment by yinlianghui** [comment]
需要测试客户端

**Comment by zhemingloveme** [comment]
客户端可以正常打开流程设计器
