### ISSUE TITLE
工作区标题较长出现省略号时，鼠标放上去应该显示完整标题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1106]
![image](https://cloud.githubusercontent.com/assets/6219465/24445820/de26cc20-149d-11e7-8a39-9fafcbe47281.png)

**Comment by zhemingloveme** [comment]
经测试：IE11 Edge 工作区标题过长会出现省略号，鼠标滑过会显示完整标题
             手机apps  工作区标题过长会出现省略号，点击会显示完整标题
