### ISSUE TITLE
传阅报错

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#1108]
步骤1 A传阅给B，当A提交到申请单到步骤2后，B再传阅给C时点击传阅按钮报错

**Comment by sunhaolin** [comment]
`var a = [];`

**Comment by zhemingloveme** [comment]
经测试：步骤1 A传阅给B，当A提交到申请单到步骤2后，B再传阅给C时，流程可以正常继续，只要流程未结束，被传阅人填写意见，都会写到签核历程中！
