### ISSUE TITLE
申请单转发后，待审批中收到的转发过来的申请单离底部有很大空隙。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1118]
![image](https://cloud.githubusercontent.com/assets/6219465/24846829/b5af6058-1def-11e7-953f-7f496b274e04.png)

**Comment by yinlianghui** [comment]
BUG重现条件：
1.申请单内容高度足以显示滚动条。
2.待审核中转发申请单。
3.滚动条滚动到底部

测试要点：
1.PC上要测试。
2.手机上要测试。
3.非转发的待审核单子要测试。
4.转发给自己及转发给其他用户两种情况要测试。

**Comment by zhemingloveme** [comment]
经测试：手机app（ios   android），pc 转发后，可以正常显示页面
