### ISSUE TITLE
手机上返回按钮不容易操作，老是触发其旁边的其他按钮事件。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1130]
- 为返回按钮右边增加“返回”文字。
- “返回”文字i18n翻译。
- 手机电脑都增加“返回”文字。

**Comment by zhusijia** [comment]
测试一栏，两栏，三栏情况下是否会出现排版错误

**Comment by yinlianghui** [comment]
测试要点：
1. 多屏情况都要测试，即2栏，3栏效果都要测试。
2. anroid/ios手机要测试。
