### ISSUE TITLE
审批王分组字段改为粗体，字体大一号

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1134]
![image](https://cloud.githubusercontent.com/assets/6219465/25222858/3cea1d70-25ec-11e7-961a-b23976cddd74.png)

**Comment by baozhoutao** [comment]
现在分组字段显示看不清是因为流程图引用的css文件.section样式导致

**Comment by zhemingloveme** [comment]
经测试：在流程设计器中，添加分组字段后，表单样式设置为表格。新建此申请单，字体为粗体，字号变大
