### ISSUE TITLE
新建流程，响应比较慢时，多次点击同一个流程，草稿箱中会新建多张申请单

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#114]

**Comment by sunhaolin** [comment]
在事件nodeSelected中执行关闭modal操作 和 新建申请单操作，如果用户在modal关闭之前非常快的点击多次 会出现新建2张申请单的情况。
由于nodeSelected是控件 treeview的内核代码 故不好修改，此问题无法修改
