### ISSUE TITLE
测试： 测试各版本office下，office在线编辑窗口弹出前置问题

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1155]
测试时，将本地steedos安装路径中vbs文件夹中的edit.vbs替换为附件中的文件，并将后缀名改为vbs进行测试
[edit.txt](https://github.com/steedos/apps/files/980849/edit.txt)

**Comment by zhemingloveme** [comment]
修改文件后：
office 2016 
office 2003 
office 2010
可以打开，office前置
