### ISSUE TITLE
手机app，无法使用更改手机号功能

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#1156]
![s70508-13311352_ b d5173d0](https://cloud.githubusercontent.com/assets/23308088/25791441/e9d39642-33f2-11e7-88d2-064c27fd4c3b.jpg)

**Comment by zhemingloveme** [comment]
点击更改手机号，**安卓手机在第一次点击的时候会跳转到登陆界面**。输入账号密码后，会进入发送验证码的页面

**Comment by zhemingloveme** [comment]
![img_0569](https://cloud.githubusercontent.com/assets/23308088/25832539/be891006-349d-11e7-8ffe-96815336ca3f.PNG)

iphone端，点击更换手机号，弹出页面内容显示不全

**Comment by yinlianghui** [comment]
关联任务：手机app，第一个弹出更改手机号窗口会自动跳转到登录界面。 #1161
