### ISSUE TITLE
iphone客户端：填写文本节点，光标不会快速定位

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#1164]
![img_0578](https://cloud.githubusercontent.com/assets/23308088/25928434/d6a7f980-362e-11e7-9517-c74ec528f7eb.PNG)

如上图所示：输入一段文字后，发现有错误需要修改。通过点击，无法把光标定位到“共”字的后边，需要删除才可以做到
android客户端不会有这样的问题

**Comment by baozhoutao** [comment]
![Uploading IMG_3383.PNG…]()
