### ISSUE TITLE
流程脚本界面，自适应出现问题

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1174]
![lalpawnfesnat3dnbabnb4a_1920_1030 png_620x10000q90g](https://cloud.githubusercontent.com/assets/26241897/26140732/f0fb5a62-3b0a-11e7-9c22-855ec64686a9.jpg)

**Comment by zhemingloveme** [comment]
经测试：流程脚本页面，收缩左侧sidebar，页面正常显示。不随之收缩
