### ISSUE TITLE
手机端，删除按钮弹出框超大字体内容显示不全

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#1177]
上传附件点击删除，超大字体弹出框内容显示不全
组织架构中删除联系人，点击‘X’按钮，超大字体弹出框内容显示不全
android和小屏幕手机都有这个问题
![ladpacog8zzctb3na8dnahw_540_960 jpg_620x10000q90g](https://cloud.githubusercontent.com/assets/23308088/26192020/b260b18e-3be2-11e7-8328-3f29d0511633.jpg)

**Comment by yinlianghui** [comment]
请测试各平台相关功能是否正常。比如删除附件弹出框，取消申请弹出框。
