### ISSUE TITLE
手机验证码，验证成功后，不应该立刻关掉窗口造成用户看到验证成功提示。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1178]

**Comment by zhemingloveme** [comment]
![s70519-14080992](https://cloud.githubusercontent.com/assets/23308088/26235403/7cb9bb3c-3c9d-11e7-9e3a-62532ff0a842.jpg)
IE11 chrome Edge浏览器，设置手机号，验证成功后，延时自动关闭窗口
**手机app，设置手机号码。验证成功后，如上图所述，并没有自动关闭窗口**
