### ISSUE TITLE
绑定手机功能在国外平台需要一个开关来暂时禁用

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1184]
Meteor.settings?.public?.phone为true时才显示修改手机号及验证手机号相关功能。
但是保留组织架构中修改手机号功能。

**Comment by yinlianghui** [comment]
测试要点：
- Meteor.settings?.public?.phone为true时
- [ ] 所有手机号相关功能都可用
- Meteor.settings?.public?.phone为false时
- [ ] 系统设置中账户功能中手机号相关功能全部不显示。

**Comment by zhemingloveme** [comment]
设置中，账户未显示更改手机号码

**Comment by zhemingloveme** [comment]
在setting.json中可以配置是否显示修改手机号功能
