### ISSUE TITLE
测试：工作区管理员、分级管理员允许修改人员手机号（不发验证码），发送短信通知新旧手机

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1187]
测试要点：
1、工作区管理员和部分管理员都可以修改
2、修改后发送短信通知，新旧手机都要收到
3、不能修改为其他用户已经验证过的手机号
4、修改后同步更新个人信息中和其他工作区通讯录中的手机号

**Comment by zhemingloveme** [comment]
测试结果：
1、工作区管理员和组织管理员都可以修改人员信息
2、修改后，新旧手机都会收到短信通知
3、修改已验证过的手机号，会有警告提醒
4、修改后同步更新到个人信息和通讯录
