### ISSUE TITLE
选择下一步骤时，步骤处理人无法选择。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1190]
账号：weixuetao-秦港股份工作区-待办流程-基层单位法律意见咨询流程：选择“法律主管部门领导复核”步骤时，步骤处理人无法选择。
![hrbdedb0e0oa9qyzaj2itllwozxwf0aaxjnomnx39vcewpf7fbvod3ypalag r34pnwvnj59utzvvuvzf3mj5blijzblijdalofcarkecgnkesglkesgl0augvwcuqryceqsycxwp5daf4evfj2bza7uaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/26241897/26333921/1afc5568-3f94-11e7-8caa-6e365fa38328.png)
![lalozu4p180cpm0evq_1213_676 png_620x10000q90g](https://cloud.githubusercontent.com/assets/26241897/26333922/1b03d748-3f94-11e7-80ca-b1ca6d7ca803.jpg)

**Comment by zhemingloveme** [comment]
由于未找到人员，控制台报错。已更改为会有消息提醒  关联#1191
