### ISSUE TITLE
签批历程改成radio后，如果步骤个数比较多，会造成填写签批意见时，签批框跑到上面看不见的问题。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1193]
![image](https://cloud.githubusercontent.com/assets/6219465/26383247/3a32f5ba-4064-11e7-81cc-61ac447ad880.png)

**Comment by yinlianghui** [comment]
测试下来，4个步骤，大字体才会有问题。

**Comment by zhemingloveme** [comment]
4个步骤，大字体安卓手机点击签批。会显示滚动条
