### ISSUE TITLE
测试：客户端Word转pdf、编辑和查看功能

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1212]
测试时，先将本地的edit.vbs文件替换为附件中的版本
1、客户端对附件有编辑权限时才允许转为pdf
2、客户端中附件可编辑时，点击文件名直接打开本地word进行编辑，可查看时，点击文件名则直接查看，其他类型文件点击则下载
[edit.zip](https://github.com/steedos/apps/files/1049399/edit.zip)

**Comment by zhemingloveme** [comment]
已通过测试，秦皇岛重新打包PC客户端
