### ISSUE TITLE
PC客户端软件不支持弹出新窗口传递第二个参数，即window.open(“url”,"name")

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1213]

**Comment by yinlianghui** [comment]
现象：同一个widow.name，第一次会弹出，但是手动关闭弹出窗口后，就不能再弹出了。
目前影响到的功能：
绑定手机号（系统设置中更改手机号及右上角提示绑定手机号链接）、手机号登录、系统设置中重置密码

**Comment by steedos** [comment]
经测试，只有弹出 steedos 内部窗口时会有问题，如果弹出窗口指向百度，肯定没问题。
原因是代码：

	// 关闭时判断
	globalWin.on("close",function(){
		if(globalWin.disableClose == false){
			globalWin.hide();
		}
	});

**Comment by yinlianghui** [comment]
已完成的老任务。
