### ISSUE TITLE
导入用户逻辑修改

### ISSUE THREAD

**Issue by zhusijia** [steedos/apps#1276]
1.去除按照手机，邮件，用户名匹配功能。
2.设置密码功能更改，只要用户没有设置密码，就允许设置密码。

**Comment by ZHANGZHEMING1996** [comment]
在新增用户过程中遇到以下问题：
导入用户之前忘记校验用户名是否存在，导入此用户【数据库中有此username】，然后选择根据用户匹配，并没有提示重复。导入后，发现此用户的信息被update，并没有新增一个用户

这个问题是操作上的问题还是apps导入程序的问题？还是说，以后在新增用户使用导入功能时，一定要先去手动校验一下系统中是否有这个用户存在？

**Comment by steedos** [comment]
程序没问题，如果导入时选择按照用户名匹配，就就会覆盖对应的用户信息
