### ISSUE TITLE
日期、日期-时间值修改后，不触发onchange事件

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#130]

**Comment by steedos** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/186

**Comment by kamleshwebtech** [comment]
I am using bootstrap datetime picker. After doing lots of research, below code works for me:

    $('.data_date_of_birth').on('changeDate', function(event) {
      alert($(this).val());
    });

**Comment by HoiDam** [comment]
zZZ
