### ISSUE TITLE
审批王：openWindow 只能打开一个窗口， 再此打开窗口会将上一个窗口跳转掉。

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1301]
- 此问题应该是由于指定了固定的window name导致

**Comment by yinlianghui** [comment]
没有发现具体问题，打印窗口不会前置跟这事也没关系，先关掉，以后有具体问题再处理。

**Comment by yinlianghui** [comment]
去掉了Steedos.openWindow函数默认统一加window.name的功能，测试要点：

- [ ] 客户端打开各种新窗口，比如重置密码，打印，流程设计器等，右下角的托盘功能要能正常使用。
- [ ] 各种新窗口打开后要能再次重复打开，但是在原窗口未关掉的情况下，有的窗口再次打开会是打开新窗口，有的会是打开原窗口，只要能打开就行，但是如果新窗口可以编辑，原则上再次打开时应该打开新窗口，避免原窗口中的编辑未保存信息丢失（比如流程设计器）。
