### ISSUE TITLE
流程权限设置时，只对当前层级的用户有效，不能识别到下级部门

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1333]
流程设计器中，设置流程权限，谁能新增申请单。比如组织架构是这样：（华炎软件—研发部—研发1部），那么在流程设计器的选组控件中勾选（华炎软件），（华炎软件—研发部）此架构下的所有人可以新增此申请单，（华炎软件—研发部—研发部1）架构下面的用户则不可以新增此申请单     【bug】

**Comment by yinlianghui** [comment]
可以参考CMS的文章发布权限那块，调用统一的函数calculateUsers计算权限

**Comment by steedos** [comment]
现有功能没问题
