### ISSUE TITLE
 从手机推送进去后没有进入日历应用界面，而是进入待审核。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1341]
- [x]  能收到通知，但是当事件结束时也通知了，应该过虑掉已结束的通知。
- [x] 从手机推送进去后没有进入日历应用界面，而是进入待审核。

**Comment by liminglang** [comment]
推送使用的AppName是“workflow”,没有“calendar”，故点击推送只能进入到待审核

**Comment by liminglang** [comment]
计划在发推送时，在payload里加一个属性叫url，在发送之前把url先拼好了，目前拼成的url，先使用统一的/calndar，以保证手机上点击时能进入到会议管理模块，在接收端做判断，如果有url，则直接跳转。

**Comment by ZHANGZHEMING1996** [comment]
需要重新发布手机app
