### ISSUE TITLE
申请单意见显示bug

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#1342]
申请单上的意见只显示 申请单结束之前的， 使用的是instance.modified字段进行判断的，传阅给一个用户后，指定了用户可以填写意见的字段，然后将申请单提交到结束后，传阅处理人填写意见的用户意见是不显示在表单上的， 但是传阅处理人先提交，再取回时，就可以将意见填写到表单上了， 因为取回时，更新了instance.modified

**Comment by baozhoutao** [comment]
处理方案为：instance上添加finished_date。意见显示判断调整为依据finished_date

**Comment by sunhaolin** [comment]
当申请单结束时给finished_date赋值，当申请单状态由结束状态变为其他状态（结束-》进行中）时（重定位）删除finished_date的值
