### ISSUE TITLE
流程设计器里，设置提交等权限时，因为组织架构复杂，选人、选部门非常难用

### ISSUE THREAD

**Issue by zonglu666** [steedos/apps#1348]

**Comment by sunhaolin** [comment]
改动如下：
- 选组中 组织排序与设置保持一致
- 流程权限设置界面，鼠标放在已选择的人或组织上 显示提示完整的值
- 选人选组 框调大；
- 搜索的人员邮件未显示问题修改；
- 切换组织 用户重复问题解决；
- 岗位选择框增加搜索框；
