### ISSUE TITLE
开发组织架构设置权限功能：A组的成员设置为可查看B组成员信息。

### ISSUE THREAD

**Issue by zonglu520** [steedos/apps#1352]
- 在目前通讯录可以设置隐藏用户的基础上
- 开发 A组的成员设置为可查看B组成员
- 选人控件和通讯录都适用此规则

具体参考企业微信

改动比较大，请在分支修改

遗留问题：限制查看外部门功能中遗留问题 #1450

**Comment by yinlianghui** [comment]
测试要点：
- [ ] 重点测试选人选组控件，及相关的各种情况。
- [ ] 手机及PC上的情况都要测试，包括选人选组及通讯录。
