### ISSUE TITLE
监控箱中考虑分类优化 方便查找。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1363]
李志旭提出：监控箱中流程太混乱，可以根据 “观察员”与“管理员”监管的不同流程进行分类吗？

**Comment by steedos** [comment]
监控箱可以考虑先用weui显示流程选择界面，再显示下面的文件。工作区管理员列出所有流程，流程管理员列出可管理的流程

- 所有流程
- 行政类
  - 发文
  - 收文
- 人事类
  - 请假
  - ...

**Comment by ZHANGZHEMING1996** [comment]
建议在流程过滤时，可以选择用户已设置的星标流程
