### ISSUE TITLE
CAS 单点登录集成

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1364]

**Comment by zonglu520** [comment]
总结：steedos集成cas基本没有问题，从cas的登录界面登录后可以跳转到审批王客户端直接使用。
问题：oauth2协议待完善
cas的5.1.5版本的服务注册到mongo数据库有问题，需要重写方法。5.1.5的cas跑通后，使用oauth2协议，且oauth的授权码等信息可能只是存在内存中，没有存入数据库。
cas的5.2.0版本正在开发，oauth2协议不完善，会出现内存溢出等情况，已给cas项目报issue。
