### ISSUE TITLE
条件判断下一步处理人已经显示，但是提交的时候，还是提示系统没取到值。要多次提交，才可以成功。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#143]
![image](https://cloud.githubusercontent.com/assets/15027092/16005676/1e450650-319b-11e6-85ae-8ba8ef10611b.png)

**Comment by baozhoutao** [comment]
此问题是由于计算下一步处理人(选择部门字段参与计算)时，第一次没有得到选择部门字段值，导致缓存了计算失败的提示信息，在选择部门字段后，再此计算下一步步骤时，没有重置提示信息导致。
