### ISSUE TITLE
条件判断后，下一步处理人显示为Object。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#144]
![image](https://cloud.githubusercontent.com/assets/15027092/16005771/9a6d528c-319b-11e6-81e8-ab9a7515f25c.png)

**Comment by baozhoutao** [comment]
请陈志培在测试平台重现此问题

**Comment by chenzhipei** [comment]
未还原此bug

**Comment by baozhoutao** [comment]
在有选人、选组控件的页面直接F5刷新 可以重现此问题。
