### ISSUE TITLE
正在编辑时，来了一条新的待办，点击这条推送，然后关闭word上传后，正文就会上传到新的待办申请单中，原待办中的正文丢失

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1442]
此问题是由于在线编辑上传时，使用了Session.get("instanceId")变量导致， 请给在线编辑重新设置一个Session变量， 应该分离 instanceId、space 2个变量

**Comment by steedos** [comment]
Session变量应该记录下正在编辑的instanceid，提示上传之前，切换回对应的instance

**Comment by chenzhipei** [comment]
请测试:
1、正文、附件编辑时，点开新待办推送后，上传正文/附件
2、新建正文时，点开新待办推送后，上传正文
