### ISSUE TITLE
限制查看外部门功能中遗留问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1450]
可以先参考下企业微信怎么处理的。
- [x] 组织管理员如果有额外查看部门权限，那么在新增及修改用户时，用户所属组织属性也可以设置成额外部门，这应该是不合理的。

**Comment by yinlianghui** [comment]
参考过企业微信了，它是在添加及修改用户所属组织时能看到额外的组织，但是选中分配的时候会报错提示没有组织权限。

我在我们的系统测试下来，有以下问题：
1.上述提到的设置成额外部门，在我们目前的程序中确实可以直接设置保存，应该在后台before.insert/update统一判断处理。
2.组织管理员目前没有添加成员功能，企业微信是有的，应该加上。
3.第1点跟之前账户功能中关于组织权限的逻辑设计有漏洞，之前是

**Comment by zhusijia** [comment]
添加用户到某个组织中时，需要是组织管理员或者有该组织的权限

编辑用户的所属部门，非工作区管理员需要以下权限：
1.原组织至少需要一个组织的权限
2.对于移出的组织需要有权限
3.对于添加的组织需要有权限

添加部门时，需要有该部门的上级部门的权限

编辑部门，非工作区管理员修改部门，需要以下权限：
1.需要有原组织或原组织的父组织的管理员权限
2.需要有改动后的父组织的权限

**Comment by liminglang** [comment]
11月30日  在测试用户导入工作区，21的库，账号lml（非工作区管理员，是行政部和财务部的组织管理员），测试结果：
1.移除移入用户功能正常，编辑部门功能正常
2.编辑财务部，直接点击更新，弹出错误提示“您没有该上级部门的权限”（bug已修正）
3.在财务部下搜索“qqqq”,按回车或点击搜索，界面一直loading（bug，已修正）
4.在财务部下搜索“qqqq”,第一次搜索无效，第二次搜索得到结果了（bug,已建issue）
