### ISSUE TITLE
组织架构问题清单

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1459]
- 增加用户，输入已有邮箱，报内部服务器错误
- 左侧组织结构树，设置的排序号无效
- 导出功能只导出当前选中的部门，很傻，应该导出所有部门的数据
- 输入搜索条件后，按回车没反应

**Comment by ZHANGZHEMING1996** [comment]
- 增加用户，输入已有邮箱，用户信息被更新
- 导出用户，每次导出工作区所有用户
