### ISSUE TITLE
关于导入用户和新增用户的问题

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1460]
1、通过excel导入用户，手机、邮件、用户名如果重复，信息就会被更新【秦港这边需求：导入用户时，应该提示我，是不是有重复，我要不要覆盖用户信息】

- 拟调整为：
  - 对于工作区已有的用户，如果通过手机或者邮箱找到用户，就会覆盖用户信息。如果通过用户名找到用户，对于已存在的用户直接报用户名已存在。
  - 对于非本工作区的用户，如果通过手机或者邮箱找到用户，就会邀请用户，如果通过用户名找到用户，对于已存在的用户直接报用户名已存在。
  - 请更新设计文档

===
以下不处理
2、手动点击添加用户，添加成功后，还需要手动去设置用户的密码？【那如果要新增很多用户，需要把每个用户的密码都设置一遍？】 （添加用户的页面，应该有一栏设置用户的密码，不需要二次去设置用户密码）

**Comment by steedos** [comment]
1、如果不希望信息被覆盖，不应该选择用用户名匹配。可以选择用手机号匹配。这样如果用户名重复会提示。
2、不建议管理员在每次添加用户时设置密码，而是设置手机号，第一次当用户自己用短信登录。

**Comment by ZHANGZHEMING1996** [comment]
![image](https://user-images.githubusercontent.com/23308088/33250023-f46d0550-d368-11e7-84bb-d05c26a92613.png)

**Comment by steedos** [comment]
知道问题了，现在不能选择匹配字段，而是按照手机号或邮箱或用户名匹配，这个规则有问题。确实会覆盖用户信息。

**Comment by steedos** [comment]
拟调整为
- 对于工作区已有的用户，如果通过手机或者邮箱找到用户，就会覆盖用户信息。如果通过用户名找到用户，对于已存在的用户直接报用户名已存在。
- 对于非本工作区的用户，如果通过手机或者邮箱找到用户，就会邀请用户，如果通过用户名找到用户，对于已存在的用户直接报用户名已存在。
