### ISSUE TITLE
工作区管理员在组织架构界面，点击刷新按钮，会看不到隐藏的组织，应该能看到才是对的

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1470]
CN上就一直有这个BUG，不严重，因为正常情况下从其他界面点击组织架构是没有问题的，只有正好停在组织架构界面点击刷新才有问题。

切换工作区的时候也有这个问题。

处理内容：
1 隐藏的部门刷新后，管理员会看不到此部门，即使注销后，再登录也看不到。
2 部门管理员不能看到隐藏的子部门

**Comment by ZHANGZHEMING1996** [comment]
工作区管理员可以看到根组织下所有组织（包括已隐藏组织）
