### ISSUE TITLE
高级搜索过滤流程问题

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1480]
- 高级搜索只显示我可以拟写的流程
- 别人发来，我审批过的流程   无法通过高级搜索进行流程过滤？

**Comment by lizhenghotoa** [comment]
普通用户：可拟写流程、处理过的流程。 特殊用户：可拟写流程、处理过的流程、有监控权 观察权限的流程。

**Comment by steedos** [comment]
做不到判断处理过的流程，因为计算量太大了。
