### ISSUE TITLE
优化发文单里的“拟搞单位”

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1484]
所属的全部组织都为可选项，并可以修改

**Comment by baozhoutao** [comment]
方案为：
1 表单脚步中添加脚步：
`CoreForm.myorgs_filter = {space: Steedos.spaceId(), users: Steedos.userId()};`
2 拟稿单位字段的输入选择中，填写脚步：
`var foo={};db.organizations.find(CoreForm.myorgs_filter).fetch().getProperty("name")`
