### ISSUE TITLE
某些情况 新建正文报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1485]
在表单 文件标题 字段输入多行文字时，点击“保存”按钮以后，新建正文报错，错误信息是“下标越界”（具体错误信息见图片）。
<img width="960" alt="9b217fdf464dee64a735fcd0bab1421" src="https://user-images.githubusercontent.com/26241897/33410776-cdc2baa2-d5bc-11e7-974b-d47b591836d7.png">
<img width="960" alt="c5dfb30635812d367196d24d4f25f72" src="https://user-images.githubusercontent.com/26241897/33410777-cdf696f6-d5bc-11e7-8d62-6f9020249110.png">
<img width="960" alt="553bee7bc73064a593b5019dee69dc8" src="https://user-images.githubusercontent.com/26241897/33410820-0b79ad24-d5bd-11e7-8d68-5f2fdac243af.png">

**Comment by chenzhipei** [comment]
此问题是由于正文标题换行有回车符导致的

**Comment by ZHANGZHEMING1996** [comment]
标题中如果用回车换行，新建的.doc默认不显示_无回车行
