### ISSUE TITLE
选人选组隐藏组织及排序相关问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1487]
1.除了工作区管理员外，其他任何用户在选人选组控件中都看不到隐藏组织，即使用户主要部门或所属部门本来就是隐藏组织。
2.选人选组控件及通讯录中组织树排序问题。

详细规则请参考github中业务逻辑文档【隐藏组织功能规则明细】。

**Comment by ZHANGZHEMING1996** [comment]
新建一个字部门，默认排序号为100。设置排序号为空时，再次编辑子部门时，排序号还会默认为100，【囧】
