### ISSUE TITLE
新建表单，修改表单内容，根据条件判断后，下一步骤名会变，处理人不会变。审批节点的岗位处理人是自动显示的，但是填写节点的处理人属性是审批时指定人员。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#149]
下一步骤：审批
![image](https://cloud.githubusercontent.com/assets/15027092/16005948/b6d38120-319c-11e6-8900-e7b52d26ca01.png)

下一步骤：填写
![image](https://cloud.githubusercontent.com/assets/15027092/16005967/c829bd72-319c-11e6-964a-e0774198858b.png)

**Comment by baozhoutao** [comment]
此问题是： 当A步骤的处理人 也在B步骤的处理人范围内时， 从A步骤切换到B步骤，会默认选中A的处理人。

**Comment by baozhoutao** [comment]
修改后：
  1 下一步处理人只有1个时，会默认选中第一个。其它情况都不选中。
  2 下一步处理人有多个时，用户选择下一步处理人后， 修改提交人、表单字段值， 将会清空下一步处理人，需要重新选择。

**Comment by chenzhipei** [comment]
当前表单暂存后，先修改下一步处理人，再修改提交人、表单字段值，下一步处理人的值没有清空，而是修改前暂存的下一步处理人。
