### ISSUE TITLE
qhd强制手机验证

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1491]
- 从右上角改为从直接跳转路由到手机号绑定界面，如果没绑定，就不能做其他操作。
- 通讯录权限设置中增加一栏：无需绑定手机号用户，设置后，就排除哪些人不强制绑定。
- 如果未设置任何无需绑定手机号用户，则所有用户都强制要求绑定手机号。

发布部署相关：
CN上要设置forceAccountBindPhone为true，expiredDays不设置。
US上不要设置forceAccountBindPhone及expiredDays
QHD保持不变，但是ignoredUsers中的设置要迁移到设置界面中重新设置一次。

业务规则文档见：【强制绑定手机号功能规则明细.md】
```
“public”：{
    "phone": {
      "forceAccountBindPhone": true,
      "-expiredDays": 30
    }
}
```

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/33541703-056ff0ae-d90b-11e7-99b0-5774f41cec4e.png)

**Comment by yinlianghui** [comment]
CN上要设置forceAccountBindPhone为true，expiredDays不设置。
US上不要设置forceAccountBindPhone及expiredDays
QHD保持不变，但是ignoredUsers中的设置要迁移到设置界面中重新设置一次。

**Comment by yinlianghui** [comment]
测试要点，请参考规则文档：【强制绑定手机号功能规则明细.md】

- [ ] PC上要测试
- [ ] 手机上要测试

**Comment by ZHANGZHEMING1996** [comment]
用户只有一个工作区，在强制绑定手机号页面，点击工作区logo，可跳过强制绑定页面
