### ISSUE TITLE
监控箱中点击第二页公文 返回后 返回到第一页列表

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1497]

**Comment by baozhoutao** [comment]
此问题是在：优化flows订阅后，开始有此问题的。
原因是在打开申请单时，订阅了flow数据， 导致了instance list 的selector进行了重算，引起Tabular重置

**Comment by baozhoutao** [comment]
此问题请用 流程管理员并且不是工作区管理员的帐号测试
