### ISSUE TITLE
桌面客户端新版本更新提醒

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1499]
- 系统打开后，检测当前版本号，如果和服务端返回的不一致，就打开浏览器提示用户下载更新。
- 服务端在代码里面记录当前最新的客户端版本号。

**Comment by chenzhipei** [comment]
需要分别测试"华炎办公"和"集团OA"两个客户端

**Comment by ZHANGZHEMING1996** [comment]
- 华炎办公 点击下载，跳转到官网客户端下载页面
- 集团OA   点击下载，跳转到内容数字港口
