### ISSUE TITLE
已注册过的邮箱，提示信息没有国际化

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#150]
![image](https://cloud.githubusercontent.com/assets/15027092/16005996/09e52c1a-319d-11e6-9cd1-0709cda1a038.png)

![image](https://cloud.githubusercontent.com/assets/15027092/16005998/0fb2b090-319d-11e6-86b5-88317fa95e0a.png)

![image](https://cloud.githubusercontent.com/assets/15027092/16006000/162297e2-319d-11e6-8949-0e691e65c038.png)

**Comment by yinlianghui** [comment]
已解决，只重现了“已注册过的邮箱，提示信息没有国际化 ”。
其他两个翻译问题没有重现。
