### ISSUE TITLE
增加Session变量apps ，用于标记主菜单显示哪些Apps

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1505]
- apps = null，显示所有apps，保持header完整功能。
- apps = [], 主导航栏为空，右上角人员下拉菜单只有注销按钮。
- apps = ["calendar"], 主导航栏只显示当前App名称，右上角人员下拉菜单只有注销按钮。

**Comment by yinlianghui** [comment]
测试要点：
只要在浏览器控制台运行脚本设置变量apps ，观察到顶部导航正确变化就行。
`Session.set("apps",xx)`
