### ISSUE TITLE
批量取消分发问题

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1509]
- 批量取消分发页面，拟稿人分发改名：全选
- 批量取消分发，点击确认后，提示取消成功，应该自动关闭弹出窗口
- 关闭按钮改成取消

**Comment by sunhaolin** [comment]
- [ ] 批量取消分发，点击确认后，提示取消成功，应该自动关闭弹出窗口
- [ ] 关闭按钮改成取消
