### ISSUE TITLE
文件标题中，特殊字符优化

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1510]
- 表单标题中，有特殊字符，保存文件后打开报错。张建辉提出，在保存时应提示：标题中有非法字符，不予保存
- 在word中文件夹名不能有的符号为：
“?”、“、”、“╲”、“/”、“*”、““”、“”“、“<”、“>”、“|”。
因为这些符号在系统中有特殊含义，用在文件名中就会导致错误的解析。
命名规则如下：
1、允许文件或者文件夹名称不得超过255个字符；
2、 文件名除了开头之外任何地方都可以使用空格；
3、文件名中不能有上面规定的符号。

**Comment by baozhoutao** [comment]
解决方案：
在生成文件名称、正文名称时，直接替换掉特殊字符：? * : " < > \ / |
