### ISSUE TITLE
点击查看分发后申请单，报错

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1511]
![image](https://user-images.githubusercontent.com/23308088/33643958-082ef36c-da7d-11e7-99a0-f4929efbe10f.png)

**Comment by baozhoutao** [comment]
使用相同的账户、申请单、数据库、develop 分支代码没有重现此问题

**Comment by ZHANGZHEMING1996** [comment]
待23打包qhd分支后，继续观察是否还有此问题

**Comment by ZHANGZHEMING1996** [comment]
打包后，未发现此问题
