### ISSUE TITLE
选人选组在人很多的时候显示不全

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1515]
![image](https://user-images.githubusercontent.com/6219465/33753492-897b5400-dc22-11e7-87c8-86aea6ec2982.png)

指的不是选人选组弹出框本身的bug，而且是值保存后显示的bug

**Comment by chenzhipei** [comment]
目前选人控件有问题，单选时会有默认值，但下一步处理人却为空，已还原代码
