### ISSUE TITLE
取消分发优化

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1516]
分分发可以批量取消，并且分发下去的文件已经结束，也可以取消分发。分发下去的文件删除，在其分发文件的历史步骤里应当删除或做删除标记。

**Comment by sunhaolin** [comment]
- [ ] 分发可以批量取消
- [ ] 并且分发下去的文件已经结束，也可以取回
- [ ] 分发下去的文件删除，在其分发文件的历史步骤里应当删除或做删除标记。

**Comment by sunhaolin** [comment]
等待跟用户确认： 分发下去的文件已经结束，也可以取消分发
