### ISSUE TITLE
在线编辑优化

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1517]
编辑文档时，点了新来的待办推送后关闭word上传，正文会上传到新的待办申请单中  这个处理建议加入提示，类似“您正在编辑公文，请保存后再打开”的提示。

**Comment by ZHANGZHEMING1996** [comment]
![default](https://user-images.githubusercontent.com/23308088/33793809-a8e925b0-dcf9-11e7-8c20-1685e7329038.png)
