### ISSUE TITLE
发送后 历史步骤中显示已读状态

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1519]
河北港口集团公司部室传阅笺--资本市场资讯（2017）第47期--富军已经发送，但是历史步骤仍显示“已读”，并且文件没有到达下一步骤。

**Comment by sunhaolin** [comment]
数据已修正，问题出现在新版本上线之前，新版本上线之后后续再观察

**Comment by ZHANGZHEMING1996** [comment]
版本以上线，近一周、未发现类似问题
