### ISSUE TITLE
A分发到B流程，B 流程丢失了A 的正文。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1520]
集团公司发文 曹子玉同志在集团领导干部大会上的讲话（id：96qBeqyJiihK8cua3）分发下去的 集团领导传阅笺（可参考申请单 id：zNu6fRtpdBRZa7nza）、集团机关部室传阅笺（可参考申请单 id：H7ZT5MubqgEjCfybT）和集团基层单位收文（可参考申请单 id：dc3G47WRKfKQQXPaD）这分发的三类流程 发文正文丢掉了。

**Comment by sunhaolin** [comment]
是老数据没有新加的字段distribute_from_instances 导致的
