### ISSUE TITLE
Meteor 版本升级

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1526]
- 重点是手机客户端自动更新的功能之前重写过meteor内核包autoupdate，这个需要检查是否需要更新
- 可以参考Rocket Chat

**Comment by sunhaolin** [comment]
- autoupdate 包已参考rocket chat升级至version: '1.3.12'
- 在21打包1.5.1分支后 测试autoupdate功能正常，app里能自动检测并弹出新版本更新提示
