### ISSUE TITLE
在apps中添加headers ，支持跨域访问，即build之后的apps代码，启动后，即使不用nginx也可以正常通过app访问

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#1528]
上线后，需要调整nginx配置文件，移除nginx中的跨域访问相关配置：
add_header 'Access-Control-Allow-Headers' 'Origin,X-Requested-With,Content-Type,Accept';

**Comment by ZHANGZHEMING1996** [comment]
21、23打包更新后，未发现明显问题。服务正常使用
