### ISSUE TITLE
客户端主窗口中打开新窗口后不关闭，在主窗口再次点击打开同一个新窗口，这时关闭新窗口会把主程序退出

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1535]
比如打开申请单打印或者密码重置窗口就会有上述问题，但是如果每次都把新窗口关闭的情况下不会有这个问题

**Comment by yinlianghui** [comment]
通过给主窗口打日志的方式达到访问主窗口的目的，
这样就可以避免多次打开同一个子窗口的时候，关闭子窗口时会把主窗口一起关掉了

**Comment by ZHANGZHEMING1996** [comment]
console.log:
globalWin.close(true);
