### ISSUE TITLE
有时流程图显示时连接线会消失。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#154]
![image](https://cloud.githubusercontent.com/assets/15027092/16006227/68d8a1b0-319e-11e6-8320-3579958001e2.png)

**Comment by sunhaolin** [comment]
未能重现此问题

**Comment by chenzhipei** [comment]
修改完表单，点击保存，再次点击流程时，线会消失

**Comment by sunhaolin** [comment]
已重新修改 请陈志培重新测试
