### ISSUE TITLE
管理员可以解除申请单附件的锁定

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1550]
- 点开附件，弹出窗口显示锁定人和锁定时间。
- 管理员在弹出窗口可以点击“解锁”按钮锁定。
- 文件被解锁后，原修改人如果点保存就失败。

**Comment by ZHANGZHEMING1996** [comment]
第三条：文件被解锁后，原修改人如果点保存就失败。     
目前是：文件解锁后，原修改人还是可以保存并上传新版本

**Comment by ZHANGZHEMING1996** [comment]
![image](https://user-images.githubusercontent.com/23308088/33978445-bf58f9bc-e0da-11e7-9b11-5a2776d4f8b1.png)
