### ISSUE TITLE
在服务端记录当前spaceId等信息

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1561]
-  将相关代码移动到
 steedos-base: https://github.com/steedos/creator/commit/645ad7d824bd64291b38bc7348f845064207cd16
- 在服务端写一个method，保存spaceId, spaceName, userId, userFullName 到ServerSession
- 切换工作区时，调用此method
- 主要目的是确保在服务端调用method时，能够取到当前工作区的Id，顺便可以监控哪些工作区的哪些人在连系统。

**Comment by ZHANGZHEMING1996** [comment]
全局函数:ServerSession.get();
打印出相关信息
![image](https://user-images.githubusercontent.com/23308088/34024685-85069826-e186-11e7-827d-95955835a985.png)
数据存在server_sessions表上
