### ISSUE TITLE
App crashing at start

### ISSUE THREAD

**Issue by hpecsa** [steedos/apps#1582]
Hi 
I am getting below trace when starting the app. Can you assist pls ?
Thx

[[[[[ ~/worspace/apps ]]]]]

=> Started proxy.
=> A patch (Meteor 1.4.4.5) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
I20171220-21:08:23.507(-5)? TabularTables autorun...
I20171220-21:08:26.081(-5) (migrations_server.js:82) Migrations: Not migrating, already at version 6
W20171220-21:08:27.128(-5)? (STDERR) /home/bassem/.meteor/packages/meteor-tool/.1.4.1_3.ltnf68.znzs++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171220-21:08:27.128(-5)? (STDERR)            				throw(ex);
W20171220-21:08:27.129(-5)? (STDERR)            				^
W20171220-21:08:27.129(-5)? (STDERR)
W20171220-21:08:27.130(-5)? (STDERR) TypeError: Cannot read property 'calendar_remind' of undefined
W20171220-21:08:27.130(-5)? (STDERR)     at packages/steedos_calendar/server/methods/alarmPush.coffee:11:25
W20171220-21:08:27.131(-5)? (STDERR)     at /home/bassem/worspace/apps/.meteor/local/build/programs/server/boot.js:299:5
=> Exited with code: 1

**Comment by liminglang** [comment]
it is OK

**Comment by hpecsa** [comment]
thanks
