### ISSUE TITLE
流程管理员，手机app，右侧的菜单按钮显示优化

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1588]
![s71223-15260534_ b f5cf157](https://user-images.githubusercontent.com/23308088/34318006-7b2c487e-e7f7-11e7-8617-70ace34781a9.jpg)

流程管理员在手机apps上，点击监控箱中的表单，右上角显示异常【并非每个申请单，都是以上情况】

**Comment by steedos** [comment]
没有更多时应该不显示
