### ISSUE TITLE
企业微信测试要点

### ISSUE THREAD

**Issue by zonglu233** [steedos/apps#1592]
- 单点登录

登录企业微信客户端后，点击审批王，可以直接跳转至“审批中心”页面。

- 组织架构同步

- [ ] 在企业微信端修改当前企业的简称，对应审批王工作区也应同步修改。

- [ ] 当前应用授权企业的范围变化后，对应审批王的通讯录也应同步修改。
- [ ] 企业微信通讯录中的部门、人员等有修改，，对应审批王的通讯录也应同步修改。

**由于同步机制是10分钟一次，所以企业微信的修改，在审批中不会立即修改，而是等到10分钟一次的同步任务执行才开始同步相应的工作区。**

**Comment by ZHANGZHEMING1996** [comment]
- 企业微信设置成管理员权限，审批王工作区没有同步权限信息为工作区管理员

**Comment by zonglu520** [comment]
1.工作区管理员来自企业微信的超级管理员，其他分组管理员不同步未工作区管理员。
2.用户目前仅用户名、职位可同步，邮箱、手机等敏感字段无法同步。
