### ISSUE TITLE
(沧州渤海文书)提交了之后单子没及时消失，触发暂存

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1593]
![152956f3-ba19-4fec-8361-c74575070025-3727-000003aa086301c1_tmp](https://user-images.githubusercontent.com/7553007/34344874-5d6f6a34-ea25-11e7-8dde-5770672e1af2.jpg)
沧州渤海文书

**Comment by ZHANGZHEMING1996** [comment]
经测试，未再次出现类似问题
