### ISSUE TITLE
部分电脑客户端在执行confirm()方法时异常，导致死机或客户端关闭。

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1596]
qhd测试平台 
股份公司文书账户登录gfgsws，拟写一个【股份公司发文】流程，模拟整理批阅文件到 文书处理或复核步骤
选择下一步骤处理人后，点击发送。客户端会自动关闭

**Comment by zonglu520** [comment]
宗路电脑测试正常，李明朗电脑也出现闪退情况。经测试，是脚本问题。

脚本在执行confirm()方法时异常，导致死机或客户端关闭。

**Comment by baozhoutao** [comment]
升级nwjs到0.19.5 即可处理此问题。 0.19.5不支持XP系统
