### ISSUE TITLE
增加“附件”类型字段

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#16]
（1）设置》流程编辑器，增加新的字段类型“附件”
（2）新增/修改表单时，如果有权限且尚未上传，则出现上传附件的按钮，点击即上传附件，这个字段的值 即为上传文件的名称；如果有权限且已上传（本人本步骤），则类似 最下面的附件显示，有链接、删除等；如果有权限且已上传（非本人本步骤），则类似 最下面的附件显示，没有删除 ［具体不同情形下的显示待进一步确认］
（3）显示表单时，如果已上传附件，则显示 上传文件的名称，并有链接，点击即打开此附件
（4）字段必填的控制，同其他类型字段
原始需求提出客户：上海仕驰

**Comment by steedos** [comment]
https://cn.steedos.com/kanban/b/f4WoHRKwJh8FeeMds/app/ioH8ymyeBRneW58qD
