### ISSUE TITLE
CN管理员添加成员，被邀请用户收不到邮件

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1606]
21上可以收到，但是收到的是英文。
![image](https://user-images.githubusercontent.com/6219465/34373897-ead7ef24-eb18-11e7-89b5-10d8b85f388d.png)

**Comment by yinlianghui** [comment]
21能正常发邮件，先fix掉英文翻译问题，后续观察看看CN是否会正常发邮件

**Comment by ZHANGZHEMING1996** [comment]
经测试：21收到新增的邮件内容翻译正常内容如下

已为您创建华炎云账号
--

您好  XXX,

请点击以下链接，填写相关信息。

http://office.steedos.com:8821/steedos/enroll-account/2B2IlTGIasqLbDXJ4KWSJg7RVDZq4PHo7QhDglIdKPR

谢谢！

CN邀请新用户发送邮件需跟进确认
