### ISSUE TITLE
流程修改后，草稿箱中的文件不会自动升级。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#161]

**Comment by chenzhipei** [comment]
进行中的表单，选择驳回时，会出现最新流程的节点。
![2016-06-14 16 22 33](https://cloud.githubusercontent.com/assets/15027092/16035988/747d7a46-324c-11e6-8cd3-13cffd653a3f.png)
在测试平台上
测试账号:chenzhipei@hotoa.com
工作区:Demo
测试流程：日期、日期-时间测试 19

**Comment by steedos** [comment]
保存后会升级
