### ISSUE TITLE
CN草稿箱，无法删除，点击申请单控制台报错【疑似表单公式配置异常导致】

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1615]
![13_44_13__01_03_2018](https://user-images.githubusercontent.com/23308088/34510928-e5ab339c-f092-11e7-8c86-15651bcbdac6.jpg)

具体情况找我要登录用户名及密码

**Comment by baozhoutao** [comment]
此问题原因为 此申请单表单上有子表类型字段，但是子表没有字段

**Comment by ZHANGZHEMING1996** [comment]
修改后，若子表没有字段，申请单可以正常新建、删除，新建字表时显示为空
