### ISSUE TITLE
CN需要支持自动进入门户应用功能

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1627]
先尝试实现之前一直用的默认进入第一个应用的方案，工作区配置默认应用的功能等Creator与apps整合后再考虑开发。

**Comment by chenzhipei** [comment]
1、设置门户应用排序号在100以内，系统默认进入第一个app
2、手机等移动端还是默认进入流程审批

**Comment by ZHANGZHEMING1996** [comment]
目前手机app也默认进入设置排序号的
