### ISSUE TITLE
监控箱，打开能管理的文件，增加分发功能。

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1632]
秦皇岛办公室提出
坚持要做，说如果监控箱 里加不了，在已办里 加也可以。
现在的重定位＋分发＋重定位，除了繁琐、容易出错之外，已有领导在追问为什么老是重定位、同时抱怨有文件没看到 。

**Comment by sunhaolin** [comment]
在已办中，申请单历史步骤中当前用户最新处理完成的步骤如果有分发的权限，则用户可以在已办中分发

**Comment by sunhaolin** [comment]
有bug， 已办中分发选择的流程范围有误
