### ISSUE TITLE
cfs包修改加前缀"steed:cfs-"，项目中引用的cfs包同一修改成加上"steedos:cfs-"前缀的包

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1647]

**Comment by chenzhipei** [comment]
测试要点：
1、各项目可对附件进行添加、删除操作
2、测试下载带特殊符号和中文文字的附件
3、apps客户端下对附件的编辑操作

**Comment by ZHANGZHEMING1996** [comment]
- 删除文章的附件报错：Uncaught ReferenceError: AdminDashboard is not defined

**Comment by chenzhipei** [comment]
再次测试creator(master分支)和apps(cfs分支)项目，放开records-qhd，测试档案归档附件相关问题
