### ISSUE TITLE
管理员可以给任意一个账号修改姓名，且用户姓名可以重名

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#165]

**Comment by steedos** [comment]
合同审批流程以 华炎软件的表单样式 为例

流程步骤： 开始－部门经理－行政部－相关部门会签－总经理－（金额>5万报董事长审批）－合同编号、用印－合同归档－结束

**Comment by steedos** [comment]
1, space_users修改name时，不更新 users.name
2, users 修改name 时，会更新space_users.name

**Comment by chenzhipei** [comment]
用户名可以重名，管理员可以在工作区中修改同名用户的名字进行区分。
