### ISSUE TITLE
免费版工作区，目前无法修改工作区管理员

### ISSUE THREAD

**Issue by ZHANGZHEMING1996** [steedos/apps#1650]
![image](https://user-images.githubusercontent.com/23308088/35202916-68c42834-ff60-11e7-99ff-30f66c0bd5ff.png)
只判断专业版工作区管理员才能修改logo

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/37016945-887221a8-2149-11e8-97ac-617f9caf6769.png)
