### ISSUE TITLE
文件和附件的排序，应该按照上传顺序排列

### ISSUE THREAD

**Issue by steedos** [steedos/apps#1655]
- 需要分别测试桌面端，苹果和安卓手机端

**Comment by sunhaolin** [comment]
现有规则： 按照附件上传时间由小到大排序，最新上传的附件显示在最下面，新上传的附件版本显示在最下面；
改为： 附件第一个版本按照上传时间由小到大排序，最新上传的附件显示在最下面，但是新上传附件版本不影响现有附件的排序
