### ISSUE TITLE
［QHD遗留问题］审批王申请单列表翻页控件需要指定到具体某一页的功能 #125

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1659]
比如 这个文大概是在第20页，我没办法直接选择到第20页，只能一点一点的点到第20页（期间可能还会跳到第一页），这个他们使用起来不太方便

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/35433718-642b5056-02bf-11e8-84f5-26b78ef7e8c0.png)

**Comment by marchtian** [comment]
QHD 王华宁 提出

**Comment by yinlianghui** [comment]
测试要点：
请测试PC/手机端翻页功能是否能正常使用，并且方便跳转到任何一页
