### ISSUE TITLE
待办文件后的数字和分类后的数字不符

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#1680]
![image](https://user-images.githubusercontent.com/6219465/36624464-98b5e54c-194a-11e8-8487-28496c9fd8e4.png)

点 “股份公司收文”，左侧显示 204条，右侧其实有 26页，也是不相符，见下图
![image](https://user-images.githubusercontent.com/6219465/36624478-c4de7efe-194a-11e8-9641-667cb6c19bf0.png)

**Comment by baozhoutao** [comment]
此问题原因：分类及流程待办数量是在前台计算，基于订阅的当前用户待办文件数据，此数据最多只订阅200条，因此会导致超过200条时，显示错误
方案为：直接在server计算出每个流程下的待办数量
