### ISSUE TITLE
beta上待审核列表出现undefined

### ISSUE THREAD

**Issue by liminglang** [steedos/apps#1693]
![image](https://user-images.githubusercontent.com/6219465/37008825-f8df19d0-211e-11e8-8e17-afa5cb78e278.png)

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/37020726-ccd91b5e-2157-11e8-9db3-20ab1d11b16d.png)


经查，代码没有发现问题。
出现上述现象原因是流程名称直接从新增字段instance.flow_name中取了，不再通过函数计算拿到，而cn上新建的instance是不会给instance.flow_name赋值的。
所以，只要从cn中新建的instance，在beta上看到的都会是undefined
