### ISSUE TITLE
企业注册时如何强制录入有效的手机号？

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1697]
手机号便于客户跟踪。
1. 现在的企业注册 页面不要求 录入手机号
2. 如果录入手机号，加入验证才能保证 手机号的准确

**Comment by yinlianghui** [comment]
考虑到时把CN上的强制绑定手机号放开后，让用户注册完自动登录后，强制绑定手机号，这样就不用改注册功能了。
请测试下新用户注册完后，是否会强制进入绑定手机号界面。
