### ISSUE TITLE
［QHD遗留问题］统计分析

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1702]
可对指定类型账号的文件处理情况进行统计和分析，包括在一定时间区间内指定账号处理每个文件的用时统计、在一定时间区间内每个指定类型帐号处理文件的平均用时统计，还可以对普通文件、办文、紧急文件和特急文件的平均用时进行分类统计，统计任务完成率情况，统计结果可以转换成excel报表。

**Comment by marchtian** [comment]
昨天，陈志培已在qhd的tableau server上试着发布了一个效率统计的页面。
1. 拟给部分人（集办文书、办公室主任等）增加“效率统计”自定义应用，点击进入全集团的效率统计的结果页面，
- 周期是定死的，目前发布的设为一周、可按实际情况改
- 可看到所有部室和单位的，所以只能开放给少部分人员
- 默认为图，可切换为表格
- 可在页面上 只显示 想要的部分人员（特定组）的数据
- 效率数据可导出

2. 如果要查其他时间段的，一是用之前的方法在自己的tableau客户端导出数据并查看；二是 正在探讨 是否可以增加上面的 效率统计页面

3. 其他人只能用之前的方法在自己的tableau客户端中查询 效率统计数据

**Comment by marchtian** [comment]
0320和王华宁沟通，提出2点
（1）增加3张表：1年（6月前－今天）、半年（6月前－今天）、季度（3月前－今天）
（2）平均耗时，希望改为 已处理、未处理 综合后的平均耗时，未处理的耗时认为是 今天－收到的时间
（3）在各时间段内，哪些单子 纳入统计范围，需要给出现在的规则

**Comment by marchtian** [comment]
0320和王华宁沟通，提出：
（1）增加3张表：1年（6月前－今天）、半年（6月前－今天）、季度（3月前－今天）
（2）平均耗时，希望改为 已处理、未处理 综合后的平均耗时，未处理的耗时认为是 今天－收到的时间
（3）在各时间段内，哪些单子 纳入统计范围，需要给出现在的规则

**Comment by marchtian** [comment]
现有数据还存在一个问题：人员只在主部门。
以技术中心文书为例：选技术中心有这个人；选部室文书就没这个人。

**Comment by baozhoutao** [comment]
以现在的方式不能处理此问题，原因如下：
接口最多取2个月的数据，如果有3个月，那么就有3万条instances，approve数量为50万，这样的数据不能通过mongo的$group脚本处理， mongo会报内存溢出

**Comment by baozhoutao** [comment]
定的方案为：按月结算
