### ISSUE TITLE
［qhd合同要求］工作日志

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1704]
工作日志。将现有PC端工作日志功能模块移植到移动端供用户查看。

拟增加链接，联系人 牛辰。

**Comment by marchtian** [comment]
192.1.1.188/worklog/default.aspx:name=XXX
XXX是OA登录的用户名

**Comment by marchtian** [comment]
老OA系统，修改  qgbg/logon/logon/steedos_sso_worklog.jsp
跳转到 192.1.1.188/worklog/default.aspx?name=XXX
XXX是OA登录的用户名

**Comment by baozhoutao** [comment]
更改文件：C:\qhd_oa\hotoa\webapps\qgbg\logon\logon\steedos_sso_worklog.jsp

**Comment by marchtian** [comment]
已上线。
暂时只给系统管理员开放了自定义应用的权限，其他待qhd确认后开放。
据说，仅工会在用。
