### ISSUE TITLE
qhd疑似个案：某岗位成员异常

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1706]
![2018-03-13 12 02 36](https://user-images.githubusercontent.com/7553007/37322075-7da0535e-26b6-11e8-806c-745a6c841bff.png)
![2018-03-13 12 02 20](https://user-images.githubusercontent.com/7553007/37322076-7df61e9c-26b6-11e8-8eea-552b8da7cd52.png)
![2018-03-13 12 02 05](https://user-images.githubusercontent.com/7553007/37322077-7e3e082e-26b6-11e8-8207-1699c1d9fa37.png)

**Comment by chenzhipei** [comment]
数据库flow_positions表中记录，users数组中存在null的记录，已修改

**Comment by marchtian** [comment]
已和秦皇岛 张建辉确认
