### ISSUE TITLE
qhd数据库岗位成员flow_positions表中存在users数组成员为null的问题

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#1707]
![image](https://user-images.githubusercontent.com/15027092/37329688-af8de5de-26d9-11e8-858d-1aaf0105db56.png)

**Comment by steedos** [comment]
用脚本清理掉错误数据即可

**Comment by chenzhipei** [comment]
数据库执行：
db.getCollection('flow_positions').update({users:null},{$pull:{users:null}},{multi:true})

**Comment by marchtian** [comment]
未再报 同样的问题，close
