### ISSUE TITLE
新版审批王中选择驳回时，会出现当前节点。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#171]
签核历程中当前节点已审批过
![2016-06-14 16 46 57](https://cloud.githubusercontent.com/assets/15027092/16036704/aca1cc1c-324f-11e6-868b-a1cf4799eed7.png)

![2016-06-14 16 22 33](https://cloud.githubusercontent.com/assets/15027092/16036584/2a1618ac-324f-11e6-912b-c1581f062dde.png)
在测试平台上
测试账号:chenzhipei@hotoa.com
工作区:Demo
测试流程：日期、日期-时间测试 19
http://192.168.0.155:3000/workflow/space/51edf29c49203b2899000026/inbox/575fac47cdda8e0090000003

**Comment by baozhoutao** [comment]
bug重现方式：此问题出现在当前步骤已经处理过的情况下，再次在此步骤进行驳回就能选择当前步骤
