### ISSUE TITLE
办公室关注的遗留问题

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1713]
（1）系统慢的问题：选人的时候有时系统加载时间比较长。但是用户也反馈系统时快时慢。（高峰时期服务器压力比较大，希望能增加应用服务器的数量。）{已增加应用服务，目前反馈已改观}
（2）通讯录用户没办法导出：系统管理员可以导出通讯录。组织管理员和普通用户没办法导出通讯录。{已上线}
https://github.com/steedos/apps/issues/1709
（3）效率统计分析问题：目前使用需要需要下载、复制链接等操作起来不方便。（已经提供了浏览器的界面，需求还在进一步沟通中，我们尽量满足需求。对于报表界面不能提供出的数据，我们想办法提供数据库脚本由管理员进行统计。）
https://github.com/steedos/apps/issues/1702
（4）手机号码验证：还需办公室内部确认后放开强制验证。（需要办公室确认短信费用的问题）
（5）股份：待办、监控、已办中翻页没规律性的跳回第一页问题。 （未能重现，可能是遇到服务器重新启动导致的。待进一步观察。）{已上线}
https://github.com/steedos/apps/issues/1725
（6）文件查询，输入内容含［］则查不到  ｛0321已上线｝
https://github.com/steedos/apps/issues/1682
（7）股份：催办对象不全 ｛已上线｝
https://github.com/steedos/apps/issues/1711
（8）股份：已办列表，增加“我的处理时间”，为我最近一次的处理结束时间。（3月23日新增需求，技术部门正在分析开发可行性。）｛已上线｝
https://github.com/steedos/apps/issues/1727
（9）短信费用的问题，需要技术中心和办公室协调解决。
（10）股份：归档后，在档案系统里打开发文的word版本报错｛已上线｝
https://github.com/steedos/apps/issues/1724
（11）股份：在股份的档案系统里有重复的文，怀疑是基层单位收文归档归到了股份公司里，需核查、处理掉
https://github.com/steedos/apps/issues/1729
（12）审批王申请单列表翻页控件需要指定到具体某一页的功能 
https://github.com/steedos/apps/issues/1659

**Comment by marchtian** [comment]
股份秘书科已提问题（约了下午确认）：
（1）点击 报送的信息详情后，返回上一步 信息列表页面 不方便。
https://github.com/steedos/creator/issues/192 之第1条
（2）信息报送数据导出，列表内容是按照固定排序还是按得分多少排序？排序还需要调整，建议按固定好的单位排序，或者按分数从高到低排序；提出没有报送信息的单位也应该显示在报表报送单位字段上。
https://github.com/steedos/creator/issues/192 之第3条
（3）［今天杨帅微信里报的］会议表单颜色变了
这个疑似还没重现，待下午当面沟通
