### ISSUE TITLE
优化find、findOne查询脚本，需要限制fields

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#1716]

**Comment by sunhaolin** [comment]
涉及功能点：
- 关联文件 `steedos-workflow\lib\models\instances.coffee`
- 图片签名 `steedos-workflow\lib\models\space_user_signs.coffee`, `steedos-workflow\server\publications\space_user_signs.coffee`
- 新建工作区创建表单流程模板 `steedos-workflow\lib\models\spaces.coffee`
- 新建申请单 `steedos-workflow\routes\api_workflow_drafts.coffee`
- 导出申请单 `steedos-workflow\routes\api_workflow_export.coffee`
- OPENAPI新建申请单 `steedos-workflow\routes\api_workflow_open_drafts.coffee`
- OPENAPI获取单个申请单信息 `steedos-workflow\routes\api_workflow_open_get.coffee`
- OPENAPI获取待审核申请单列表 `steedos-workflow\routes\api_workflow_open_pending.coffee`
- 转签核 `steedos-workflow\routes\api_workflow_reassign.coffee`
- 重定位 `steedos-workflow\routes\api_workflow_relocate.coffee`
- 取回 `steedos-workflow\routes\api_workflow_retrieve.coffee`
- 导出流程 `steedos-workflow\routes\export.coffee`
- 导出表单模板 `steedos-workflow\routes\export_table_template.coffee`
- 导入流程 `steedos-workflow\routes\import.coffee`
- 获取下一步处理人 `steedos-workflow\server\lib\get_handlers_manager.coffee`
- 字段对应关系 `steedos-workflow\server\lib\instance_manager.coffee`
- 获取流程管理权限 `steedos-workflow\server\lib\permission_manager.coffee`
- 消息推送 `steedos-workflow\server\lib\push_manager.coffee`
- 引擎：`steedos-workflow\server\lib\uuflow_manager.coffee`
    - 申请单新建、提交、审批
    - 通过脚本计算申请单名称
    - 待审核邮件通知
    - 表单字段可搜索
    - 催办短信
 
- 打印 `steedos-workflow\server\lib\workflow_manager.js`, `steedos-workflow\server\routes\instance.coffee`
- 分发管理 `steedos-workflow\server\methods\distribute.coffee`
- 修改流程状态（启用/禁用）`steedos-workflow\server\methods\flow.coffee`
- 分发/转发 `steedos-workflow\server\methods\forward_instance.js`
- 待审核申请单是否已读、审核意见 `steedos-workflow\server\methods\instance_approve.coffee`
- 未找到下一步处理人报错信息弹出（处理人类型为指定审批岗位） `steedos-workflow\server\methods\next_step_users_not_found.coffee`
- 草稿箱暂存/待审核暂存 `steedos-workflow\server\methods\save_instance.js`
- 星标流程 `steedos-workflow\server\methods\start_flow.coffee`
- 分类显示 `steedos-workflow\server\publications\categories.coffee`
- 打开申请单 `steedos-workflow\server\publications\instance_data.coffee`
- 草稿箱角标 `steedos-workflow\server\publications\instance_draft.coffee`
- 服务端生成可填写申请单 `steedos-workflow\server\routes\instance_draft_view.coffee`
- 申请单列表 `steedos-workflow\tabular.coffee`

**Comment by lizhenghotoa** [comment]
1、在流程列表界面 点击“流程”进行搜索，没反应。
2、催办时填写办结时间时 时间控件不出现选择24小时的小闹钟图标。
3、导入流程后，流程启用打不开。
