### ISSUE TITLE
归档到档案系统中的基层单位收文 ，在档案系统中打开各个版本正文word报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1724]
基层单位收文归档到档案系统时，原发文（发文分发到收文）正文的word历史版本也归档到收文的条目里了，并且word还打不开。理论上，收文 在档案里只有原表单和一个pdf正文。
可以参考档案系统具体条目  http://192.1.1.169/archive/home/file_display.jsp?CategoryId=10&FolderID=0&fieldParent=1&fileID=1812143 
 对应的OA中的申请单id：KQgZxm5gD3svYQCRR

**Comment by baozhoutao** [comment]
0d3215b
