### ISSUE TITLE
qhd：待办、监控、已办中翻页没规律性的跳回第一页

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1725]
李志旭、郭海潮提出：
（1）列表显示时，翻页至第3页，停留再此较长时间后，有时会跳转到第1页［偶发］
（2）待办里，到第3页处理某文，处理后，点击“返回”键会到列表页，大部分为回到第3页、有时会回到第1页［偶发］

--重现规则：在监控箱列表先按照流程过滤后， 在翻到非第一页， 在控制台执行此脚本：Steedos.deps.miniute.changed() 就会回到第一页。这个脚本是自动每10分钟执行一次。

**Comment by marchtian** [comment]
在正式平台、测试平台上测试，尚未发现此类问题

**Comment by baozhoutao** [comment]
已知重现规则为：
1、修改当前用户user表信息时， 申请单列表会返回到第一页
2、如果是在监控箱，修改space信息，申请单列表也会返回到第一页
