### ISSUE TITLE
［QHD遗留问题］股份的档案系统里有重复的文

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1729]
在股份的档案系统里有重复的文，怀疑是基层单位收文归档归到了股份公司里，需核查、处理掉

**Comment by marchtian** [comment]
我的想法：
（1）确认，新归入的是否没问题
（2）确认，股份发文分发到基层单位收文，归档单位 是 默认过来的，有没有隐患
（3）手动处理，已归档的重复件 怎么 核查并处理好

**Comment by baozhoutao** [comment]
此问题已和张建辉确认，是分发到其他单位的申请单，归档单位还是“股份公司”

**Comment by marchtian** [comment]
待处理 已误归入“股份公司”的文

**Comment by marchtian** [comment]
查OA数据库，得知约10个左右的账户误归了800多条股份基层单位收文 到 档案系统的“股份公司”全宗，得到了明细的instanceID纪录。
讨论得出2个方案：
一、重走一次审批王的归档
（1）写脚本修改800多个instance的value值：修正归档单位，并将记录设置为待归档
（2）系统自动重归档即可
二、直接修改档案系统的数据库
（1）依据instanceID，写脚本修改档案系统中的800多条记录，修改其全宗ID即可
待后续再处理。
