### ISSUE TITLE
qhd：子管理员在通讯录里，搜出来的用户没有编辑按钮，直接找到的可以编辑

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1734]
张建辉 反馈

**Comment by yinlianghui** [comment]
测试要点：

- [ ] 只要左侧组织数选中的组织有权限，则右侧无论是搜索还是找到的，都可以编辑。
- [ ] 右侧搜索到的数据范围应该限制在左侧所选中组织内，而不可以搜索选中组织以外的用户。【重要】
