### ISSUE TITLE
qhd：关于子管理员能管理用户的操作范围

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1735]
张建辉提出：
（1）子管理员，目前能“添加成员”，提出去掉。凡是新增用户，由系统管理员统一处理。
（2）子管理员，目前“设置主部门” 会报错。用户一般属于N个组，其中包括子管理员管的这个组、子管理员管的这个组的子组、不属于他管的其他组。目前，设置为哪个 都会报错。
（3）子管理员，修改用户所属组时，如果 去除  “不属于他管的其他组”，则报错。
建议思路1:修改所属组时，最下方的输入框里是当前所属组，每个组后面有个“x”，建议没有权限的就去掉这个 “x” 。
建议思路2:修改所属组时，最下方的输入框里是当前所属组，每个组后面有个“x”，建议去掉所有 “x”；可以在上面的树 点击 来  增减所属组。

最后方案：
1.在settings.json中加一个开关，qhd中子管理员不能"添加成员", CN及其他保持不变。
2.会报错的原因是后面统一改了校验函数，新的函数没有兼容设置主部门按钮功能，造成所有子管理员设置主部门都会报错，最后的规则是只要有编辑权限就能设置任何一个部门为主部门且不会判断权限，也不会报错。
3.做不到，目前有问题时是会提示到没有权限的，统一去年后面的"x"的话会影响正常使用的效果，而且这种情况比较极端。

注意qhd上版本时设置开关量：Meteor.settings.public.contacts.disableAddUserForSubAdmin

**Comment by yinlianghui** [comment]
注意qhd上版本时设置开关量：Meteor.settings.public.contacts.disableAddUserForSubAdmin
