### ISSUE TITLE
qhd集团秘书科：自动生成集团议题单通知流程的内容

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1737]
现状：通过“集团部室会议安排流程”，各部室提交的议题申请单都会集中到会议主持人（集团秘书），这时，添加一条“集团议题单通知流程”，须作如下操作：
（1）手动增加子表的内容：N行（可能是10条左右）议题，即对应N个“集团议题单通知流程”的议题申请单；
（2）执行N次手动关联文件操作，搜索并关联上N个“集团议题单通知流程”文件
融光提出：
（1）在“集团部室会议安排流程”的列表页可以 多选
（2）勾选后，点击某按钮新增1个“集团议题单通知流程”，自动关联上勾选的“集团议题单通知流程”文件，并 自动填写 子表的N行内容。
简言之，有点将 1个文件分发为1个文件的操作，引申为N个文件分发为1个文件的操作。不同就是，将原始的（主）字段的值 复制 到 新的子表里的字段中去（多行）。

**Comment by baozhoutao** [comment]
方案：
	* 相关文件添加事件
	* 事件中可以通过脚本设置申请单value
	* 优化相关文件选择页面，支持多选
	* 选择相关文件后，订阅相关文件的申请单信息。
	* 触发相关文件事件

**Comment by baozhoutao** [comment]
流程脚本：
```
$("body").on("after-save", ".save-instances-related", function(e){
	console.log("after-save....");
	_table_field = "会议详情";
	table_values = SteedosTable.getTableValue(_table_field);
	if(!table_values){
		table_values = []
		SteedosTable.setTableValue(_table_field, table_values)
	}

	start_index = table_values.length || 0

	_.forEach(e.related_instances, function(ins, index){
		_index = start_index + index;
		item_value = {"序号": _index + 1, "议题": ins.values["议题"], "汇报部门": ins.values["申请单位"], "参会单位": ins.values["参加单位"]};
		SteedosTable.addItem(_table_field, _index, item_value);
		SteedosTable.setTableItemValue(_table_field, _index, item_value);
	})
})
```

**Comment by lizhenghotoa** [comment]
1、关联文件界面 搜素框搜索的时候会有闪屏的现象。
2、第一次选择一个关联文件以后，需要在添加一个流程。子表中会重复第一次选择的流程。比如第一次添加了A关联文件，点击确定后，子表出现一条数据 1、A。发现还需要在添加B 关联文件，又勾选上B 流程后点击确定，字表上会出现三条数据，包括1、A。2、B。3、C。
