### ISSUE TITLE
perfect-scrollbar升级，steedos:perfect-scrollbar

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#1751]
直接使用官方提供的原始文件：https://github.com/utatti/perfect-scrollbar
不要再依赖keepnox:perfect-scrollbar meteor package，此package没有维护，还是使用旧版本的perfect-scrollbar，旧版本的perfect-scrollbar在多滚动条的情况下存在bug

**Comment by steedos** [comment]
https://github.com/steedos/creator/issues/1024
