### ISSUE TITLE
BUG:驳回到结束节点，填写完意见后，下一步处理人又显示出来了（不应该显示）

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#1762]
![_15234122928567](https://user-images.githubusercontent.com/6194896/38592833-ea57d46a-3d70-11e8-9b58-fa8e957dd35c.png)

此处共有2个bug：
1、驳回步骤显示了下一步处理人
2、选中的步骤与session中存储的stepId不一致

**Comment by baozhoutao** [comment]
此问题重现方式：
方式1：收到新申请单后，打开申请单，并选择驳回-结束 ，然后输入意见处理人字段会显示出来
方式2：打开申请单，选择驳回-结束，然后修改表单字段，处理人会显示出来

**Comment by baozhoutao** [comment]
测试范围：各种步骤类型，并且确认核准、驳回(开始、其他步骤、结束)、提交对应的下一步处理人范围是否与流程配置的范围一致

**Comment by baozhoutao** [comment]
测试流程：21 steedos数据库，账户：baozhoutao@hotoa.com 。工作区：测试邀请用户 ，流程：`bug测试 `分类下的 `条件步骤及签批步骤测试`
