### ISSUE TITLE
某账号修改不了排序号

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1764]
qhd测试环境可复原
修改 “nieyuzhong”的排序号报错；
修改 “nieyuzhong”的其他信息也报错；
修改别人的可以。
疑似这个账号有什么特殊性。

**Comment by yinlianghui** [comment]
孙老师已把该异常用户的邮件地址通过直接改数据库修正了

**Comment by marchtian** [comment]
已排查有问题纪录并处理
