### ISSUE TITLE
qhd：编辑部门 添加用户时，搜索出的用户需要显示主部门。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/apps#1810]
![image](https://user-images.githubusercontent.com/26241897/40402855-9c10c16e-5e80-11e8-962f-d4bdfb05ea6d.png)
![image](https://user-images.githubusercontent.com/26241897/40402884-ceb65ff2-5e80-11e8-8ed9-1a43b0f6a84a.png)

**Comment by steedos** [comment]
https://github.com/steedos/creator/issues/1031
