### ISSUE TITLE
用户登录工作区后，在工作区列表中，最好能显示每个工作区需要待审核的文件数量，否则用户不清楚哪个工作区有文件要处理。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#183]

**Comment by steedos** [comment]
修改 workflow_home
最上面新增各工作区的待审核文件列表。点击可以切换并进入工作区。类似老版本审批王。

**Comment by sunhaolin** [comment]
steedos_keyvalues表：
  user: string,
  space: string, 
  key: string, 如："badge"
  value: {
    "workflow": 1,
    "chat": 2,
    ......
  }
当space值为null时，key为badge对应的workflow的值为user所有space中待审核的申请单的数量之和
