### ISSUE TITLE
QHD：二公司的已归档文件，在（老）档案系统中查不到

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1845]

**Comment by baozhoutao** [comment]
问题原因是：
二公司发文流程归档档案系统中的数据：**所属年度为空**，导致在接收管理-文书简化-文件级-2018下看不到新数据，可以点到文书简化-文件级中看到二公司发文数据(数据太多，很难找)。

看了二公司发文流程，其所属年度值来自 文件编号(发文号)，但是发文号都是空的

**Comment by marchtian** [comment]
拟待后面有时间时 ，分析 二公司发文的发文号都为空的原因，及怎么改进，及怎么重归档

**Comment by marchtian** [comment]
检查，（1）自2018年8月28日发起的 二公司发文 都已经有 发文号了。（2）在新档案系统 里能查到全部记录。
已另建issue，本issue关闭
