### ISSUE TITLE
QHD：集团基层单位收文部分表单的归档单位 误为 集团公司了

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1877]
（1）LZ：确认 “集团基层单位收文” 的表单设置已无问题，新单子不会再有此问题
（2）CZP：查OA数据库，“集团基层单位收文” 的表单里 的“归档单位” 为 “集团公司” 的instance 清单
（3）SHL：参考https://github.com/steedos/apps/issues/1729 修改脚本并执行，修正这些instance的 归档单位，并将记录设置为待归档
（4）LZ：系统自动重归档后，检查确认老档案系统 记录是否已OK
（5）ZL：档案升级项目，修改数据库记录，重置 这些instance对应的档案记录的全宗

**Comment by lizhenghotoa** [comment]
目前集团基层单位收文无归档单位错误问题，通过排查之前已归档流程，以下几个单位在2018.1.11之前的申请单会有问题。
港口工程公司文书：2018.1.11之前（空或集团公司）归档到：	港口工程公司
地产（方大）公司文书：2018.1.10之前（只有一个）归档到：房地产开发公司
港丽电梯文书：2018.1.10之前  归档到：港丽电梯
海运煤炭交易市场（环渤海交易中心）文书：2018.1.10之前  归档到：	海运煤炭市场
后勤公司文书：2018.1.10之前（只有一个）归档到：后勤公司

**Comment by marchtian** [comment]
SHL已完成：
（2）查OA数据库，“集团基层单位收文” 的表单里 的“归档单位” 为 “集团公司” 的instance 清单
（3）参考#1729 修改脚本并执行，修正这些instance的 归档单位，并将记录设置为待归档

**Comment by marchtian** [comment]
系统自动重归档后，下属2个未归档：59Q8o3GB2Px9JYNS4，NCdxRhrWNgxtqhufq，手动归档也 失败，待检查确认问题所在。

**Comment by baozhoutao** [comment]
申请单中的 “归档单位” 为 “海景假日酒店”，档案中只有 “海景酒店”，导致档案系统归档接口报错。

**Comment by sunhaolin** [comment]
已设置 59Q8o3GB2Px9JYNS4，NCdxRhrWNgxtqhufq   “归档单位” 为 “海景酒店”，归档状态为未归档
