### ISSUE TITLE
新版流程设计器，设置流程时，开始节点默认的字段都没有选上，这样会导致新建时字段都不可填，应该默认都选上。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#188]
![image](https://cloud.githubusercontent.com/assets/15027092/16073965/e7974fec-331a-11e6-91d0-8843020d6e67.png)

**Comment by chenzhipei** [comment]
修改表单时新增某字段，保存后，在开始节点该字段默认没有勾选，旧版开始节点默认都是勾选的。

**Comment by steedos** [comment]
转移到新任务

**Comment by zhemingloveme** [comment]
目前21平台上，新建表单流程，开始时节点权限依然是没有选中，需要手动勾选☑️

**Comment by zhemingloveme** [comment]
经测试：在流程设计中，设计表单，配置流程，保存成功后，打开流程，新建表单，默认所有的字段都有权限，不需要手动打开权限。所有新建流程的开始节点的所有权限都是勾选状态的！
