### ISSUE TITLE
门户点击待办定位到具体的单子

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#1904]

**Comment by zonglu666** [comment]
https://uateip.dzug.cn:4430/eop-sso/login?service=http://192.168.0.81:3000/api/cas/sso 

 v-frankl    Sso2018

---

查找到的待办文件

{
            "id": "SwcjPGQqooPd7gjJe",
            "start_date": "2017-12-11T05:06:08.521Z",
            "flow_name": "公司发文",
            "space_name": "华炎软件",
            "name": "正文 (1)",
            "applicant_name": "MJ",
            "applicant_organization_name": "华炎软件",
            "submit_date": "2017-12-08T10:12:59.734Z",
            "step_name": "拟稿人处理",
            "space_id": "Af8eM6mAHo7wMDqD3",
            "modified": "2017-12-11T10:18:28.195Z",
            "is_read": true,
            "values": {
                "拟稿人": "MJ",
                "日期-时间": "",
                "日期": "",
                "文件标题": "正文 (1)",
                "下拉框": "",
                "多选": ""
            }
        },

**Comment by zonglu666** [comment]
https://uateip.dzug.cn:4430/eop-sso/login?service=http://http://192.168.0.81:3000/api/cas/sso   

v-frankl

**Comment by zonglu666** [comment]
### 本地测试链接

https://uateip.dzug.cn:4430/eop-sso/login?service=http://192.168.0.81:3000/api/cas/sso?redirect_url=/workflow/space/{{space_id}}/inbox/{{id}}

https://uateip.dzug.cn:4430/eop-sso/login?service=http://192.168.0.81:3000/api/cas/sso?redirect_url=/workflow/space/51ae9b1a8e296a29c9000001/inbox/QbKgnQd6YYqs7i5MN

 v-frankl    Sso2018

---

### 查找到的待办文件的

{
            "id": "SwcjPGQqooPd7gjJe",
            "start_date": "2017-12-11T05:06:08.521Z",
            "flow_name": "公司发文",
            "space_name": "华炎软件",
            "name": "正文 (1)",
            "applicant_name": "MJ",
            "applicant_organization_name": "华炎软件",
            "submit_date": "2017-12-08T10:12:59.734Z",
            "step_name": "拟稿人处理",
            "space_id": "Af8eM6mAHo7wMDqD3",
            "modified": "2017-12-11T10:18:28.195Z",
            "is_read": true,
            "values": {
                "拟稿人": "MJ",
                "日期-时间": "",
                "日期": "",
                "文件标题": "正文 (1)",
                "下拉框": "",
                "多选": ""
            }
        },
