### ISSUE TITLE
录制审批王应用案例之合同审批流程

### ISSUE THREAD

**Issue by steedos** [steedos/apps#192]
参考这个网页中的版本
http://oss.steedos.com/videos/case/expense.mp4

场景如下：
1、员工使用手机填单
2、领导使用手机审批
3、合同管理员查询导出合同清单
4、管理员定制表单
5、管理员定制流程

这个视频计划放在登录页和网站首页，做为快速向导。
可以先录制一个3分钟的简单版本，让后再录制详细的。

请田总设计，陈志培录制

**Comment by steedos** [comment]
合同审批流程以 华炎软件的表单样式 为例

流程步骤： 开始－部门经理－行政部－相关部门会签－总经理－（金额>5万报董事长审批）－合同编号、用印－合同归档－结束

**Comment by marchtian** [comment]
建议，可在视频的第一部分增加合同审批应用后的好处描述如下：
**降低合同风险**
执行规范的合同签署流程，实现业务、法律、财务等多部门的会签，显著降低合同签署的各种风险。
**提高审核效率**
原来，需要通过纸质文件人工流转，费时费力；现在，各级领导和相关人员，在手机和电脑上就能审批，大大提高了效率。
**合同查询方便**
在合同审批和合同执行的全过程中，有权限的人员都可随时随地调阅电子文件，还能查看文件的历史版本。
**跟踪监督到位**
合同信息可导出为合同台账，便于开展合同按计划执行、收款付款提醒、款项进度监督、项目绩效考核等工作。

**Comment by steedos** [comment]
取消任务
