### ISSUE TITLE
被重定位给A，再被重定位走，之前A的意见在意见栏中显示不出来了。

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#1921]
在重定位时, 系统检测当前的approve的处理人及步骤在之前是否有记录, 如果有, 则将除当前approve之外的最新一条approve(排除judge为terminated)的sign_show设置为true

**Comment by marchtian** [comment]
秦港测试平台测试：
秘书核稿时填写意见“同意”，运行到拟稿人分发时，管理员重定位到 秘书核稿，这时，表单上显示 秘书核稿 意见为“同意”
（1）秘书 只 修改正文，不点 “保存”按钮；管理员 再重定位到 拟稿人分发，则 表单上显示 秘书核稿 意见为“同意”、签核历程里最新一条 秘书核稿 步骤无意见
（2）秘书  点“保存”按钮，则 签核历程里当前 秘书核稿 步骤有意见、表单显示  秘书核稿 意见为灰色的“同意”；管理员 再重定位到 拟稿人分发，则 表单上显示 秘书核稿 意见为“同意”、签核历程里最新一条 秘书核稿 步骤无意见
