### ISSUE TITLE
分级授权：新建申请单时根据部门(树状)显示流程列表

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1933]
1. 左侧显示为组织架构（只显示单位的组织），右侧显示左侧选中单位对应的流程列表
2. 流程分类后续需要进一步讨论确认，暂时忽略该属性
3. setting.json增加开关量，is_group_company，开关开着才按上述规则显示流程列表，否则保持原样

- [x] 实现新建工作单时流程列表界面
- [ ] 其他需要弹出流程列表的地方都应该改为弹出这个新界面

其他需要弹出流程列表的功能迁移到：
需要实现统一的选择流程窗口的功能，原来的流程选择弹出框考虑作废 #1940

**Comment by yinlianghui** [comment]
- [ ] 已实现新建工作单时流程列表界面
- [ ] 其他需要弹出流程列表的地方都应该改为弹出这个新界面
