### ISSUE TITLE
工作区管理员，在creator中选择单位 ，上下级显示有误

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1943]
creator中，工作区管理员，“选择单位”

开始选择时，显示不对，没有显示在北天集团、矿区服务事业部的下面，而是 直接显示在 最下面了
![image](https://user-images.githubusercontent.com/7553007/50079161-cabcea00-0223-11e9-8bb1-811c94bd5db2.png)

点开 北天集团、矿区服务事业部后，显示正常
![image](https://user-images.githubusercontent.com/7553007/50079149-c1cc1880-0223-11e9-8727-34f3607ed8df.png)

**Comment by yinlianghui** [comment]
经确认，该问题是因为它的space_users没有设置company_id值
