### ISSUE TITLE
字段列表显示功能不可用：字段设置为列表显示后，没效果

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#1985]
此问题是由于#1322修改导致字段列表显示功能异常。

表单设计器上，设置某字段为“列表显示”
![image](https://user-images.githubusercontent.com/7553007/53783566-15115580-3f4d-11e9-84af-c4ebb8665884.png)

在收件、发件、监控中，以本流程过滤，列表显示中，依然没有 此字段
![image](https://user-images.githubusercontent.com/7553007/53783590-3d00b900-3f4d-11e9-9152-2779839c9fa9.png)

**Comment by marchtian** [comment]
23 上测试结果
gfgsws 进入，连续如此操作
（1）待办里，过滤“股份公司收文”，文号list
（2）监控里，过滤“股份公司发文”，文号不list
（3）监控里，过滤“股份公司收文”，文号list

**Comment by marchtian** [comment]
23 测试OK

**Comment by marchtian** [comment]
qhd-beta已更新，给集团、股份的 收文、发文配置后OK

**Comment by marchtian** [comment]
0426已上线，集团公司发文/收文、股份公司发文/收文  的 文件编号 已配置为 列表显示
