### ISSUE TITLE
QHD：通过传阅增加总法律顾问意见

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#1995]
### 【修改内容】
 - [x] 支持传阅时能写脚本
 - [x] 增加总法律顾问意见 字段、修改流程节点权限、修改表单样式
 - [x] 增加传阅脚本，实现：
  * 如果传阅对象为1人、且为总法律顾问，则不管三个勾是怎么勾的，都只认为是 勾选了 总法律顾问意见
  * 如果传阅对象为多人、且含总法律顾问，则弹出警告框、提示总法律顾问与其他人员的选项应不同 
  * 如果传阅对象为1至数人、且不含总法律顾问，则不管总法律顾问意见 是否否选、都认为没有勾选了 总法律顾问意见

### 【实际处理】
文书传阅时，分两次：
  * 选择 传阅对象为 总法律顾问1人，3个勾不用动，点“确认”则传阅给总法律顾问
  * 选择传阅对象为其他人（注意，不要选到总法律顾问），总法律顾问意见前的勾 可勾也可不勾（勾上也和没勾一个效果），其他两个勾 跟之前的处理一样，点“确认”则传阅出去。

**Comment by baozhoutao** [comment]
[通过传阅增加总法律顾问意见.zip](https://github.com/steedos/apps/files/3075928/default.zip)

**Comment by marchtian** [comment]
已打包到qhd-beta，测试OK

**Comment by marchtian** [comment]
0416 已上线
