### ISSUE TITLE
日期-时间字段必填，未填写情况下提交，字段匡标红，提示填写信息，填写完后，点击暂存，日期-时间框还是标红。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#211]
日期字段也是这个现象
![2016-06-17 14 52 11](https://cloud.githubusercontent.com/assets/15027092/16143057/e53f237c-349c-11e6-8b1a-70bdac713ced.png)

**Comment by baozhoutao** [comment]
此问题处理方案：
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L47  修改此文件setValue 方法中所有 input.val('xxxx') 为 input.val('xxxx').trigger('change')

**Comment by chenzhipei** [comment]
新增表单时，还未填写就已提示日期字段必填
