### ISSUE TITLE
多行文本只读显示前用 marked 函数处理

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#219]
多行文本只读显示前用 marked 函数处理，这样即解决了多行文本框中由于空格导致的换行在只读时没有换行的问题，又可以支持 Markdown 语法。

html = Spacebars.SafeString(Markdown(text))

**Comment by steedos** [comment]
请截图说明

**Comment by chenzhipei** [comment]
草稿箱中：
![2016-06-20 10 46 33](https://cloud.githubusercontent.com/assets/15027092/16182199/dfecc376-36d5-11e6-9c4d-647df856ffaa.png)
只读时：
![2016-06-20 10 46 57](https://cloud.githubusercontent.com/assets/15027092/16182210/fb85bc64-36d5-11e6-86ca-6a8a7c935d47.png)

**Comment by steedos** [comment]
测试请用实际中文或英文测试。这种案例在生活中不会发生。
