### ISSUE TITLE
邀请用户问题汇总

### ISSUE THREAD

**Issue by steedos** [steedos/apps#231]
我們公司有使用審批王的服務，目前在操作上遇到以下問題，想請您們協助處理。

1. 目前要將新進員工的帳號做新增的動作，但新版的審批王沒有這個選項按鈕，無法新增。（如下圖）
若是用新建用戶的方式，卻又收不到認證信件可以設密碼。
點選『忘記密碼』畫面也直接跳掉，不能使用。

![default](https://cloud.githubusercontent.com/assets/3104826/16262776/bb05edce-38a3-11e6-8a36-4ee3db2e5469.jpg)

2. 在新版的審批新建好帳戶之後，新建的資料上傳完，到設置查看，e-mail 信箱會跑掉，在流程上除了公司名不會更動外，主管、部門等其他資訊都會呈現空白。無論輸入新增多少次，資料欄位還是空白的。

**Comment by sunhaolin** [comment]
在新版的審批新建好帳戶之後，新建的資料上傳完，到設置查看，e-mail 信箱會跑掉，在流程上除了公司名不會更動外，主管、部門等其他資訊都會呈現空白。無論輸入新增多少次，資料欄位還是空白的。不明白具体指的是什么；需要测试时多测试；

**Comment by chenzhipei** [comment]
新注册的用户在旧版中登录使用，邮箱是没有的
![2016-07-01 13 38 27](https://cloud.githubusercontent.com/assets/15027092/16512815/f33281d6-3f91-11e6-8926-eca9fbc2bdba.png)
