### ISSUE TITLE
邀请用户邮件内容为英文。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#244]
![2016-06-23 19 52 35](https://cloud.githubusercontent.com/assets/15027092/16302188/5b552d98-397c-11e6-9e4d-20083d118cc4.png)

**Comment by chenzhipei** [comment]
qq邮箱标题显示问题已报新bug

**Comment by wangdingrun** [comment]
中英文版本审批王的注册、邀请、修改密码等操作均已测试。在注册华炎云账号时，无需登录邮箱进行验证也可以直接登录华炎云。因此，邮箱验证的过程似乎并未起到效果，若注册时邮箱账号输入错误，该人员未发现，长期使用后，一旦忘记密码，则无对应的邮箱找回原有密码。该问题已报bug。
