### ISSUE TITLE
附件保存到阿里云

### ISSUE THREAD

**Issue by steedos** [steedos/apps#250]

**Comment by sunhaolin** [comment]
1、安装 osscmd到/usr/local/oss
2、将本地附件批量上传到oss 对应bucket下，如 workflow-attach-cn/sand/instances/，如果是内网服务器则host为oss-cn-beijing-internal.aliyuncs.com
3、修改包iyyang:cfs-aliyun的代码 使得文件格式类似instances-xxx-xxx.jpg
4、配置settings ，Meteor.settings.public.cfs.store   Meteor.settings.cfs.aliyun/aws
5、修改表cfs.instances.filerecord将copies.instances.key设置为新的路径

**Comment by steedos** [comment]
已确认
