### ISSUE TITLE
每日计算统计数据

### ISSUE THREAD

**Issue by steedos** [steedos/apps#251]
本任务请孙浩林指导陈志培开发。

新增表 steedos_statistics， 统计每个付费工作区的以下数据

- 工作区名称
- 所有者姓名
- 账户余额
- 用户总数，后续账单按参考这个数据
- 流程总数
- 表单总数
- 申请单总数
- 申请单附件总大小
- 网站总数
- 文章总数
- 评论总数
- 文章附件总大小

- 当日新增的申请单数
- 当日文章数
- 当日评论数

- 用户最近登录日期（最新一个）
- 申请单最近修改日期（最新一个）
- 文章最近修改日期 （最新一个）

**Comment by chenzhipei** [comment]
新增字段：

- 当日流程总数
- 当日表单总数
- 当日申请单总数
- 当日申请单附件总大小
- 当日网站总数
- 当日文章总数
- 当日评论总数
- 当日文章附件总大小

**Comment by chenzhipei** [comment]
申请单附件未统计

**Comment by chenzhipei** [comment]
需添加定时执行任务
