### ISSUE TITLE
申请单打印格式没有表格的线条

### ISSUE THREAD

**Issue by wangdingrun** [steedos/apps#262]
![bug](https://cloud.githubusercontent.com/assets/20121831/16374169/d8eaf1da-3c87-11e6-9ee2-ad6d5cd8b208.png)

**Comment by baozhoutao** [comment]
![default](https://cloud.githubusercontent.com/assets/6194462/16607185/18aa19c8-4371-11e6-9aa3-0b5f3d5b86b3.png)
![default](https://cloud.githubusercontent.com/assets/6194462/16607188/1d46a7e4-4371-11e6-8e3b-2ccaff2e2911.png)

添加表格线后，表单上线条太多，打印效果不佳。此任务不做处理
