### ISSUE TITLE
chrome对审批王新版测试：进行表单设计时，若加入的字段为表格，使用搜狗输入法输入会出现大量未输入文字，旧版本不会出现该情况。使用Safari对审批王新版本和旧版本进行测试，若使用搜狗输入法，在表单中加入表格，输入字段名，均有bug出现。

### ISSUE THREAD

**Issue by wangdingrun** [steedos/apps#265]
![default](https://cloud.githubusercontent.com/assets/20121831/16406605/d86243f6-3cd4-11e6-8c20-4fee01897894.png)
老版本与搜狗兼容

![1](https://cloud.githubusercontent.com/assets/20121831/16406801/ee37571a-3cd5-11e6-845e-2f567aa25156.png)

![2](https://cloud.githubusercontent.com/assets/20121831/16406773/bf117d3a-3cd5-11e6-940a-53b4e2d08980.png)

新版本在表单设计时，添加表格字段，若同样输入”chen'zhi'pei“，得到很多不需要的文字。

**Comment by steedos** [comment]
不一定是新老版本的问题。测试时用的浏览器不同。一个是Chrome ，一个是Safari

**Comment by wangdingrun** [comment]
20160630：使用safari对新老版本审批王都进行了测试，在加入表格后，使用搜狗输入法输入文字，都有bug出现。

具体情况如下图所示：
![sarafi](https://cloud.githubusercontent.com/assets/20121831/16474115/5f4c2f80-3ea6-11e6-98d4-5a9de2c46f57.png)
![safari](https://cloud.githubusercontent.com/assets/20121831/16474126/7371ba8e-3ea6-11e6-84fa-d7aca8de796f.png)

**Comment by steedos** [comment]
那应该改标题了

发自我的 iPhone
