### ISSUE TITLE
大众公用工作区--电脑端上签核历程中出现了错误的签核历程，但过段时间后无论从手机端还是电脑端看又恢复正常了。

### ISSUE THREAD

**Issue by irenehy** [steedos/apps#271]
正确的是：大众商务总经理审批，不正确的显示为：新路由 大众商务判断。具体见附件。
![bug](https://cloud.githubusercontent.com/assets/7665279/16437802/4f7a0aa2-3ddc-11e6-802f-4f4748cc8eb5.jpg)

**Comment by steedos** [comment]
待再次重现
