### ISSUE TITLE
Instance 按流程过滤界面，改为和新建申请单类似

### ISSUE THREAD

**Issue by steedos** [steedos/apps#274]

**Comment by chenzhipei** [comment]
监控箱中导出表单时，点击未分类，"所有流程"标题会消失
![2016-07-15 09 26 58](https://cloud.githubusercontent.com/assets/15027092/16860901/a5c23666-4a6e-11e6-9ea6-eb4b41cbdaeb.png)

再次点击未分类，未分类中的流程无法显示
