### ISSUE TITLE
选择部门和选择人员字段虽然可修改，但显示成只读的背景色

### ISSUE THREAD

**Issue by steedos** [steedos/apps#280]
- 控件只读时，增加一个 class 属性 readonly
- 编写CSS  
.selectUser
.selectUser.readonly
.selectOrg
.selectOrg.readonly

**Comment by baozhoutao** [comment]
处理方案：
 选人、选组字段可以编辑时， 文本框的背景色为白色；
 选人、选组字段不可编辑时，文本框的背景色与其它只读字段类型颜色一致。
