### ISSUE TITLE
新版审批王中根部门的名字可以修改，旧版中不可以修改。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#285]

**Comment by wangdingrun** [comment]
修改后进行测试，新版审批王的根部门名称无法修改，下级部门名称可以修改，与旧版一致。综上所述，实现了目标要求。

**Comment by chenzhipei** [comment]
工作区名字修改后会报错，此问题是由于工作区名字修改后，对根部门名字进行修改时校验，逻辑有矛盾，此问题已修改，请王定润重新测试。

**Comment by wangdingrun** [comment]
经测试，当工作区的名字发生变更时，根部门（一级部门）的名字也会随之改变。此外，拥有子部门的部门无法删除。
