### ISSUE TITLE
Android version 3.0.2 with GCM Push notifications

### ISSUE THREAD

**Issue by steedos** [steedos/apps#292]
需要搭建模拟器环境测试，必要的话指导陈志培专门搭一个虚拟机做Android测试

**Comment by baozhoutao** [comment]
关掉app进程可以收到
![](https://static.dingtalk.com/media/lALOWCsq_s0CX80BYA_352_607.png_620x10000q90.jpg)

app后天运行可以收到
![](https://static.dingtalk.com/media/lALOWCkq1c0C0M0BeA_376_720.png_620x10000q90.jpg)

**Comment by baozhoutao** [comment]
测试环境： 确保 服务端可以链接到google服务器。确保 app客户端可以链接到google服务器。
