### ISSUE TITLE
Android 客户端不能弹出显示享聊、云盘

### ISSUE THREAD

**Issue by steedos** [steedos/apps#293]
预计是执行 route /api/setup/sso/:app_id 之后，inAppBrowser 没有能正确执行跳转
建议使用 chrome://inspect 调试

**Comment by baozhoutao** [comment]
1 chrome://inspect 不能调试app弹出的页面；
2 此问题时由于app弹出的页面没有登录信息导致 sso接口调用失败。

**Comment by baozhoutao** [comment]
请在23服务器上进行测试确认， Android、IOS 客户端。
