### ISSUE TITLE
华炎云博客平台中，列表中显示的时间与实际发布的时间不一致

### ISSUE THREAD

**Issue by wangdingrun** [steedos/apps#300]
显示的时间如下：为几秒前
![default](https://cloud.githubusercontent.com/assets/20121831/16572384/9b9c7e3e-429a-11e6-92a3-4e9fa24cc347.png)

而实际的更改时间并不是几秒前
![default](https://cloud.githubusercontent.com/assets/20121831/16572393/b7b27966-429a-11e6-977f-03069b1c937a.png)

**Comment by steedos** [comment]
显示的是修改日期
