### ISSUE TITLE
点击推送消息自动进入申请单

### ISSUE THREAD

**Issue by steedos** [steedos/apps#322]
1、推送消息中包含 space 和 instance，都是Id
2、点击消息自动进入申请单

**Comment by baozhoutao** [comment]
通知情况分为以下情况：
1、提交到下一步 (收件箱)：通知下一步处理人
2、提交到结束 (已完成) ：通知提交者。
3、取消申请 (草稿箱)：通知申请人

**Comment by baozhoutao** [comment]
添加getInstanceSummary 函数 获取 申请单信息，用于判断文件箱

**Comment by baozhoutao** [comment]
现在支持：GCM、APNS 推送消息点击进入申请单。
不支持：aliyun推送点击。

**Comment by baozhoutao** [comment]
APNS 请在23服务器： http://steedos.ticp.net:8888/ 服务器测试。
GCM 需要安装 google play 上的审批王客户端。然后在23上进行测试。23服务器需要能链接到google服务器。

**Comment by liulian2016** [comment]
测试发现网页上点击推送消息可以直接打开申请单，但是iphone6点击推送，只是打开审批王，没有直接进入申请单。
