### ISSUE TITLE
在桌面客户端显示推送消息

### ISSUE THREAD

**Issue by steedos** [steedos/apps#323]
客户端订阅 手机推送消息表。只订阅最新的5条

检测收到新记录：
http://docs.meteor.com/api/collections.html#Mongo-Cursor-observeChanges

使用插件，弹出推送消息：
https://github.com/azproduction/jquery.notification

**Comment by baozhoutao** [comment]
消息弹出框6秒后自动关闭

**Comment by baozhoutao** [comment]
此功能不在手机版下生效。
