### ISSUE TITLE
审批王注册 |  注册时，无需登录邮箱验证，便可直接登录审批王。因此注册的邮箱真实性难有待考证！

### ISSUE THREAD

**Issue by wangdingrun** [steedos/apps#325]
![default](https://cloud.githubusercontent.com/assets/20121831/16789660/151b62d2-48e2-11e6-93ea-a8eb68468a00.png)

![default](https://cloud.githubusercontent.com/assets/20121831/16789671/2ac06362-48e2-11e6-8a88-28f2b7937d59.png)

**Comment by steedos** [comment]
会单独设计用户邮件绑定功能。
