### ISSUE TITLE
safari浏览中，当未处理的单子过多时，数字显示框会超出一部分

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#327]
![2016-07-13 11 58 47](https://cloud.githubusercontent.com/assets/15027092/16791488/fabb16f2-48f1-11e6-9c20-b3d7c5699e75.png)

**Comment by wangdingrun** [comment]
@chenzhipei 
# 经测试，在safari浏览器中，未处理子单数量过多时，也不会超出显示栏。
![2016-07-28 14 04 44](https://cloud.githubusercontent.com/assets/20121831/17202557/904f7ce0-54cc-11e6-9551-64fdd2e8c7f0.png)
