### ISSUE TITLE
点击编辑，对部门中某字段进行修改时，点击返回，显示的是设置界面，应该显示部门设置界面。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#337]
在该界面点击返回
![2016-07-15 11 06 21](https://cloud.githubusercontent.com/assets/15027092/16862840/ca00d3c8-4a7f-11e6-8d38-421a32afca2d.png)
返回到这个界面
![2016-07-15 11 06 39](https://cloud.githubusercontent.com/assets/15027092/16863061/b66a7b50-4a81-11e6-8b89-81d0d40fecb0.png)
应该返回到这个界面
![2016-07-15 11 47 44](https://cloud.githubusercontent.com/assets/15027092/16863095/0a584940-4a82-11e6-8ff8-6ac27f435c78.png)

**Comment by steedos** [comment]
此类问题有很多，不必重复报
