### ISSUE TITLE
工作区名字过长时，显示有问题。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#338]
![lalow-ypysyyzqvk_1354_178](https://cloud.githubusercontent.com/assets/15027092/16863495/d8c5d362-4a85-11e6-9adc-d5087b4d511a.png)

**Comment by baozhoutao** [comment]
问题2 ：工作区选择时， 选择列表与显示部分空隙太大。
![q d o 6iw 5kn x6r 8](https://cloud.githubusercontent.com/assets/6194462/16905524/b27d1868-4cd9-11e6-9be0-06de4da240ae.png)

**Comment by baozhoutao** [comment]
支持点击工作区与选择符号(V) 之间空白处选择工作区。
