### ISSUE TITLE
iPhone客户端切换工作区会弹出一个窗口。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#354]
![laloxsj-uc0ecm0cfw_639_1136](https://cloud.githubusercontent.com/assets/15027092/16982730/15dfcdb2-4ea4-11e6-9268-04add79eca4c.png)

**Comment by baozhoutao** [comment]
此问题是由于 switchSpace  下的 a标签href值为 # 导致。去掉a标签的href ，并设置获得焦点时的鼠标样式即可。

**Comment by baozhoutao** [comment]
可以通过手机app 链接 192.168.0.23服务器进行测试。
