### ISSUE TITLE
user emails set primary逻辑

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#366]
1、user表修改emails {address:xxx,verified:true,primary:true}，primary address最多只能有一个；
2、添加email address后 显示 unverified ,并显示 Verification email sent.  可以resend 邮箱校验邮件；
3、当address verified后 可以 set primary email；
4、管理员可以新增人员 但是 不可修改人员列表中的人员email（readOnly）。

**Comment by chenzhipei** [comment]
管理员现在无法看到人员的邮件地址
