### ISSUE TITLE
使用Node开发Office文档在线编辑

### ISSUE THREAD

**Issue by steedos** [steedos/apps#394]
检测当前运行在客户端环境下：
1、将文档（例如.docx文件）下载到本地
2、使用child_process，用对应的程序（例如Word）打开文档，当前页面全屏显示文档编辑中。
3、检测到文档关闭，检测文件变化(hash)，如果有变化，自动上传新版本。
4、搞定！

**Comment by hotkm** [comment]
windows: 
const exec = require('child_process').exec;
exec('start /wait php.docx', function(error, stdout, stderr) {
});

**Comment by hotkm** [comment]
hash
=======
`
var fs = require('fs');
var crypto = require('crypto');

// the file you want to get the hash    
var fd = fs.createReadStream('php.docx');
var hash = crypto.createHash('sha1');
hash.setEncoding('hex');

fd.on('end', function() {
    hash.end();
    console.log(hash.read()); // the desired sha1sum
});

// read all file and pipe it (write it) to the hash object
fd.pipe(hash);
`

**Comment by steedos** [comment]
https://blog.netnerds.net/2007/01/vbscript-download-and-save-a-binary-file/

在IE中通过 vbscript 保存一个文件，理论上IE中可以实现和Node客户端一样的效果。

**Comment by chenzhipei** [comment]
下载最新客户端测试如下情况（客户端分支为:node_office_edit_online；apps分支为:office_edit_online）：
1、测试不同系统下的附件编辑情况：目前只支持windows中编辑word文档，其他系统、类型文件默认下载
2、测试文件修改后是否会作为新版本添加
3、测试文件未修改是否会作为新版本上传
4、测试附件编辑后是否提示确认上传
5、测试文件编辑时能否关闭华炎云客户端
6、测试提示信息是否国际化
7、测试普通工作区编辑附件后，大小超过1M，能否上传

**Comment by chenzhipei** [comment]
office在线编辑需改进的问题:
1、附件下载时添加loading界面
2、附件上传提示信息：添加文件名
3、在线编辑提示：添加编辑文件的文件名、文件下载本地存放的路径
4、附件上传成功提示消息不需要点击确认
5、word类型文件右侧添加“在线编辑”选项

**Comment by chenzhipei** [comment]
目前项目在分支office_edit_online分支上，合并后，请在23上测试：
1、windows客户端中doc、docx类型文件可以进行在线编辑
2、点击在线编辑时，下载文件到本地指定路径，没有则创建：
>xp客户端：C:\Documents and Settings\用户\My Documents\Steedos
>win10客户端：C:\Users\用户\Documents\Steedos\

3、在线编辑时，客户端中不能进行其他操作，无法关闭客户端，有“在线编辑”提示信息

4、点击在线编辑时，判断本地是否有同名文件，有则提示是否覆盖。点击取消，打开本地已有的同名附件进行编辑；点击确认，则覆盖本地已有附件，并打开该附件进行编辑。

5、编辑时为修订模式，修改者为当前客户端登录用户。

6、点击关闭，自动对当前的修改进行保存，关闭后客户端后检测文件是否修改，有修改则提示是否上传。点击取消，不上传附件，并在本地保存已修改的文件；点击确认,上传后删除本地的附件。

7、免费工作区限制上传附件的大小，当用户修改文件后大于1M，系统提示，确认后自动打开该附件，让用户继续修改。
