### ISSUE TITLE
附件名中有%，上传附件就会有问题

### ISSUE THREAD

**Issue by liulian2016** [steedos/apps#398]
IE11中，上传%附件，显示上传成功，但是在附件列表中没有显示。后面继续上传其他附件，都无法上传。
chrome中，上传%附件，显示上传成功，附件列表中也显示，但是点击附件名下载出错，400 Bad Request

**Comment by chenzhipei** [comment]
修改url为id下载，请测试网页、手机客户端、桌面客户端附件下载情况

**Comment by steedos** [comment]
测试文件名：免责声明 %10(1）.docx
上传错误的文件名后，系统服务报错并重新启动

W20161219-13:51:39.011(8)? (STDERR) events.js:141
W20161219-13:51:39.015(8)? (STDERR)       throw er; // Unhandled 'error' event
W20161219-13:51:39.017(8)? (STDERR)       ^
W20161219-13:51:39.020(8)? (STDERR)
W20161219-13:51:39.020(8)? (STDERR) Error: Error storing file to the instances store: ENOENT: no such file or directory, open 'C:\Users\dell\Documents\GitHub\apps\.meteor\local\cfs\files\instances\instances-qHB2gqf346TBnCGrS-免责声明 (1）.doc'
W20161219-13:51:39.021(8)? (STDERR)     at [object Object].<anonymous> (packages/cfs_collection/common.js:88:1)
W20161219-13:51:39.023(8)? (STDERR)     at emitThree (events.js:97:13)
W20161219-13:51:39.024(8)? (STDERR)     at [object Object].emit (events.js:175:7)
W20161219-13:51:39.025(8)? (STDERR)     at WriteStream.<anonymous> (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:220:1)
W20161219-13:51:39.027(8)? (STDERR)     at emitOne (events.js:77:13)
W20161219-13:51:39.028(8)? (STDERR)     at WriteStream.emit (events.js:169:7)
W20161219-13:51:39.029(8)? (STDERR)     at WriteStream.<anonymous> (fs.js:1837:12)
W20161219-13:51:39.030(8)? (STDERR)     at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by steedos** [comment]
本需求可以简单的调整为附件名包含 % 号时自动替换为下划线。

**Comment by sunhaolin** [comment]
需要查看cfs源码，防止报错服务启动不了
