### ISSUE TITLE
流程中修改的字段值，保存后再打印，打印界面显示的不是最新的值

### ISSUE THREAD

**Issue by irenehy** [steedos/apps#406]

**Comment by steedos** [comment]
草稿箱和待审核，如果my_approve.values 有值，应该取my_approve.values

**Comment by sunhaolin** [comment]
此问题暂未修改，有以下疑虑：
需求：合同最后一步，会填合同编号，填好了，打印没有内容，必须要结束，在到已完成里找到，再打印，如果每天要弄20几个合同都这样，觉得麻烦；
疑虑：如果填错  打印了，又修改了，然后文件提交到结束了 这样打印出来的和申请单存的最终值就不一样了

**Comment by steedos** [comment]
虽然疑虑很好，但是看到的和打印出来的不一样，用户会很奇怪。

**Comment by steedos** [comment]
请包周涛在新开发的打印界面中修改
