### ISSUE TITLE
同一个流程文件，老版中看到的少了一个字段

### ISSUE THREAD

**Issue by irenehy** [steedos/apps#414]
大众公用-大众商务合同流程中有多个文件，在老版中看没有没有“签约对象”字段，在新版中有此字段
![default](https://cloud.githubusercontent.com/assets/7665279/18041900/900149da-6def-11e6-8838-ef8c2c33cbf6.jpg)
![default](https://cloud.githubusercontent.com/assets/7665279/18043328/c2eb3a18-6df9-11e6-9182-a51e6f6e692a.jpg)

**Comment by steedos** [comment]
不处理
