### ISSUE TITLE
桌面客户端ppt、excel文件在线编辑

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#418]
在线编辑请参考issues: #394 使用Node开发Office文档在线编辑

桌面客户端代码：steedos-desktop(分支：node_office_edit_online)

apps代码：apps(分支：office_edit_online)

**Comment by steedos** [comment]
https://cn.steedos.com/kanban/b/f4WoHRKwJh8FeeMds/app/zBAY69brXwkdveKPs
