### ISSUE TITLE
博客--文章下添加的附件，在系统的预览界面中按添加的次序正常显示，但发布界面中排序错乱

### ISSUE THREAD

**Issue by irenehy** [steedos/apps#424]
![default](https://cloud.githubusercontent.com/assets/7665279/18429652/3144c3f4-7907-11e6-8ff4-807e23e89eac.jpg)
![default](https://cloud.githubusercontent.com/assets/7665279/18429655/3654a382-7907-11e6-986f-7396e71c4c3d.jpg)

**Comment by yinlianghui** [comment]
已实现，规则如下：
- [x] 统一按倒序排序。
- [x] 附件列表显示及打开规则与审批王一样，见https://github.com/steedos/apps/issues/647

android app上有点击附件下载功能，这个要打包测试，我没有测试。
我测试过iphone6s/chrome/firefox/ie11/edge

**Comment by chenzhipei** [comment]
安卓手机已测试：是倒叙显示，下载后可以打开
