### ISSUE TITLE
桌面客户端无法显示流程设计器

### ISSUE THREAD

**Issue by steedos** [steedos/apps#428]
原因是流程设计器与 nodejs 冲突。而桌面客户端对于 *.steedos.com 的域名自动加载了 nodejs

有一个改进的方案是把流程设计器显示在一个全屏的 iframe 中。并且给iframe 加上禁用 nodejs的属性。具体说明如下：
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/#node-and-normal-frames

可以写一个静态的html文件，使用 addAssets加入到package中，内容类似这样
<iframe src="/applications/designer/current/zh-cn/index.html" width="500" height="500" nwdisable="true"></iframe>
，点击流程设计器时，跳转到这个静态的html文件，通过这个文件中转一下显示流程设计器。

**Comment by yinlianghui** [comment]
已完成，增加了一个新的界面"/packages/steedos_admin/client/designer/index.html?locale={{locale}}&space={{spaceId}}"
现在可以打开流程设计器了。

**Comment by yinlianghui** [comment]
路径变更为"/packages/steedos_admin/assets/designer/index.html?locale={{locale}}&space={{spaceId}}"

今天测试了下chrome/firefox/ie11/edge都可以正常打开流程设计器了。
