### ISSUE TITLE
在线编辑时，需给文件增加lock 属性，防止多人同时编辑

### ISSUE THREAD

**Issue by steedos** [steedos/apps#429]

**Comment by sunhaolin** [comment]
- 使用cfs.instances代替instance.attachments字段
- 上传附件时cfs.instances 需要存owner, space, instance, approve,  current, history，/s3接口修改
- 附件编辑时更新cfs.instances的lock属性
- 表单使用cfs.instances显示instance_id相关附件
- 现有数据升级：遍历instances表将attachments相关信息存进cfs.instances（owner, space, instance, approve,  current, history）
- instance.attachments 字段暂时保留
