### ISSUE TITLE
审批王自定义脚本事件触发机制的设计

### ISSUE THREAD

**Issue by steedos** [steedos/apps#440]
在设置流程时，可配置流程脚本。

可以在脚本中编写代码，等待具体事件触发才执行。

```
$(".instance-form").on('instance-before-submit', function(e, opts) {
   //编写具体业务逻辑
   if (xxx)
       e.preventDefault(); 
});
```

在审批王中点击提交按钮

```
var event = jQuery.Event( "instance-before-submit", {instance: {}} );
$(".instance-form").trigger(event);
if (event.isDefaultPrevented())
{
    //中断执行
}   
```

在审批王中显示申请单时

```
// 以下代码可以清理事件触发器，但是没有必要，因为切换申请单时，审批王会重新生成 $(".instance-form")
// $(".instance-form").off('instance-before-submit');
```

**Comment by baozhoutao** [comment]
脚本示例(附件大小判断)：
$(".instance-form").on('instance-before-submit', function(e) {
	console.log(e.instance);
	
	var approve = workflowAPI.getCurrentApprove();
	
	var attachments = workflowAPI.getInstanceAttachments(approve.instance,approve.id);
	
	attachments.getProperty("original").forEach(function(attachment){
		if(attachment.size > (1024*1024) * 1){
			toastr.warning("附件:" + attachment.name + ",大小超过1M限制,请重新上传附件");
			e.preventDefault(); 
		}
	})
});
