### ISSUE TITLE
字段权限显示的BUG

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#444]
同一个文件，在不同文件箱显示效果不一致问题

**Comment by baozhoutao** [comment]
此问题原因：当前用户对审批单字段有编辑权限，但是不在“待办”中打开时，出现字段view的只读是通过form的readonly来控制导致显示不一致问题。
处理方式：在生成字段权限时，判断 instance IsreadOnly == true ，则设置所有字段权限都为readonly，不再依赖form的readonly。
