### ISSUE TITLE
［秦港］主送 是个特殊的字段

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#449]
为select和input的组合，可以先选select，选中的即出现在input中，input还可以继续修改。
提交的实际值 为 input

**Comment by steedos** [comment]
在表单中配置模板实现

**Comment by marchtian** [comment]
<select id="zhusongselect" name="zhusongselect" onchange="document.getElementsByName('主送')[0].value = this.options[this.selectedIndex].value ; this.selectedIndex = 0;" class="form-control">
              <option value=""></option>
              <option value="各单位、各部室">政务发文</option>
              <option value="各基层党组织、各部室">党务发文</option>
              <option value="各基层党组织，各单位、各部室">党委、行政联合发文</option>
          </select>
          <script type="text/javascript">
              if (document.getElementsByName('主送')[0].disabled || (document.getElementsByName('主送')[0].tagName == 'DIV')) {
                document.getElementById('zhusongselect').style.display = "none";
              } 
          </script>
