### ISSUE TITLE
［秦港］分发

### ISSUE THREAD

**Issue by marchtian** [steedos/apps#450]
1 设置
1.1 流程设计，节点上增加“分发”按钮的开关
1.2 流程设计，分发的细节设计：分发流程（要么就不限制，要么限制可选的流程范围，涉及跨space，要求相同的名字）、分发范围（即用户清单）

2 流程处理-分发文件
2.1 某些节点 才出现 “分发”按钮
2.2 点“分发”，出现多选用户的界面
2.3 点“确定”，即 给这些用户传 分发文件（类似“传阅”）
2.4 能随时在签核历程里看到 分发进展

3 流程处理－触发新流程
3.1 看到有新分发的文件
3.2  接受分发 ，（1）选择触发哪个子流程（要么完全自主选择，要么在设置中限定的我所在space可发起的对应流程中选择），（2）父文件的字段值传入（字段名相同），（3）父文件的附件（包括正文）传入（最新版）

**Comment by steedos** [comment]
使用流程转发替代
