### ISSUE TITLE
当窗口宽度变化时，设置界面混乱

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#462]
![default](https://cloud.githubusercontent.com/assets/15027092/19259982/b5359fc2-8fb8-11e6-8fcd-0e9e59780799.PNG)

![default](https://cloud.githubusercontent.com/assets/15027092/19260115/c1f1458a-8fb9-11e6-9afb-8b73a73cd6a3.PNG)

**Comment by yinlianghui** [comment]
.dataTables_wrapper {
  .box-body {
    overflow-x:auto;
    table.dataTable{
      min-width:800px;
    }
  }
}

new Tabular.Table时设置autoWidth为 false即可。
