### ISSUE TITLE
博客-市北燃气党建网首页各栏目中需要显示二级栏目中的最新文档等问题

### ISSUE THREAD

**Issue by irenehy** [steedos/apps#463]
1.首页各栏目中需要显示二级栏目中最新文档，目前只显示一级栏目中的文档
2.每篇文档的下方需要增加点击数
3.从Excel中复制的表格没有表格线，见附件
4.摘要需为不必填，正文为必填
![excel](https://cloud.githubusercontent.com/assets/7665279/19261592/d8426318-8fc4-11e6-860d-24852a7b6f9b.jpg)

**Comment by baozhoutao** [comment]
已将任务新建到CMS下：https://github.com/steedos/steedos-cms/issues
