### ISSUE TITLE
CMS - 市北党建网

### ISSUE THREAD

**Issue by steedos** [steedos/apps#464]
a.首页各栏目中需要显示二级栏目中最新文档，目前只显示一级栏目中的文档
b.每篇文档的下方需要增加点击数

**Comment by baozhoutao** [comment]
问题a: 二级文档问题时由于网站模板未修改，已重新调整了模板；无需修改代码。
问题b: 此问题在cms项目下：https://github.com/steedos/steedos-cms/issues/3
