### ISSUE TITLE
申请单转发

### ISSUE THREAD

**Issue by steedos** [steedos/apps#465]
需求：
- 收文转发文
- 出差申请转出差报销

开发：
- [x] 在申请单操作按钮中增加“转发”。
- [x] 能看到申请单的人都可以点击此按钮，即使申请单已结束。
- [x] 点击转发弹出窗口，描述此功能的说明。最下面出一个流程选择框，让用户选择需要转发的流程。可以选择其他工作区的流程。
- [x] 在草稿箱中用选中的流程创建草稿
    - [x] 将原申请单的附件的最新版本复制到新申请单。
           - [x] 根据字段code和type相同给新字段赋值
    - [x] 循环原申请单中的字段，如果新申请单中有同名字段，自动复制到新申请单。（此需求暂不考虑子表）
    - [x] 显示新申请单，用户可以继续修改并提交。

下一步：
- [ ] 新增相关申请单类型字段
- [ ] 如果新表单中有相关申请单字段，则自动设置为原申请单
- [ ] 相关申请单字段有修改权限时，用户可以从自己有权限访问的申请单中查询并选中申请单。
- [ ] 只读状态时，用户点击此字段，弹出窗口显示此申请单信息。（在弹出窗口中要判断权限）

**Comment by sunhaolin** [comment]
- **开发** 部分已开发完成；
- **下一步** 还未开发；
