### ISSUE TITLE
ie、火狐、edge浏览器中访问steedos，点击应用，部分边框会缺失

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#486]
ie、edge浏览器
![ie11](https://cloud.githubusercontent.com/assets/15027092/19425469/6fb71c3a-9465-11e6-93c6-dadd871cbd0d.PNG)

火狐浏览器
![default](https://cloud.githubusercontent.com/assets/15027092/19425477/7dd87f70-9465-11e6-913e-a3c281c29791.PNG)

**Comment by yinlianghui** [comment]
已解决ie11/edge上的bug，firefox因为不支持after及before的css伪类，所以没有找到办法，估计要解决的话，就不能用css伪类去显示边框线，而换成传统方案。
