### ISSUE TITLE
部分苹果手机搜索功能异常，如搜索请假申请，没有文件显示，搜索请假申，有文件

### ISSUE THREAD

**Issue by irenehy** [steedos/apps#517]
刘恋和包周涛手机搜索不行，田骐手机搜索正常

![default](https://cloud.githubusercontent.com/assets/7665279/19843305/e1b141ac-9f5b-11e6-9c08-a1e80ec0b6d8.JPG)

**Comment by steedos** [comment]
估计是操作系统本身的问题，暂不处理
