### ISSUE TITLE
审批王操作界面增加对应的帮助链接

### ISSUE THREAD

**Issue by steedos** [steedos/apps#529]
1、因为界面调整，一些帮助要对照修改。
2、Steedos 比较难搞懂的界面上，要加上跳转到帮助的链接。

**Comment by liulian2016** [comment]
1、附件
中文
https://www.steedos.com/cn/help/workflow/instance_attachment.html
英文
https://www.steedos.com/us/help/workflow/instance_attachment.html

2、	取消申请
中文
https://www.steedos.com/cn/help/workflow/instance_cancel.html
英文
https://www.steedos.com/us/help/workflow/instance_cancel.html

3、	传阅
4、	复制
5、	转签核
中文
https://www.steedos.com/cn/help/workflow/instance_reassign.html
英文
https://www.steedos.com/us/help/workflow/instance_reassign.html

6、	重定位
中文
https://www.steedos.com/cn/help/workflow/instance_relocate.html
英文
https://www.steedos.com/us/help/workflow/instance_relocate.html

7、	导出表单
中文
https://www.steedos.com/cn/help/workflow/instance_export.html
英文
https://www.steedos.com/us/help/workflow/instance_export.html

**Comment by zhangshanshan2016** [comment]
添加帮助链接页面：传阅、转签核、重定位、文件转发、过滤查询申请单、新建申请单、邀请用户。（中文页面均有）

**Comment by zhemingloveme** [comment]
经测试：客户端，浏览器端，在传阅、转签核、重定位、文件转发、新建申请单、邀请用户页面中，都有按钮可以跳转到帮助文档。中文英文都可以跳转
