### ISSUE TITLE
Mongodb 数据库 排序

### ISSUE THREAD

**Issue by steedos** [steedos/apps#531]
https://jira.mongodb.org/browse/SERVER-1920

先在公司做测试。

**Comment by sunhaolin** [comment]
db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )
db.createCollection('space_users_new',{collation:{locale:'zh'}})
db.space_users.copyTo('space_users_new')
db.space_users.renameCollection('space_users_old',true)
db.space_users_new .renameCollection('space_users',false)
db.space_users_old.drop()
测试确认后最后执行 db.space_users_new.drop()
给新的space_users增加索引:
db.space_users.createIndex({user: 1}, {background: 1});
db.space_users.createIndex({user_accepted: 1}, {background: 1});
db.space_users.createIndex({space: 1}, {background: 1});
db.space_users.createIndex({is_deleted: 1}, {background: 1});
db.space_users.createIndex({user: 1, user_accepted: 1}, {background: 1});
db.space_users.createIndex({user: 1, space :1}, {background: 1});
db.space_users.createIndex({space: 1, user_accepted: 1}, {background: 1});
db.space_users.createIndex({space: 1, user: 1, user_accepted: 1}, {background: 1});
db.space_users.createIndex({space: 1, manager: 1}, {background: 1});
db.space_users.createIndex({manager: 1}, {background: 1});
db.space_users.createIndex({space: 1, created: 1}, {background: 1});
db.space_users.createIndex({space: 1, created: 1, modified: 1}, {background: 1});
