### ISSUE TITLE
点击打开steedos 应用后， 然后关闭该应用窗口，再选中其他工作区 ，页面显示404 page not found

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#534]

**Comment by yinlianghui** [comment]
已解决，处理方法是删除路由'/app/:app_id'及'/app/:app_id/opened'，新增全局函数Steedos.openApp打开应用。
并且把所有调用上述路由的地方全部换成调用全局函数Steedos.openApp了。

**Comment by yinlianghui** [comment]
测试要点：

- 除了点击左上角弹出应用选择框中打开应用要测试外，路由/steedos/springboard中也可以打开应用，因为目前还是有些情况下会进入到这个路由，所以我也改过了，也要测试。
- 虽然换成调用全局函数Steedos.openApp的地方不多，我也都测试过了，测试时能想到可能需要打开app的地方都测试了吧。
