### ISSUE TITLE
使用 swipebox 预览申请单的图片类型附件

### ISSUE THREAD

**Issue by steedos** [steedos/apps#535]
具体可参考 cms

https://github.com/brutaldesign/swipebox

**Comment by yinlianghui** [comment]
![image](https://cloud.githubusercontent.com/assets/6219465/21300429/d9287a1a-c5de-11e6-999a-37b70883c2d0.png)

在“版本”后面增加了“预览”链接。

**Comment by yinlianghui** [comment]
测试时请注意测试手机APP，原来的功能没有改过，但是最好一起测试下。
