### ISSUE TITLE
审批王的工具栏图标按钮都加上Bootstrap Tooltip

### ISSUE THREAD

**Issue by steedos** [steedos/apps#544]
http://getbootstrap.com/javascript/#tooltips

需要处理邮件，审批王，知识库三个模块

可以试试这个包 https://github.com/lookback/meteor-tooltips

**Comment by zhangshanshan2016** [comment]
当切换space时，新打开的home页面，由于home页面的view层不再执行，其上的button不能加上Tooltip。
