### ISSUE TITLE
按流程分类显示待审核

### ISSUE THREAD

**Issue by steedos** [steedos/apps#547]
- 待审核列表页上面的下拉菜单，改为下拉选择流程
- 每个流程后面显示待审核的数量
- 只列出有待审核的流程
- 所有工作区的待审核最多取 100 条，以便在前台计算按流程分类的功能。

- 其他箱的下拉菜单可以考虑改成目前选流程的菜单

**Comment by baozhoutao** [comment]
调整后显示规则如下：

- 默认订阅最新的100条待办文件(含传阅)

- 只有在待办文件数量大于0 并且 当前是在Inbox 列表 才显示workflow_menu。

**Comment by steedos** [comment]
选中申请单后，过滤条件失效。
类似问题 https://github.com/steedos/apps/issues/526

**Comment by chenzhipei** [comment]
下拉过滤某流程后，选中某流程，过滤条件还是会失效
