### ISSUE TITLE
流程并发

### ISSUE THREAD

**Issue by steedos** [steedos/apps#548]
可以同时发给多个下一步骤去处理

**Comment by marchtian** [comment]
![2016-11-10 9 39 12](https://cloud.githubusercontent.com/assets/7553007/20178860/19f61742-a78e-11e6-9a64-c16878ed2594.png)

**Comment by marchtian** [comment]
附属规则：
（1）对应步骤有open状态的trace时，不生成新的trace
（2）存在open状态的trace时，不允许结束（即下一步为结束，点击“发送”后，弹出对框框，提示还有人正在处理）

**Comment by steedos** [comment]
暂停
