### ISSUE TITLE
iphone客户端审批表单，当输入文本或有消息弹出框时，表中部分文本字段中的数字会显示成链接形式

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#55]
![2016-02-26 15 27 43](https://cloud.githubusercontent.com/assets/15027092/13346293/29531a14-dca0-11e5-8cb8-936174ee00a2.png)

**Comment by chenzhipei** [comment]
**1、审批表但中的内容**
**2、签核历程中的意见栏**
![iphone_workflow1](https://cloud.githubusercontent.com/assets/15027092/13347471/e83a1c90-dca8-11e5-8bb1-27113439422d.png)
**3、审批表单的标题**
![iphone_workflow2](https://cloud.githubusercontent.com/assets/15027092/13347482/fe1bdfd0-dca8-11e5-895a-33896be3533d.png)

**Comment by steedos** [comment]
老版本问题关闭
