### ISSUE TITLE
工作区余额不足自动提醒

### ISSUE THREAD

**Issue by steedos** [steedos/apps#564]
- 提前三个月，在管理员主界面上提示。
- 提前一个月，在所有用户主界面上提示。
- 显示效果为登录后右上角浮出提示。

**Comment by yinlianghui** [comment]
前端这块加好了空函数，后续孙后台space相关字段准备好后，再补上相关逻辑 就可以了。

**Comment by yinlianghui** [comment]
已完成。

**Comment by yinlianghui** [comment]
已完成。
