### ISSUE TITLE
在服务端生成表单Html

### ISSUE THREAD

**Issue by steedos** [steedos/apps#567]
对于只读表单的显示，最好相关代码能做到前后台统一一套。

**Comment by baozhoutao** [comment]
开发已完成

**Comment by baozhoutao** [comment]
[测试-服务端生成instance readOnly view.xlsx](https://github.com/steedos/apps/files/643533/-.instance.readOnly.view.xlsx)

**Comment by baozhoutao** [comment]
代码已合并到master 分支，测试中

**Comment by steedos** [comment]
测试可以使用转发功能： 申请单转发时，增加选项，可把原表单作为第一个附件 #560
