### ISSUE TITLE
忘记密码:允许用户手工输入邮件中收到的验证码

### ISSUE THREAD

**Issue by steedos** [steedos/apps#577]
- 用户点击忘记密码并提交后，在邮件中显示 Meteor 生成的token验证码。
- 界面停留在验证码输入页面，用户可以从邮件中复制验证码并输入。
- 输入完成之后校验验证码是否正确，如果正确则跳转到密码修改页面。

可能需要定制这个包 https://github.com/meteor-useraccounts/flow-routing

**Comment by yinlianghui** [comment]
已解决，剩余一个需要优化的问题，我另外建了issue:https://github.com/steedos/apps/issues/626
