### ISSUE TITLE
组织机构新增部门，点击“创建”后，弹出窗口没有消失，但部门已经创建成功

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#579]

**Comment by yinlianghui** [comment]
已解决，modal本身就不支持多层关闭功能，统一实现比较复杂，这时只把所有AdminDashboard.modalNew及AdminDashboard.modalEdit弹出层方面的问题解决了。
即只要是从AdminDashboard中弹出层中再弹出一层的需求，都不会再有问题。
