### ISSUE TITLE
邮件敏感字过滤 及跨域名提醒

### ISSUE THREAD

**Issue by steedos** [steedos/apps#587]
在 mail_domains 中，新增字段 
  - sensitive_keywords_alert = 多行文本框用于填写关键词列表，一行一个
  - sensitive_keywords_forbidden = 多行文本框用于填写关键词列表，一行一个
  - before_send = 用户可以编写函数，在发送邮件时执行

- 邮件发送时，如果检测到 before_send，则执行，如果throw error，则弹出报错信息，停止发送邮件。

befor_send
- 验证收件人的域名是否合法。
- 验证:  邮件标题、正文、附件名称是否包含相关的关键词。
- 根据敏感字保密级别(一般、机密) 如果是一般，则进行提醒，用户可点击确认后继续发送。如果是机密则停止发送并提示用户。

**Comment by steedos** [comment]
原始需求： 22.	邮件关键字过滤：邮件标题、正文、附件名称。关键字库提供维护接口，维护权限为管理员。在发送时统一验证: 根据关键字保密级别(一般、机密) 如果是一般，则进行提醒，用户可点击确认后继续发送。如果是机密则停止发送并提示用户。添加开关：根据设置来控制是否可以给中石油以外的域名发送邮件。(关于在邮件服务器上设置关键字过滤的方案，陈志明是说，他们没有邮件服务器的权限)
23.	如果收件人、抄送人、密送是中石油域名(@petrochina.com.cn、@cnpc.com.cn)以外的邮箱，在发送时，需要添加提示

**Comment by zhangshanshan2016** [comment]
[抚顺石化发件校验脚本 .txt](https://github.com/steedos/apps/files/623930/default.txt)

**Comment by zhangshanshan2016** [comment]
[抚顺石化发件校验脚本.txt](https://github.com/steedos/apps/files/626245/default.txt)

**Comment by steedos** [comment]
请 @chenzhipei 测试

**Comment by steedos** [comment]
验证失败后，仍然显示 loading 状态，无法修改。

**Comment by chenzhipei** [comment]
测试后，警告关键字和邮件跨域名提醒后，点击“取消发送”，会一直显示loading的状态

**Comment by chenzhipei** [comment]
修改后，测试确认通过
