### ISSUE TITLE
系统关闭时记录最近打开的URL，下次登录后自动进入对应的URL

### ISSUE THREAD

**Issue by steedos** [steedos/apps#588]
URL 保存在 localStorage 中，
localStorage.setItem("Steedos.lastURL")

**Comment by chenzhipei** [comment]
请测试关闭当前窗口、关闭整个浏览器和直接退出客户端这几种情况下的效果

**Comment by steedos** [comment]
现有代码
			lastUrl = localStorage.getItem('Steedos.lastURL:' + Meteor.userId())
			if lastUrl
				FlowRouter.go lastUrl

改为检测 lastUrl
如果 以 /workflow 开头，则跳转到 /workflow
如果 以 /cms 开头，则跳转到 /cms
如果 以 /emailjs开头，则跳转到 /emailjs

**Comment by yinlianghui** [comment]
已解决，增加了contacts/portal/admin，没有加的有chat/云盘/日历。
我测试了chrome/firefox/edge/ie11/steedos客户端。
并且排除了/workflow等后面紧根其他字符的情况，比如/workflowabc,/cmsdef
