### ISSUE TITLE
组织机构分级管理

### ISSUE THREAD

**Issue by steedos** [steedos/apps#592]
组织机构通讯录管理员需要分级管理，直属单位管理自己的组织机构通讯录，并且可以创建本单位的办公群组（管理员通过组织机构通讯录来选择人员添加到办公群组中）

**Comment by steedos** [comment]
- organizations 新增 admins 字段, space admins 可以修改此字段
- organization admins 可以维护组织下的成员，也可以维护下级组织
- 点击组织结构图时，调用服务端方法判断是否可以管理当前节点。如果可以，则显示增删改按钮。
- 对组织进行增删改时，需要判断是否有权限。
- 对space_users进行增删改时，也需要判断是否有权限。比如编辑用户时，用户所属部门不能超出 space admins 可管理的组织范围。

**Comment by yinlianghui** [comment]
暂时只考虑一层分级管理，即：
1、organization admins  编辑组织的时候，隐藏 admins 字段，不让其查看编辑
2、只有space admins 可以修改organization admins字段，且所有组织的organization admins都只由space admin维护。

**Comment by yinlianghui** [comment]
组织权限相关功能要点：
前端---------------
- [ ] 只有space admin可以在添加/编辑组织窗口看到“组织管理员”属性，否则这个属性就是隐藏的。
- [ ] 选中组织结构图中某个组织后，如果当前用户是space admin就一定会显示右上角的增删改按钮，可以做相应操作，且可以看到和修改“组织管理员”属性。
- [ ] 选中组织结构图中某个组织后，如果当前用户不是space admin，但是是该组织或者其父组织的“组织管理员”属性中一员，则显示右上角的增删改按钮，可以做相应操作，且无法看到“组织管理员”属性。
后端---------------
- [ ] 对组织进行增删改时，如果当前用户没有权限（上述前端描述的规则），则弹出相应错误提示。
- [ ] 对组织进行增加、修改操作时，如果当前用户有权限，但不是space admin，如果修改了“组织管理员”属性（没有权限修改），则保存时弹出相应错误提示。

测试要点----------

- 前端好测试，只要准备两个浏览器，分别用两个账户登录，一个是space admin，一个非space admin，space admin账户变更非space admin账户的的organization admins权限，对照上述功能点就能测试出来。
- 后端测试会比较麻烦，可以分两段，一段是测试有权限修改的情况，只要能正常修改就行（包括“组织管理员”属性的修改）；另一段是测试没有权限修改的情况，这会比较麻烦，可以在同一个浏览器上开两个tab，先登录sapce admin，并准备另一个非sapce admin账户，找准一个非sapce admin账户没有权限操作的组织，并点击添加或修改组织按钮弹出编辑窗口，然后在另一个tab上注销登录并用非sapce admin账户登录，然后回到第一个tab中，在弹出编辑窗口点击保存，如果有相应错误提示则说明测试通过，反之则测试不通过。

**Comment by yinlianghui** [comment]
space_users权限相关功能要点（权限规则与组织权限一样）：
前端---------------
- [x] 选中组织结构图中某个组织后，如果当前用户是space admin，右侧左上角一定会显示“邀请用户”按钮，在用户列表也一定可以看到编辑和删除按钮，且可以做相应操作。
- [x]  选中组织结构图中某个组织后，如果当前用户不是space admin，但是是该组织或者其父组织的“组织管理员”属性中一员，则显示右侧左上角“邀请用户”按钮，在用户列表也一定可以看到编辑和删除按钮，且可以做相应操作。
- [x] 选中组织结构图中某个组织后，如果不是上述两种情况，则右侧左上角“邀请用户”按钮不显示，用户列表也一定不可以看到编辑和删除按钮。

**Comment by yinlianghui** [comment]
拖动变更用户所属组织时权限相关功能要点（权限规则是上述两种权限中后端逻辑的结合）：
前端---------------
无
后端---------------
- [x] 判断当前登录用户对要拖动到组织是否有编辑权限（参考上面的“组织权限相关功能要点”）
- [x] 判断当前登录用户对正在拖动转移的用户是否有编辑权限（参考上面的“space_users权限相关功能要点”）
测试要点----------
- 判断当前登录用户对要拖动到组织是否有编辑权限，这个比较容易测试，找一个当前用户的权限的组织，及一个没有权限的组织，然后从有权限组织那块拖动一个用户到没有权限组织上，会有相应的错误提示就对了，反之拖动到另一个有权限的组织上，则能成功转移并且没有错误提示（不过目前因为另一个bug的存在，有一定的机会碰到其他来自后台转移用户过程中的错误提示）就测试通过。
- 判断当前登录用户对正在拖动转移的用户是否有编辑权限，这个比较麻烦了，因为没有权限的话，是没办法编辑和拖动用户的，所以只能像上面“组织权限测试要点”后端测试描述的那样，在同一个浏览器上开两个tab来测试。

**Comment by yinlianghui** [comment]
今天我测试的时候发现，上面写的测试要点中关于比较麻烦的开两个tab切换账户的方式来保留有权限的编辑界面并测试是否提交到后台会有相应报错的方式已经行不通了，因为有权限的编辑界面会同步其有权限的字段了，而不是保留在原来的状态。

**Comment by yinlianghui** [comment]
我重新测试过后，没有重现bug。
部分需要开两个tab切换账户来测试的后台功能因切换用户后现在会同步界面，所以无法测试，但是之前测试过没有问题。

**Comment by yinlianghui** [comment]
space_users处需求变更：
- [x] 添加用户时，需要有用户所属组织全部权限，而不是只要其中一个组织有权限。
- [x] 修改用户时，需要有用户原所属组织全部权限，且需要有变更后的所属组织全部权限，而不是只要其中一个组织有权限。
- [x] 删除用户时，需要有用户所属组织全部权限，而不是只要其中一个组织有权限。
- [x] 拖动迁移用户所属组织时，需要有用户所属组织全部权限，而不是只要其中一个组织有权限。之前拖动目标组织权限判断不变，但是代码优化过了，所以也要一起重新测试。
