### ISSUE TITLE
组织机构操作日志

### ISSUE THREAD

**Issue by steedos** [steedos/apps#594]
组织机构通讯录管理员要有操作日志，记录管理员工作内容，时间，IP地址 type:enhancement

**Comment by steedos** [comment]
表 audit_log， 中纪录以下内容

c_name, c_action, object_id, object_name, value_from, value_to, created_by, created_by_name, created  
表名称，表操作，对象id, 对象name，原json，新json, 操作人id，操作人名称，日期 
organizations, add, 111, 测试组织, null，新json，101, 某管理员, 日期

**Comment by steedos** [comment]
.after.insert(userId, doc)
- value = doc

.after.update(userId, doc, fieldNames, modifier, options)
- value_previous = this.previous
- value = doc

.after.remove(userId, doc)
- value = doc

**Comment by chenzhipei** [comment]
更新问题：
1、更新组织机构名字后，fullname内有改变
2、没有修改操作，点击更新后，audit_logs表中依旧会添加纪录

**Comment by chenzhipei** [comment]
点击更新后，虽然没有修改字段，但是organizations中的modified_by和modified字段也会更新

**Comment by chenzhipei** [comment]
1、组织机构人员拖动后，会造成人员部门字段丢失的问题
2、组合机构父子部门之间人员拖动会报内部错误
3、updateusers方法为direct.update，跳过了部门中的一些验证，建议修改direct.update为update，再修改相关权限问题
