### ISSUE TITLE
点击进入监控箱，清除浏览器缓存后，再次回到监控箱，监控箱中会订阅所有工作区的流程，但是无法操作

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#597]
清除浏览器缓存前：
![default](https://cloud.githubusercontent.com/assets/15027092/20655297/54d15ef4-b55c-11e6-9faa-b4d4a3c26e00.png)

清除浏览器缓存后：
![default](https://cloud.githubusercontent.com/assets/15027092/20655307/64ba547e-b55c-11e6-9c3f-a01f44af3ee1.png)

**Comment by yinlianghui** [comment]
这个问题其实是登录信息失效后（即要在清除缓存时选中清除cookie，或用另一个浏览器tab登出系统）出现 的BUG。
造成问题现象的原因是登出系统后，TabularTables.instances的selector函数中报错了。
已解决，规则及测试要点：

- [x] 后台增加安全筛选逻辑判断，即增加调用了全局函数Admin.selectorCheckSpace ，这样就算前台报错，后台也可以拦截请求，从根本上解决信息安全问题。
- [x] 前台增加了用户信息丢失时的逻辑判断，现在不会出现前台浏览器控制台报错问题了。
- [x] 顺手优化了下之前的Admin.selectorCheckSpaceAdmin 函数，所以需要测试调用到该函数相应的功能，比如系统设置中相关TabularTables列表功能是否正常。
- [ ] 需要在其他所有TabularTables中增加全局函数Admin.selectorCheckSpace，作为数据安全屏障。

**Comment by yinlianghui** [comment]
理想情况是用户登录信息丢失后，应该自动跳转到登录界面，见：https://github.com/steedos/apps/issues/669

**Comment by yinlianghui** [comment]
最后一项任务为所有TabularTables中增加changeSelector函数，清单如下：
1. CMS文章列表，数据范围限制在指定site中，且当前登录用户要求属于site所属space中。
2. Contacts的个人联系人用户列表中，数据范围限制在指定owner中，且当前用户ID要等于owner。
3. Contacts/Setting等APP的组织架构用户列表中，数据范围限制在指定space中，且当前登录用户要求属于该space。
4. 邮件APP中的个人联系人用户列表中，数据范围限制在指定owner中，且当前用户ID要等于owner。
5. 邮件APP中的组织架构用户列表中，数据范围限制在指定space中，且当前登录用户要求属于该space。
6. 审批王APP中的选人控件中，数据范围限制在指定space中，且当前登录用户要求属于该space。
7. 审批王APP中的instance列表，数据范围限制在指定space中，且当前登录用户要求属于该space。
