### ISSUE TITLE
将steedos-server的引擎逻辑迁移到apps的steedos-workflow中

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#601]
测试点
- 测试对象是待审核中的申请单
- 需要测试所有的步骤类型：
  - 填写
  - 审批
  - 条件节点
- 需要测试所有的处理人类型：
  - 审批时指定人员
  - 指定人员
  - 指定审批岗位
  - 申请人的上级
  - 申请人
  - 指定人员字段
  - 指定部门字段
  - 指定部门
  - 指定人员字段相关审批岗位
  - 指定部门字段相关审批岗位
- 需要测试表单公式
- 需要测试推送消息和提醒邮件

**Comment by baozhoutao** [comment]
需要在settings.json 文件中添加配置：
"email": {
    "from": "Steedos <noreply@steedos.com>"
  },
  "imo": {
    "appcid": "272562",
    "appuid": "5462392",
    "sync_app_key": "24bc3fef811a017771038323d80a6cae",
    "push_app_key": "352019d110cada000dac9184b3b30b59"
  }

**Comment by steedos** [comment]
请陈志培逐项测试
