### ISSUE TITLE
db.organizations.before.insert/update类似这样的语句，有很多地方没有判断userId是否存在

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#602]
当一个浏览器窗口注销登录后，另一个浏览器上点击更新按钮更新数据（没有自动跳转到登录界面或者自动跳转到登录界面前），可能会存在数据错误的情况，比如doc.created_by可能会变成undefiend，需要测试后确定。

**Comment by steedos** [comment]
具体问题具体处理
