### ISSUE TITLE
个人联系人点击导入，第一个弹出的窗口是不是没必要，应该直接弹出选人控件吧

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#604]
![image](https://cloud.githubusercontent.com/assets/6219465/20736440/6fef1d9e-b6e1-11e6-92ce-a305b4821197.png)

第一个弹出窗口中有个“人员”输入框，要点击才弹出选人控件，感觉怪怪的。

**Comment by steedos** [comment]
不处理
