### ISSUE TITLE
组织架构功能中，有时会出现拖动用户到某个组织后报错，但是用户成功转移了，感觉会有隐患。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#607]
Exception while invoking method 'move_space_users' TypeError: Cannot read property 'updateUsers' of undefined
I20161201-13:49:06.059(8)?     at packages/steedos_lib/lib/models/space_users.coffee:232:20
I20161201-13:49:06.060(8)?     at Array.forEach (native)
I20161201-13:49:06.060(8)?     at Object.<anonymous> (packages/steedos_lib/lib/models/space_users.coffee:230:32)
I20161201-13:49:06.060(8)?     at packages/matb33_collection-hooks/update.js:70:1
I20161201-13:49:06.061(8)?     at Array.forEach (native)
I20161201-13:49:06.061(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20161201-13:49:06.062(8)?     at packages/matb33_collection-hooks/update.js:69:1
I20161201-13:49:06.062(8)?     at Array.forEach (native)
I20161201-13:49:06.062(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20161201-13:49:06.062(8)?     at after (packages/matb33_collection-hooks/update.js:68:1)

**Comment by yinlianghui** [comment]
我今天碰到过几次，有一次直接刷新浏览器后再操作也遇到上面问题，但是没有找到重现规则。

**Comment by sunhaolin** [comment]
此问题由删除组织引起

**Comment by yinlianghui** [comment]
我重新测试过后，没有重现bug。
