### ISSUE TITLE
邮件回执

### ISSUE THREAD

**Issue by steedos** [steedos/apps#617]
- 写邮件时增加选项 “发送回执”
- 发送邮件时如果检测到此选项，则增加邮件头 Disposition-Notification-To: "Chilkat Software" <admin@chilkatsoft.com>
- 在阅读邮件时，如果检测到此选项，显示如下界面，如果用户选择发送，则自动发送一份邮件回执给对方。
![image](https://cloud.githubusercontent.com/assets/3104826/20963245/9b0708ae-bca7-11e6-8b90-4d69f5aef07b.png)

具体可以参考QQ邮箱

**Comment by yinlianghui** [comment]
新建邮件规则：
- [x] 在底部显示“需要回执”勾选框，当选中的时候表示需要对方回馈已读邮件，反之不需要。
- [x] 如果用户勾选了“需要回执”，则在对方收件箱打开邮件的时候会在邮件内容最底部显示类似“发件人希望得到您的回执..”的弹出框。
收邮件规则：
- [x] 当第一次打开未读邮件时，如果对方发件的时候勾选了“需要回执”，则在邮件内容最底部显示类似“发件人希望得到您的回执..”的弹出框，反之不显示。
- [x] 当打开已读邮件时，无论对方发件的时候是否勾选了“需要回执”，则都不显示类似“发件人希望得到您的回执..”的弹出框。
- [ ] 如果收到的是系统发送的回执邮件，则无论如何都不显示类似“发件人希望得到您的回执..”的弹出框。
在类似“发件人希望得到您的回执..”的弹出框中的操作规则：
- [x] 点击发送按钮，则发送回馈邮件给发件人并关掉弹出框，发件人会收到一封回执邮件，告诉发件人邮件已被打开阅读。
- [x] 点击不发送按钮，则直接关掉弹出框。

**Comment by yinlianghui** [comment]
测试要点：
- 要注意双向发邮件去测试实际效果是否如上述规则。
- 最好能测试下目前市场上常用邮箱有哪些是兼容的哪些是不兼容的，排出一个兼容性清单。

**Comment by steedos** [comment]
从QQ邮箱发送邮件到 hotoa.com ，发送时选择 需要回执，结果在邮件模块中看不到 发送回执按钮

**Comment by steedos** [comment]
阿里云的邮箱不支持

**Comment by yinlianghui** [comment]
今天陈这边测试到一个bug，即两个抚顺那边的邮件账户之间用回执功能发邮件的时候没有回执效果。
之前是用抚顺的账户与aliyun/qq邮箱之前测试的，抚顺发aliyun/qq，及aliyun/qq发抚顺正反两种情况都测试过，但是没有测试抚顺发抚顺的情况。
造成这个问题的原因是我们的邮件发件人及收件人的格式与的aliyun/qq格式不一样。
aliyun/qq的格式是：" "=?gb18030?B?x8zDqw==?=" <736775410@qq.com>"
我们的格式是：" =?UTF-8?Q?=E9=99=88=E5=BF=97=E5=9F=B9?=
 <hotoa@petrochina.com.cn>"

**Comment by yinlianghui** [comment]
打包到21上后需要重新测试。

**Comment by zhangshanshan2016** [comment]
![default](https://cloud.githubusercontent.com/assets/20197393/21797541/ba81cd14-d74a-11e6-8caf-e58a3e415991.png)
