### ISSUE TITLE
在cms文章列表翻页这块，有时添加/修改文章，或者点击一个未读文章时会出现翻页错乱的问题.

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#618]
今天有点时间的时候静下心来测试了几分钟，终于找到重现规则：
左侧点开一个站点，如果站点中有文章，则点击切换到另一个站点（文章列表带翻页，不确定是否要带分类），点击翻页按钮就会看到不能翻页的问题，浏览器控制台也没有报错。

**Comment by yinlianghui** [comment]
今天又测试了一次,发现上次测试到的重现规则无法再重现问题了。
然后发现另一个重现规则：
进入某个站点后，点开站点下的分类，如果这时有翻页按钮的话，点击翻页则一定会出现无法翻页的问题了。

**Comment by yinlianghui** [comment]
原因是之前默认没有选择分类栏目的时候显示的是包括所有分类栏目下的文章，改成默认只显示没有分类的文章就好了。

**Comment by zhemingloveme** [comment]
经测试：pc客户端，android客户端 ios客户端  在cms 翻页时，可以正常显示，切换站点的文章也可以显示
