### ISSUE TITLE
当服务不可能用（即服务ip地址无法访问）时，客户端显示一片空白，没有任何错误提示。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#623]
![image](https://cloud.githubusercontent.com/assets/6219465/21070034/e3cff9f0-beba-11e6-86a7-614531164d33.png)

**Comment by steedos** [comment]
![image](https://cloud.githubusercontent.com/assets/3104826/21308824/abc99512-c616-11e6-9f91-a6a5efdfcb9c.png)

我这里有提示
