### ISSUE TITLE
用钉钉扫码登陆，显示无服务

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#624]
当用钉钉扫描二维码登陆时，显示interal server error 
![qq 20161210130823](https://cloud.githubusercontent.com/assets/23308088/21071394/fcc0371c-bed9-11e6-9aec-5f34e1574ec9.png)
![qq 20161210130747](https://cloud.githubusercontent.com/assets/23308088/21071395/fcc37f9e-bed9-11e6-93a2-36050f11366c.png)

**Comment by steedos** [comment]
https://cn.steedos.com/kanban/b/fMYefy8GamcN6zRoy/steedos/85PdoJPJYFfocfWaz
