### ISSUE TITLE
apps推送消息开发

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#634]
- 新建申请单
- 草稿箱提交申请单：
    - [x] 发送消息给下一步处理人;
- 待审核提交申请单：
    - 如果下一步骤申请单结束
        - [x] 发送消息给当前用户（badge）
    - 如果下一步骤未结束
        - [x] 发送消息给下一步处理人
        - [x] 发送消息给当前用户（badge）
- - [x] 传阅
- 转签核：
    - [x] 发送给新指定的处理人
    - [x] 发送给旧处理人（badge）
- 重定位：
    - [x] 发送给新指定的处理人
    - [x] 发送给旧处理人（badge）
- 取消申请：
    - [x] 发送给待处理人
    - [x] 发送给被传阅人（badge）
- 监控箱删除申请单

**Comment by chenzhipei** [comment]
监控箱中删除流转中的申请单，处理人的待审核数没有变化
https://github.com/steedos/apps/issues/707
