### ISSUE TITLE
申请单 html 类型附件，显示预览按钮，使用 弹出窗口显示此 html 文件内容

### ISSUE THREAD

**Issue by steedos** [steedos/apps#647]
此功能主要为了为了处理显示转发之后的原申请单：
申请单转发时，增加选项，可把原表单作为第一个附件 #560

**Comment by yinlianghui** [comment]
已实现，规则如下：
- [x] html类型附件增加预览按钮，点击打开新窗口预览，但是原链接在PC上是下载，在手机上是打开新窗口预览，android app是下载。
- [x] 图片类型附件增加预览按钮，点击弹出图片展示层预览，但是原链接在PC上是下载，在手机上是打开新窗口预览，android app是下载。
- [x] 其他类型附件没有预览按钮，原链接在PC上都是下载，在手机上是打开新窗口预览，android app是下载。

android app上有点击附件下载功能，这个要打包测试，我没有测试。
我测试过iphone6s/chrome/firefox/ie11/edge
ie11/edge打开申请单会卡死且报错，没法确认，不过感觉之前我测试过没有问题的，可能是更新代码发现的新bug。

**Comment by yinlianghui** [comment]
ie11及edge今天测试过了，功能正常。
