### ISSUE TITLE
个性化设置网页字体大小

### ISSUE THREAD

**Issue by steedos** [steedos/apps#653]
- 每个用户的个性化设置菜单中，增加选项，可以设置字体大小
标准，大字体，超大字体
normal, large,extra-large
100%， 120%,  135%

- 系统启动时，根据用户设置的字体大小，给body增加样式 zoom-normal, zoom-large, zoom-extra-large

- 定义 css，针对不同的样式，配置对应的 zoom 属性

- 个性化样式中暂时注释掉设置主题功能，目前的白色主题比较丑，等将来调试好再说。

**Comment by steedos** [comment]
对于 windows 客户端，还有一种额外的设置方法：
nw.Window.get().zoomLevel = 0 正常
nw.Window.get().zoomLevel = 1 大
nw.Window.get().zoomLevel = 2 超大

**Comment by yinlianghui** [comment]
已完成，规则及测试要点：
1. iphone6s safari上加粗字体无法放大。
2. 字体加大后，在电脑和手机上都存在双层滚动条问题，而且出现双层滚动条的话，在mac/iphone6s的safari及mac上的chrome上无法滚动到底部（即滚动条底部内容看不到）。
3. ie11上放大后，右侧有一部分内容看不到，而且没有水平滚动条。
4. chrome/edge上效果相对来说最理想，没有什么大问题。
5. ifrefox不支持zoom属性，而且transform:scale(xx)及transform-origin:top left;样式会有上述第3点问题，即右侧有一部分内容看不到。
6. steedos客户端效果与windows上chrome效果基本一致。

**Comment by yinlianghui** [comment]
经与庄总讨论确定该问题后续要继续调式，争取解决滚动条问题。

**Comment by yinlianghui** [comment]
1. 个人联系人右侧搜索框加按钮在手机上会显示两行造成样式有点错乱（搜索框再小的话就几本没法用了）。

**Comment by yinlianghui** [comment]
上述未完成任务另报issue了，见：
手机上在大字体及超大字体时联系人APP中的个人联系人界面由于顶部操作按钮过多造成界面错乱 #870
iphone6s上账户设置中邮件界面，字段放大后，宽度不够造成样式问题，特别是添加了新邮件后问题更明显。 #871
ios原生app上设置放大字体后没有放大效果 #872

**Comment by zhemingloveme** [comment]
经测试：手机端：ios、android 浏览器端：IE11 桌面客户端：windos  均可以自定义字体，有标准字体、大字体、超大字体3种供选择，都可以正常显示！
、
