### ISSUE TITLE
选人控件，个人联系人，组织构架等用到jstree的地方，根目录的用户显示方案，是全部显示还是只显示根目录对应的用户。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#675]
有很多地方的用户列表用到了jstree，而且这些控件在邮件/审批王/联系人/系统设置等APP中都用到了，需要一个清楚的规则，建议最好统一规则（根目录的用户显示方案，是全部显示还是只显示根目录对应的用户。）

目前已测试的结果：
1. 联系人APP中组织构架是只显示根目录对应的用户。
2. 联系人APP中个人联系人是全部显示。

**Comment by steedos** [comment]
暂时按照这个规则不做调整。
