### ISSUE TITLE
Readonly view下，URL类型字段会自动加“http://”，手动添加“https://”后点击链接跳转失败。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#680]
![image](https://cloud.githubusercontent.com/assets/15027092/21422684/cb9b10be-c873-11e6-8f54-1064cd4a4aaa.png)
![image](https://cloud.githubusercontent.com/assets/15027092/21422691/d3b6390e-c873-11e6-8159-4fe58451a8d8.png)

**Comment by zhangshanshan2016** [comment]
测试过程：IE，Chrome, 客户端测试。1.url类型的字段，比如填写“tao.com”或“http://taobao.com”后，在Readonly view下，url里的值还是“tao.com”或“http://taobao.com”，值不发生变化，不会自动添加“http://”，链接均是可以打开。
2.在子表中，URL类型字段没有"http://"或“https://”时会自动加“http://”，手动添加“https://”后链接是可以打开。
