### ISSUE TITLE
打印表单预览，字段过多换页时，样式会乱，实际打印出来的单子换页处的样式也是乱的

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#686]
测试工作区：Demo2017
测试账号:chenzhipei@hotoa.cpm 密码：123456
测试流程：全字段测试
申请单id: ZMMNC9FkzdD3Meqsn
测试过程：打印预览样式错乱
![image](https://cloud.githubusercontent.com/assets/15027092/21446465/53937014-c901-11e6-9a4b-a81def5801bf.png)

**Comment by steedos** [comment]
http://stackoverflow.com/questions/1763639/how-to-deal-with-page-breaks-when-printing-a-large-html-table
可能的解决方案

**Comment by zhangshanshan2016** [comment]
chrome，edge打印”全字段测试 28”样式还是错乱，IE点击表单上的打印按钮时，只显示出来一页的内容
![image](https://cloud.githubusercontent.com/assets/20197393/21632132/045c5d54-d27e-11e6-9594-b835065f0fa2.png)

**Comment by baozhoutao** [comment]
请测试大众公用 合同流程的打印是否正常。

**Comment by baozhoutao** [comment]
readonly view 不支持类似语法：<tr {{#if true}} style='color:red' {{/if}}>...</tr>
会导致大众公用打印模板异常

**Comment by zhangshanshan2016** [comment]
IE，chrome打印预览是好的，chrome打印出来的申请单是好的，IE浏览器只打印出申请单的第一页的部分内容。
新建的issue:IE浏览器中打印申请单时，只打印出申请单的第一页 #744
