### ISSUE TITLE
传阅的申请单点击保存无效，传阅意见没有保存下来

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#687]
测试工作区：Demo2017
测试账号:sunhaolin@hotoa.cpm 密码：123456
测试流程：全字段测试
申请单id: 4wdnXcqhcuLaPnoXu
测试过程：填写意见后点击“保存”，没有提示消息，切换申请单后，意见栏为空

**Comment by baozhoutao** [comment]
此问题是由于 传阅文件是以只读view显示，暂存时，获得不到values 导致saveIn 函数直接return.
