### ISSUE TITLE
新增工作区信息页面

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#688]
1. 所有用户都可以看到工作区信息界面。
2. 工作区管理员可以新建工作区。
3. 工作区所有者可以新建/修改工作区。
4. 如果settings.public.admin.disableAddSpace为true则任何人都没有新建工作区功能。

**Comment by yinlianghui** [comment]
测试要点：
需要测试新建的工作区是否可以正常邀请用户并且正常使用审批王审批单子。

**Comment by zhemingloveme** [comment]
![image](https://cloud.githubusercontent.com/assets/23308088/24089676/42a5661a-0d74-11e7-8301-624272da961b.png)
拥有者账户，对工作区进行编辑。打开编辑页面，点击浏览器返回按钮，弹此窗口（安卓手机触摸返回键也会弹出此窗口）
