### ISSUE TITLE
打印已完成的表单，选择自定义样式ipad客户端响应时间过长，会卡死

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#689]
![img_0032](https://cloud.githubusercontent.com/assets/23308088/21447547/fe54def2-c910-11e6-9dca-7e0ff11aa971.png)
付费工作区，选择自定义，客户端无响应，卡死（ipad客户端）

Android客户提示只有专业版才有自定义模板功能，可是已经是付费专业版工作区！
iPhone客户端同样提示只有专业版才有自定义模板功能。

**Comment by steedos** [comment]
客户端已删除打印按钮
