### ISSUE TITLE
打印功能只有ios系统的web页面可以使用，其他环境都是无响应

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#691]
ios浏览器页面，可以正常使用打印功能
ios客户端，打印功能无响应
Android浏览器页面，打印功能无响应
Android客户端，打印功能无响应

**Comment by steedos** [comment]
可以尝试加入插件 https://github.com/katzer/cordova-plugin-printer

**Comment by steedos** [comment]
需求不强烈，暂时不处理
