### ISSUE TITLE
ipad端表单添加表格的 + 按钮，不灵敏

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#694]
需要点击多次才能添加成功，用户体验不好

**Comment by steedos** [comment]
估计手机有类似的问题，应该是因为 + 按钮太小，可以左右放大加宽。

**Comment by zhangshanshan2016** [comment]
1.手机上测试通过；
2. 重新建立一个新的issue：#730点击ipad表单中的子表的 + 按钮时，必须要点击两下，才出现子表

**Comment by baozhoutao** [comment]
此问题通过#730任务来处理，有此问题的不止是子表的 + 按钮
