### ISSUE TITLE
在手机上，看完申请单之后需要滑到最上面才能签批

### ISSUE THREAD

**Issue by steedos** [steedos/apps#696]

**Comment by steedos** [comment]
建一个分支，把申请单页面做成 三个Tab 

审核（只有草稿和待审核时候显示），表单，签核历程

**Comment by yinlianghui** [comment]
已完成，因为没有进一步确定这个分支是否最后会应用，所以后续一些细节我没有进一步优化，等确定后再动手。

**Comment by yinlianghui** [comment]
功能已完成，留下任务及BUG：
iphone 6s safari下，弹出审批层后，底部可以看到20px的黑色空隙。 #807

**Comment by zhemingloveme** [comment]
经测试：android客户端，处理申请单，在右下角会有笔的图标，点击后弹出窗口可以选择核准、驳回，填写处理意见，选择下一步处理人！
