### ISSUE TITLE
firefox 会在控制台提示：密码字段出现在一个不安全的 http:// 页面中。这是一个可能导致用户登录凭据被窃取的安全风险。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#700]
![image](https://cloud.githubusercontent.com/assets/6219465/21464531/b501857a-c9ba-11e6-97eb-9a6add9f994a.png)

功能不受影响，申请单中有密码字段就会有上述提示。

**Comment by steedos** [comment]
我们外网环境是https，开发环境才是 http
