### ISSUE TITLE
打印同一张申请单，各浏览器效果不同：ie11 分组和主表中的密码字段为空；Firefox:打印出来的样式混乱，只打印出第一张（共两张）

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#702]
测试工作区：Demo2017
测试账号:chenzhipei@hotoa.cpm 密码：123456
测试流程：全字段测试
申请单id: bdgkvw55o3cnfsLmR
测试过程：测试ie11、chrome、firefox打印效果

ie11：
![ie11](https://cloud.githubusercontent.com/assets/15027092/21465003/6c0eddf8-c9ca-11e6-83ad-7d916bb9e884.jpg)

firefox：
![firefox](https://cloud.githubusercontent.com/assets/15027092/21465014/fc1d8c50-c9ca-11e6-91a6-a240002d09f6.jpg)

**Comment by steedos** [comment]
fixfox 打印功能不处理

**Comment by steedos** [comment]
密码为空没问题
