### ISSUE TITLE
没有配置推送证书时，服务自动重新启动

### ISSUE THREAD

**Issue by steedos** [steedos/apps#705]
W20161224-15:02:19.737(8)? (STDERR) Error: ENOENT: no such file or directory, open 'C:\Users\dell\Documents\GitHub\apps\.meteor\local\build\programs\server\cert.pem'
W20161224-15:02:19.738(8)? (STDERR)     at Error (native)

**Comment by steedos** [comment]
没有配置证书的时候，不应该调用 push 相关功能。

**Comment by sunhaolin** [comment]
解决方案： 判断Meteor.settings.push是否为空，如为空则不配置Push.Configure
