### ISSUE TITLE
ie11 收不到推送通知

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#706]
前台输入$.notification.permissionLevel()，结果为“unsupported”
![image](https://cloud.githubusercontent.com/assets/15027092/21466263/6a8dd43c-c9fe-11e6-855f-793c72cfc068.png)

**Comment by steedos** [comment]
判断，如果是IE，则不发送推送通知

**Comment by chenzhipei** [comment]
测试ie11提交、chrome审批：chrome能收到推送通知，chrome提交，ie11审批：不影响功能，暂不处理
