### ISSUE TITLE
火狐浏览器，在设置“组织架构”时，对选中的“人员”进行编辑时，不能选择“所属部门”和“上级主管”

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#708]
账户：chenzhipei@hotoa.com 密码：123456
工作区：Demo2017
测试平台：本地开发环境（21数据库）
测试过程：点击“组织机构”，选择某人员编辑时，前台报错。

![image](https://cloud.githubusercontent.com/assets/20197393/21489940/79c50316-cc2a-11e6-9e09-8337e1bbe399.png)

**Comment by yinlianghui** [comment]
火狐不再做兼容处理。
