### ISSUE TITLE
IE浏览器，火狐，chrome上的workflow，“设置”中的“组织架构”的搜索功能失效

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#709]
账户：chenzhipei@hotoa.com 密码：123456
工作区：Demo2017
测试平台：本地开发环境（21数据库）
测试过程：点击“组织机构”，在“搜索“框中输入”邮件地址“或”姓名“进行搜索时，搜索结果都是”没有人员“。
![image](https://cloud.githubusercontent.com/assets/20197393/21491310/b381b610-cc36-11e6-9f7a-53d1f18943f9.png)

**Comment by sunhaolin** [comment]
关联 TabularTables增加changeSelector函数造成的审批王组织架构等搜索功能异常 #717

**Comment by yinlianghui** [comment]
该功能昨天 改好了，刚测试了下是正常的。
