### ISSUE TITLE
TabularTables增加changeSelector函数造成的审批王组织架构等搜索功能异常

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#717]
是因为之前为TabularTables增加changeSelector函数造成的。
之前增加changeSelector函数的任务见：https://github.com/steedos/apps/issues/597

**Comment by yinlianghui** [comment]
已解决，对照了之前增加changeSelector函数的任务中的清单，重新测试了一下，目前功能正常了。

**Comment by sunhaolin** [comment]
同 IE浏览器，火狐，chrome上的workflow，“设置”中的“组织架构”的搜索功能失效 #709
