### ISSUE TITLE
设置流程权限时，新增申请单的授权人员中不包括管理员，管理员不具有新增申请单的权限

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#718]
工作区：Demo2017(管理员：陈志培)
测试平台：本地开发环境（21数据库）
测试流程：czp测试/全字段测试

测试流程权限设置：
谁能新增申请单：
授权部门：Demo2017/新组织(孙浩淋)，  授权用户：test4                                                          
谁能查看所有申请单：
授权部门：Demo2017/0625测试/物管部(test5)，授权用户：test2                                                                      
谁能查看所有申请单，并能删除申请单：
 授权部门：Demo2017/czp测试(test3)， 授权用户：test1
                                                                                                   
测试过程：设置“全字段测试”流程的流程权限:
 1.在“新增申请单”的“授权部门”和“授权用户”中不包括管理员，管理员不具有新增申请单的权限。
   2.在“监控箱”中，点击“按流程查看申请单”按钮时，不能按“全字段测试”流程查看所有流程
![default](https://cloud.githubusercontent.com/assets/20197393/21513462/d78e18c4-ccf3-11e6-9311-d0f4e51e6c3b.PNG)
![default](https://cloud.githubusercontent.com/assets/20197393/21513463/e0d9ffb0-ccf3-11e6-93a6-f451c7af5216.PNG)

**Comment by sunhaolin** [comment]
经测试此逻辑与老板workflow逻辑一致
