### ISSUE TITLE
新版审批王表单中看不到“表单描述”内容，旧版是能看到的

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#719]
旧版：
![image](https://cloud.githubusercontent.com/assets/15027092/21514213/80ca7e42-ccfd-11e6-8d24-29165d81ef32.png)

新版：
![image](https://cloud.githubusercontent.com/assets/15027092/21514215/8ddbac5a-ccfd-11e6-8f74-9a2a9d8ef809.png)

**Comment by baozhoutao** [comment]
请测试：打印、编辑、只读、文件转发转存附件 情况下的表单描述是否显示正常

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome Edge iOS android端，在流程设计器中，添加表单描述。新建表单可以正常显示表单描述，在已审核中／监控箱中／打印／编辑／只读／文件作为附件转发都可以正常显示
