### ISSUE TITLE
流程设计器中打开已有流程，修改表单字段公式后点击保存，前台报错

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#720]
测试工作区：Demo2017
测试流程: 全字段测试（公式）
测试账号:chenzhipei@hotoa.com 密码:123456
![image](https://cloud.githubusercontent.com/assets/15027092/21517180/c9f2eb12-cd17-11e6-9a96-0eb6333abd21.png)

**Comment by zhangshanshan2016** [comment]
在IE和chrome上分别修改和增加表单上的字段公式，保存后，前台没有报错
