### ISSUE TITLE
手机上登录界面顶部toolbar定位有问题。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#721]
![image](https://cloud.githubusercontent.com/assets/6219465/21534995/43adfc52-cdaa-11e6-8ca8-68ccd561c304.png)
确认过没有设置大字体时一样会有问题的，应该是之前改成绝对定位造成的。

**Comment by yinlianghui** [comment]
已解决，同时加上了滚动条显示，因为注册界面内容比较多，会需要滚动条。

**Comment by zhangshanshan2016** [comment]
手机App测试通过；
手机浏览器测试通过；
