### ISSUE TITLE
进入”组织架构“后，进行搜索后，再点击左侧的部门，右侧没有显示出该部门对应的人员

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#722]
测试工作区：Demo2017
测试账户：zhangshanshan@hotoa.com，密码：123456
测试过程：点击进入”设置“里的”组织架构“，对某个人员进行搜索，搜索后，再点击左侧部门，右侧并没有显示出该部门所对应的相关人员，右侧显示的是该部门对该人员的搜索结果。
![default](https://cloud.githubusercontent.com/assets/20197393/21536109/4b937dac-cdb9-11e6-9933-721945f4b85c.PNG)
![1](https://cloud.githubusercontent.com/assets/20197393/21536111/51ee4592-cdb9-11e6-9a2b-8565d252df0c.PNG)

**Comment by steedos** [comment]
切换部门时清除搜索结果

**Comment by zhangshanshan2016** [comment]
测试过程：IE，chrome浏览器，app测试通过
