### ISSUE TITLE
新版审批王基于申请人和基于姓名表单字段的公式不生效，前台报错，旧版能生效。

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#727]
测试工作区：Demo2017
测试流程：全字段测试（公式）
测试申请单id：BYxfdm66J4YFMkJq7
测试账号：chenzhipei@hotoa.com 密码：123456
测试的公式：
- 申请人的姓名：{applicant.name}
- 申请人所在部门（全路径）： {applicant.organization.fullname}
- 申请人所在部门（最底层部门名）： {applicant.organization.name}
- 申请人的角色名： {applicant.roles}
- “报销人”所在部门（全路径）： {报销人}.organization.fullname
- “报销人”所在部门（最底层部门名）： {报销人}.organization.name
- “报销人”的角色名： {报销人}.roles
- “报销人”的姓名： {报销人}.name

新版审批王：
![image](https://cloud.githubusercontent.com/assets/15027092/21562248/631891d4-ceb2-11e6-945a-3aa6b5dd6d50.png)

旧版审批王：
![image](https://cloud.githubusercontent.com/assets/15027092/21562487/25870646-ceb4-11e6-9f76-91a48785468a.png)

**Comment by zhangshanshan2016** [comment]
1.IE，chrome，手机上建立 “全字段测试（公式）”申请单，公式字段生效。
2.申请人属于多个部门时，申请人所在部门只显示出来一个。
