### ISSUE TITLE
ipad：safari、APP、chrome 上， 弹出modal的按钮(子表、选人选组) 需要点击2次才能弹出

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#730]

**Comment by baozhoutao** [comment]
其中申请人字段：input类型， readonly 在点击后会获得光标，然后始终都无法弹出选人modal，需要点击其他地方(非当前input) 后，再次点击才可弹出modal。

**Comment by baozhoutao** [comment]
通过focus 给其他对象是设置光标也不能处理次问题

**Comment by zhangshanshan2016** [comment]
同一个issue：ipad 浏览器和APP部分按钮需要点击2次才能触发 #724

**Comment by baozhoutao** [comment]
修改：
子表：新增、删除、编辑按钮
选人、选组控件
sidebar：流程新建按钮

**Comment by zhemingloveme** [comment]
经测试：ipad客户端，查看申请单后，该申请单为蓝色，再次点击左边的文件箱（点击另一条申请单）。还是需要点击2次才能触发！

**Comment by zhemingloveme** [comment]
ipad上，选择传阅对象时，点击左边的选项框和点击名字右边灰色区域不同步。触发状态不同步
![img_0050](https://cloud.githubusercontent.com/assets/23308088/21885363/3c4e1fd4-d8f2-11e6-8387-a0accf17d84a.png)

**Comment by zhemingloveme** [comment]
同#809，已经处理通过测试！
