### ISSUE TITLE
高级搜索后，再次点击搜索下拉框，有的字段会自动填充，有的则不会

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#732]
按流程查询后会自动填充：
![image](https://cloud.githubusercontent.com/assets/15027092/21604962/1d78722a-d1e1-11e6-929a-72e84b342024.png)

按申请人查询后不会自动填充：
![image](https://cloud.githubusercontent.com/assets/15027092/21605023/6ef450f6-d1e1-11e6-8b9b-58b4aa601547.png)

**Comment by sunhaolin** [comment]
允许此种情况，需要优化：当用户在搜索框中输入搜索内容时显示 “搜索的结果：x”

**Comment by steedos** [comment]
暂停，转移到看板
