### ISSUE TITLE
edge/ie中，选人控件中的头像是歪的

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#735]
测试了安卓手机客户端、edge、ie、chrome、火狐，ie和edge中是歪的
![image](https://cloud.githubusercontent.com/assets/15027092/21633492/a2b4dd80-d28a-11e6-93dc-32d687f69959.png)

**Comment by yinlianghui** [comment]
请重新测试下所有浏览器的情况，特别是手机APP及PC客户端。

**Comment by zhemingloveme** [comment]
经测试：手机App、IE11 Edge浏览器、windows客户端，使用选人控件时，头像呈居中显示！
