### ISSUE TITLE
在审批王的某个文件箱的搜索框中进行搜索后，再点击其他文件箱时，没有出现该文件箱对应的申请单，而是搜索后的申请单

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#740]
测试账户： chenzhipei@hotoa.com , 密码：123456
测试space:  Deomo2017
![image](https://cloud.githubusercontent.com/assets/20197393/21667002/7cd7bb04-d330-11e6-840d-271728694886.png)

**Comment by sunhaolin** [comment]
允许此种情况，需要优化：当用户在搜索框中输入搜索内容时显示 “搜索的结果：x”

**Comment by zhemingloveme** [comment]
经测试; Chrome IE11  在搜索框中输入关键字，下面会显示搜索结果：  然后是搜索的数据。点击其他的文件箱，依然还会显示搜索结果字样。点击右上角的 X 关闭按钮，会回到相应的文件箱！
