### ISSUE TITLE
ios平台（iPhone和ipad）：新建表单，下一步骤的列表框变窄

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#741]
![img_0045](https://cloud.githubusercontent.com/assets/23308088/21668245/ebee02dc-d33a-11e6-984f-4af9c84f11b0.png)

经测试：CN环境下不存在这样的问题  
              21测试环境下：iOS系统（iPhone客户端、浏览器和ipad客户端、浏览器）下拉框变窄
                                     Android系统没有问题

**Comment by yinlianghui** [comment]
已解决，所有safari统一去掉了默认样式，留下一片空白。

**Comment by zhemingloveme** [comment]
经测试：IOS客户端，Safari  下一步骤在下面，呈现空白
