### ISSUE TITLE
workflow：同一个步骤多次处理时(非同一个处理人) 会出现错误提醒

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#742]
申请单：http://steedos.ticp.net:3134/workflow/space/52ba669333490464b4000065/inbox/4APH9J3qoxoDMtLM7

**Comment by baozhoutao** [comment]
![image](https://cloud.githubusercontent.com/assets/6194462/21675496/f3e563c2-d36c-11e6-8e7a-3ab291055be7.png)

**Comment by zhemingloveme** [comment]
经测试：Chrome IE11  同一个步骤多人处理时，不会出现错误提醒。只要有进行处理，其他的登陆账户就会同步到最新的处理结果。
