### ISSUE TITLE
普通用户（非工作区管理员）无法通过组织机构导入个人联系人

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#743]

**Comment by zhemingloveme** [comment]
经测试：Chrome、IE、ios客户端和Safari、Android客户端和浏览器   
                          普通用户是无法导入联系人的，点击设置，只有‘’账户设置‘’按钮
                          工作区拥有者和管理员可以查看和管理联系人的功能

**Comment by zhemingloveme** [comment]
经测试：Chrome IE11   点击左上角，选择个人联系人，可以看到组织结构下边有个人联系人，点击进去可以进行修改（添加和删除），普通用户和管理员都可以进行此操作！
