### ISSUE TITLE
3.2 数据库升级脚本：flows.print_template

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#746]
替换flows.print_template 字段中{{#formatDate finish_date}}{{/formatDate}} 为{{formatDate finish_date}}

**Comment by sunhaolin** [comment]
db.getCollection('flows').find({
    print_template: /{{#formatDate finish_date}}{{\/formatDate}}/
}, {
    print_template: 1
}).forEach(function(f) {
    var new_print_template = f.print_template.replace(/{{#formatDate finish_date}}{{\/formatDate}}/g, '{{formatDate finish_date}}');
    db.flows.update({
        _id: f._id
    }, {
        $set: {
            print_template: new_print_template
        }
    });
})

**Comment by sunhaolin** [comment]
包确认不用执行此脚本
