### ISSUE TITLE
改善知识库界面

### ISSUE THREAD

**Issue by steedos** [steedos/apps#747]
- 中间栏navigationbar右侧增加下拉菜单，可以预览站点、新建栏目、编辑栏目、删除栏目、修改站点、删除站点，
- 去掉左边菜单上的下拉菜单
- 中间栏navigationbar固定，列表滚动
- 右侧栏navigationbar中间显示标题，手机上左侧显示返回，右侧显示下拉菜单

**Comment by yinlianghui** [comment]
上述所有要求已完成

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome  android客户端，在CMS上，可以正常添加，编辑，删除站点/栏目/文章。搜索功能也可以正常使用！
