### ISSUE TITLE
组织机构中设置为无效的用户应该为灰色，现在看不到无效的用户，无法找回该用户

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#751]

**Comment by chenzhipei** [comment]
目前修改为：无效用户为灰色，选人控件中不显示，组织机构中显示
请测试：chrome、ie11和手机上管理员、分级管理员、普通用户登陆后的情况

**Comment by zhemingloveme** [comment]
经测试：Chrome 、IE11、 App  上管理员、分级管理员、普通用户，设置为无效用户后，会显示为灰色
