### ISSUE TITLE
帮助下面新增关于菜单

### ISSUE THREAD

**Issue by steedos** [steedos/apps#755]
关于 Steedos Apps
About Steedos Apps

Steedos Apps 是深受公司员工喜爱的云端的企业管理软件，帮助您的团队随时随地的沟通与协作。
Steedos Apps is a cloud-based productivity suite that helps you and your team connect and get work done from anywhere on any device.
（以上文字弹出新窗口链接到 https://www.steedos.com/）

版本号：Steedos.Info.version
修订日期：Steedos.Info.commit.date "Fri Jan 6 18:06:53 2017 +0800"
发布日期：Steedos.Info.build.date "Fri Jan 6 18:06:53 2017 +0800"

© 华炎软件. 保留所有权利.
© HotLong Software. All rights reserverd.

**Comment by chenzhipei** [comment]
请测试浏览器和手机客户端情况（中英文）

**Comment by zhangshanshan2016** [comment]
修订日期 ：控制台报错

**Comment by zhangshanshan2016** [comment]
测试过程：开发版上 张姗姗本地服务（192.168.0.142:3000）上的 ”修订日期“显示不出来，其他人本地服务上的“修订日期”都可以显示出来。

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome Edge ios客户端 pc端 点击关于，会显示：
Steedos Apps    
Steedos Apps 是深受公司员工喜爱的云端的企业管理软件，帮助您的团队随时随地的沟通与协作。https://www.steedos.com/   
版本号：
修订日期：
发布日期：
