### ISSUE TITLE
workflow：订阅instance、flow、form 到本地

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#756]
1、签核历程可以预览当前填写的意见
2、一个文件多个窗口打开时，一个窗口处理掉后，其他窗口应该跳转到list列表

**Comment by baozhoutao** [comment]
测试点：
1、签核历程可以预览当前填写的意见
2、一个文件多个窗口打开时，一个窗口处理掉后，其他窗口应该跳转到list列表
3、自定义模板支持：instanceSignText 模板：{{> instanceSignText step='秘书核稿' default='已阅'}}

**Comment by zhemingloveme** [comment]
经测试：1.在填写处理意见时，签核历程会实时同步显示
               2.一个文件在多个窗口打开处理，会同步最新的处理结果

**Comment by zhangshanshan2016** [comment]
测试点：自定义模板支持：instanceSignText 模板：{{> instanceSignText step='秘书核稿' default='已阅'}}

该点的测试过程：在steedos.ticp.net:8888上建立“河北港口集团有限公司发文”，在“'秘书核稿”的那一栏中出现“签批”，签批的内容就是审批的意见，如果没有填写审批意见时，签批的内容是'已阅'。
