### ISSUE TITLE
桌面 App 客户端会记住密码，存在安全隐患

### ISSUE THREAD

**Issue by steedos** [steedos/apps#764]

**Comment by steedos** [comment]
http://stackoverflow.com/questions/10938891/disable-form-autofill-in-chrome-without-disabling-autocomplete

Here's the magic you want:

    autocomplete="new-password"
Chrome intentionally ignores autocomplete="off" and autocomplete="false". However, they put new-password in as a special clause to stop new password forms from being auto-filled.

**Comment by zhangshanshan2016** [comment]
测试过程：登陆客户端后，注销，再登陆时，没有出现密码
