### ISSUE TITLE
Android客户端返回键不兼容

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#765]
![s70109-13145095](https://cloud.githubusercontent.com/assets/23308088/21757693/acf6cf2e-d66d-11e6-8312-81f1aa9c7cfb.jpg)
点击右上角的 x 号按钮，可以关闭！但是，触摸手机的返回按钮客户端就无响应
若要退出steedos客户端，也不可以连续触摸返回键，需要强制关闭到后台！
用户体验不完美

**Comment by steedos** [comment]
https://cn.steedos.com/kanban/b/f4WoHRKwJh8FeeMds/app/9g5GD4GzpyztLXJmY
