### ISSUE TITLE
待审核提交报错

### ISSUE THREAD

**Issue by steedos** [steedos/apps#767]
9340100@qq.com
http://127.0.0.1:3000/workflow/space/560fbad9527eca0e3b000001/inbox/576e97a0d77d5e7a310006e6

W20170109-15:45:14.683(8)? (STDERR) TypeError: outbox_users.unshift is not a function
W20170109-15:45:14.684(8)? (STDERR)     at Object.uuflowManager.engine_step_type_is_start_or_submit_or_condition (packages/steedos_workflow/server/lib/uuflow_manager.coffee:646:31)
W20170109-15:45:14.686(8)? (STDERR)     at packages/steedos_workflow/routes/api_workflow_engine.coffee:105:32
W20170109-15:45:14.686(8)? (STDERR)     at Array.forEach (native)
W20170109-15:45:14.687(8)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20170109-15:45:14.687(8)? (STDERR)     at packages/steedos_workflow/routes/api_workflow_engine.coffee:8:5
W20170109-15:45:14.687(8)? (STDERR)     at packages/simple_json-routes/json-routes.js:76:1
W20170109-15:45:47.038(8)? (STDERR) TypeError: outbox_users.unshift is not a function
W20170109-15:45:47.039(8)? (STDERR)     at Object.uuflowManager.engine_step_type_is_start_or_submit_or_condition (packages/steedos_workflow/server/lib/uuflow_manager.coffee:646:31)
W20170109-15:45:47.041(8)? (STDERR)     at packages/steedos_workflow/routes/api_workflow_engine.coffee:105:32
W20170109-15:45:47.042(8)? (STDERR)     at Array.forEach (native)
W20170109-15:45:47.042(8)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20170109-15:45:47.042(8)? (STDERR)     at packages/steedos_workflow/routes/api_workflow_engine.coffee:8:5
W20170109-15:45:47.043(8)? (STDERR)     at packages/simple_json-routes/json-routes.js:76:1

**Comment by zhangshanshan2016** [comment]
测试过程：打开IE，Chrome控制台，提交待审核的申请单后，控制台没有报错
