### ISSUE TITLE
新建草稿提交报错

### ISSUE THREAD

**Issue by steedos** [steedos/apps#768]
申请付款

I20170109-15:57:38.779(8)? Exception while invoking method 'inbox_save_instance' TypeError: Cannot read property 'traces' of undefined
I20170109-15:57:38.779(8)?     at [object Object].Meteor.methods.inbox_save_instance (packages/steedos_workflow/server/methods/save_instance.js:167:1)
I20170109-15:57:38.780(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20170109-15:57:38.780(8)?     at packages/ddp-server/livedata_server.js:711:19
I20170109-15:57:38.781(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20170109-15:57:38.781(8)?     at packages/ddp-server/livedata_server.js:709:40
I20170109-15:57:38.782(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20170109-15:57:38.782(8)?     at packages/ddp-server/livedata_server.js:707:46
I20170109-15:57:38.783(8)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20170109-15:57:38.783(8)?     at packages/ddp-server/livedata_server.js:551:43

**Comment by baozhoutao** [comment]
此问题是由于日期控件处罚了change事件导致。https://github.com/steedos/apps/commit/fb7427facba9a559effa3de0815e505a7e050c5f

**Comment by zhangshanshan2016** [comment]
测试过程：打开IE和Chrome浏览器控制台，提交草稿箱申请单，控制台没有报错
