### ISSUE TITLE
知识库切换工作区列表页显示的是审批王中的待审核文件数量

### ISSUE THREAD

**Issue by steedos** [steedos/apps#769]

**Comment by yinlianghui** [comment]
规则要点：
每个应用左上角工作区列表显示当前应用在每个工作区的badge数量，目前只有审批王及知识库两个应用有badge数量功能，即目前其他应用（包括系统设置、联系人等）中左上角工作区列表是不会显示badge数量的。
点击左上角应用名称会弹出应用列表层，该界面的badge规则类似上述左上角工作区列表，但是显示的是每个应用在所有工作区的badge数量总合。
之前的系统首页（该界面理论上作废，防止有其他链接进来我一起同步了相应逻辑），即路由/steedos/springboard，也有应用列表，其badge规则与上述弹出的应用列表层一样。

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome  点开审批王和知识库，左边的红点在其他工作区有待审核的情况下显示，如果这个时候，点击进去有待审核的工作区，小红点自然消失。在工作区中，只要刚刚有新的审批单需要审核，小红点就会显示，点开切换到其他待审核的工作区则消失！

多端同时处理申请单时，以最新的处理结果为准！
