### ISSUE TITLE
组织机构管理时，按姓名搜索，搜索不到用户，搜索范围有误

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#771]
![image](https://cloud.githubusercontent.com/assets/15027092/21790905/699d5bd2-d71a-11e6-9809-c60993991110.png)

**Comment by sunhaolin** [comment]
已确认属于正常情况，全局搜索为新功能，待开发

**Comment by steedos** [comment]
有搜索条件时，不考虑左侧选中的部门，在所有部门中搜索

**Comment by zhemingloveme** [comment]
经测试：IE11 chrome Edge浏览器中，打开联系人，选择组织架构，点击搜索框，输入搜索字段，可以根据字段快速锁定联系人。只能进行查看，没有修改操作权限！
