### ISSUE TITLE
选人控件中搜索出同名账号，但不显示是哪个单位哪个部门的

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#772]
![image](https://cloud.githubusercontent.com/assets/15027092/21791020/09276d28-d71b-11e6-8aa7-b570340e22bb.png)

**Comment by chenzhipei** [comment]
请测试桌面客户端情况，管理员和普通人员点击收件人，弹出该人员详细信息

**Comment by zhemingloveme** [comment]
https://github.com/steedos/apps/issues/814 已经处理成功
