### ISSUE TITLE
审批王的登录界面，登录密码报错时，提示是英文，而不是中文

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#773]
![image](https://cloud.githubusercontent.com/assets/20197393/21791223/58787894-d71c-11e6-9f81-2527bd69daa6.png)

**Comment by yinlianghui** [comment]
中文：账号或密码错误
英文：Account or password error

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome Edge  android客户端，ios客户端 在登录界面，输入账号或者密码错误，中文版本错误提示：用户名或密码错误 英文版本错误提示：Username or password is wrong
