### ISSUE TITLE
组织机构人员不能跨页排序

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#774]
![image](https://cloud.githubusercontent.com/assets/15027092/21791207/39b880ac-d71c-11e6-8b51-aa65673ad1be.png)

**Comment by sunhaolin** [comment]
需要升级数据库3.4.1

**Comment by zhemingloveme** [comment]
经测试：IE11  Chrome 打开组织结构，点击右边的排序按钮，尽管很多页联系人，也可以正常排序！

**Comment by steedos** [comment]
需要更新抚顺石化和外网的数据库之后才能标记为 fix done

**Comment by zhemingloveme** [comment]
测试点：点击名称排序，观察排序的顺序（所有页码）是否按照a-z字母进行排序!

**Comment by sunhaolin** [comment]
这是解决排序号的问题，别跟数据库排序搞混淆， 数据库排序任务：Mongodb 数据库 排序 #531

**Comment by zhemingloveme** [comment]
目前，修改为审批王组织机构联系人默认排序：首先考虑排序号，其次是文字的汉语拼音a-z顺序排序，最后是英文字母

**Comment by sunhaolin** [comment]
已修改请重新测试

**Comment by steedos** [comment]
待 cn us 都升级之后再标记 fix:Done
