### ISSUE TITLE
新工作区第一次进入审批王自动导入流程

### ISSUE THREAD

**Issue by steedos** [steedos/apps#778]
- 默认流程模版放在代码中
- 进入审批王时，判断如果一个流程都没有，自动导入默认流程模版
- 流程模版分中文和英文模版

**Comment by baozhoutao** [comment]
可通过此脚本批量导出模板文件（必须是工作区管理员）：db.forms.find({state:"enabled"}).forEach(function(form){window.open(Meteor.absoluteUrl("api/workflow/export/form?form="+form._id))})

**Comment by baozhoutao** [comment]
通过注册功能进行测试。

**Comment by baozhoutao** [comment]
请陈志培在workflow/server/flow-template/ 文件夹下新建en、zh-CN文件夹，把模板文件拆开

**Comment by chenzhipei** [comment]
请测试浏览器默认语言为中、英文下新用户注册后新增流程是否能看到默认的流程
