### ISSUE TITLE
已经登录审批王的浏览器，拷贝其他人发来的链接打开。没有错误提示，也无响应

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#780]
在21环境下，拷贝他人发来的链接
http://192.168.0.21/workflow/space/53215960334904539e00121a/inbox/57dfabdb384c6a007e00001d
    是他工作区的链接，我点击后
![default](https://cloud.githubusercontent.com/assets/23308088/21797746/dc49d31e-d74b-11e6-8651-6574f5ebfd81.png)
   没有错误提醒，页面无响应，一直在加载中……

**Comment by baozhoutao** [comment]
如果是无效、无权限的申请单id，则退回到列表页面。
