### ISSUE TITLE
邮件模块全选框选中后，切换文件箱或点击换页，全选框还是选中状态

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#781]
![image](https://cloud.githubusercontent.com/assets/15027092/21799984/9336003e-d756-11e6-9f08-a59a31fd5d15.png)

**Comment by zhangshanshan2016** [comment]
测试过程：在21上测试后，邮件模块全选框选中后，切换文件箱或点击换页，全选框还是选中状态
