### ISSUE TITLE
当管理员设置某人为无效时，此人应该不能选择进入此工作区

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#783]
当管理员设置某人为无效时，这个人还有待审核的单子，他还可以继续审批，但是别人是不能指定他审批的（因为他被设置为无效）
当这个人（被设置为无效的人）继续审批待审核中的单子时，待审核箱子的数据，和右边不同步！
![_20170110180449](https://cloud.githubusercontent.com/assets/23308088/21802282/fae7a788-d75f-11e6-82bb-82d29eaa4999.png)

**Comment by steedos** [comment]
当管理员设置某人为无效时，此人应该不能选择进入此工作区

**Comment by zhemingloveme** [comment]
经测试：管理员用户设置某人为无效用户时，这个人的此工作区也会被删除，且不存在任何有关此工作区的相关信息
