### ISSUE TITLE
点击转发邮件，弹出附件保存对话框且转发邮件的附件都没有带上

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#786]
![image](https://cloud.githubusercontent.com/assets/15027092/21839969/be6ae8b8-d815-11e6-9c37-2374ebf44cc6.png)

![image](https://cloud.githubusercontent.com/assets/15027092/21840001/e22d5b8c-d815-11e6-9972-7b978196047b.png)

**Comment by zhangshanshan2016** [comment]
同一个问题：打开emailjs草稿箱，点击带附件邮件时，邮件自动下载另存 #784
