### ISSUE TITLE
在待审核、草稿进行点击打印，在打印页面可以操作附件的bug

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#787]

**Comment by zhemingloveme** [comment]
经测试：在IE11 情况下提示请使用Chrome浏览器进行打印，如果有附件是可以显示，并可以点击下载附件，没有附件则不显示附件一栏
               在Chrome情况下，进行打印，如果有附件可以显示，并可以点击下载附件，没有附件则不显示附件一栏
