### ISSUE TITLE
左侧sidebar滚动条滚动到顶部一定位置的时候，其顶部操作元素无法操作。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#790]
![image](https://cloud.githubusercontent.com/assets/6219465/21843639/b23ead48-d826-11e6-9435-7fe325614afa.png)

上图所示红线部分无法操作。
cms/workflow等都有这个问题。
手机上比较明显。

**Comment by yinlianghui** [comment]
移除了每个 app下左侧main-sidebar中的contacts-sidebar样式类及 main-header中的steedos样式类。
请测试每个app的左侧菜单是否能正常工作，包括手机上也要测试。

**Comment by zhangshanshan2016** [comment]
测试过程：浏览器正常，手机APP重新打包后，再测试一下.在CMS中新建站点时报错。

**Comment by zhangshanshan2016** [comment]
测试过程：21重新打包后，手机APP正常。
