### ISSUE TITLE
有传阅(未处理)的申请单提交到结束后，传阅用户处理时，前台报错error

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#791]
服务端报错:
Exception while invoking method 'cc_submit' TypeError: Cannot read property 'forEach' of undefined
 at packages/steedos_workflow/server/methods/trace_approve_cc.js:146:1

**Comment by baozhoutao** [comment]
删除传阅记录也报错

**Comment by baozhoutao** [comment]
此问题是由于代码未考虑结束步骤没有approves属性的情况

**Comment by zhangshanshan2016** [comment]
测试过程：IE，chrome，电脑客户端，处理已经结束的（未处理的）传阅时，前台没有报错
