### ISSUE TITLE
PC上左侧sidebar上收起状态上鼠标放上去有样式显示BUG

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#797]
![image](https://cloud.githubusercontent.com/assets/6219465/21877728/048784f2-d8c8-11e6-85a2-1a8eaca1d8e9.png)

![image](https://cloud.githubusercontent.com/assets/6219465/21877829/d05b5fc2-d8c8-11e6-94fe-18a6edfd08ea.png)

**Comment by yinlianghui** [comment]
请测试时测试CMS及审批王两处APP

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome  Edge 浏览器 在知识库和审批王界面时，收起状态栏，未出现下面黑色短线，显示正常！
