### ISSUE TITLE
部分浏览器应用弹出层连线样式有问题。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#802]
Edge浏览器效果如下：
![image](https://cloud.githubusercontent.com/assets/6219465/21880274/02dfa7c2-d8d9-11e6-87fe-90a88f4f65a9.png)

Firefox效果如下:
![image](https://cloud.githubusercontent.com/assets/6219465/21880291/26b45e0e-d8d9-11e6-9d89-b13262b8bcba.png)

**Comment by steedos** [comment]
firefox 问题不处理
