### ISSUE TITLE
手机上增加滚动条事件实现滚动到底部时自动弹出审批层。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#808]

**Comment by yinlianghui** [comment]
请测试iphone/android手机/ipad/各个电脑浏览器，如ie/edge/safari，我没有全测试。

**Comment by zhemingloveme** [comment]
经测试：android客户端，iphone客户端，ipad客户端，IE11.Chrome Edge  均可以在申请单的最下面，自动弹出审批层
