### ISSUE TITLE
ipad：jquery perfectScrollbar 会导致ipad上部分标签的click事件需要点击多次才触发

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#809]
1、sidebar 中的 a标签
2、Tabular.Table 列表

修改方案为：不再ipad上使用perfectScrollbar 控件

**Comment by baozhoutao** [comment]
请不要在移动设备perfectScrollbar控件，此控件会引起pad上的click事件异常

**Comment by baozhoutao** [comment]
请测试ipad ：选人控件、新建流程、申请单 子表新增、编辑、删除功能 是否正常。

**Comment by zhemingloveme** [comment]
经测试：ipad上选人控件可以正常切换，新建申请单，删除功能，取回，传阅，文件转发编辑功能可以正常点击触发
