### ISSUE TITLE
自定义应用：App 密钥添加限制，如果有填写App密钥，则长度必须为16位

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#811]
如果App 密钥有值，单长度!=16 ，点击自定义应用会报错：
Error: Invalid IV length
   at Error (native)
   at new Cipheriv (crypto.js:187:16)
   at Object.Cipheriv (crypto.js:185:12)
   at packages/steedos_api/routes/sso.coffee:60:20
   at packages/simple_json-routes/json-routes.js:76:1

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome Edge  在添加自定义应用的时候，APP密钥必须要输入16位字符，否则会红色窗口提醒：App 密钥最短16字符长
