### ISSUE TITLE
开发人员信息查看页面

### ISSUE THREAD

**Issue by steedos** [steedos/apps#814]
显示人员姓名、邮件、手机、所属部门等信息

**Comment by steedos** [comment]
重复任务 选人控件中搜索出同名账号，但不显示是哪个单位哪个部门的 #772

**Comment by chenzhipei** [comment]
请测试手机客户端、电脑浏览器和桌面客户端情况，管理员和普通人员点击组织机构中的人，弹出该人员相关信息

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome Edge pc客户端，手机客户端，选择联系人，点击右侧联系人列表可以查看：姓名、邮箱、电话、所属部门
