### ISSUE TITLE
手机端的工作区和浏览器端的不一致，IE11 没有滚动条

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#816]
![img_0052](https://cloud.githubusercontent.com/assets/23308088/21960746/b98e3e22-db2f-11e6-84fe-7172fadb8200.png)
![default](https://cloud.githubusercontent.com/assets/23308088/21960747/c24a948e-db2f-11e6-9b19-130dbf626fb1.png)

IE11  既没有滚动条，工作区又显示不全
Chrome  有滚动条，但是滑动鼠标第三键滑轮，不可以触发滚动条。需要鼠标左键点击，拖动才可以
Egde  可以正常使用

**Comment by steedos** [comment]
只有测试人员才有这么多工作区
