### ISSUE TITLE
自定义样式，ipad显示不全

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#817]
![img_0051](https://cloud.githubusercontent.com/assets/23308088/21960845/902498a8-db32-11e6-8e5f-c4648b91d8c6.png)

![img_0054](https://cloud.githubusercontent.com/assets/23308088/21960839/73f9be42-db32-11e6-9a18-88dfe0b3ba43.png)

**Comment by steedos** [comment]
已单独安排任务
