### ISSUE TITLE
工作区初始化bug：创建工作区后，可以看到未启用的应用

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#818]
![image](https://cloud.githubusercontent.com/assets/6194462/21961111/fb67d7c0-db3b-11e6-8438-daa753b69e5e.png)

**Comment by steedos** [comment]
目前的规则是未选择任何应用时，显示所有应用。是有点怪。

**Comment by yinlianghui** [comment]
启用应用功能已去除了，所以不存在上述问题了。
