### ISSUE TITLE
审批王高级搜索，如果在里面弹出的窗口更改过流程列表界面的话，会有弹出框BUG。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#820]
![image](https://cloud.githubusercontent.com/assets/6219465/21961503/1b97fb88-db46-11e6-9a78-df9e4784f2fa.png)

1、申请单里包括主表及子表内的选人选组控件都无法弹出选择框。
2、点击新建申请单弹出窗口后，会需要关闭两次弹出窗口。
3、如果弹出的高级搜索窗口本身有滚动条的话，滚动条也会消失，不能再滚动了。

**Comment by zhemingloveme** [comment]
经测试：pc客户端   1、申请单里包括主表及子表内的选人选组控件都无法弹出选择框。  已经解决通过测试
                                2、点击新建申请单弹出窗口后，会需要关闭两次弹出窗口。   已经解决通过测试
                                3、如果弹出的高级搜索窗口本身有滚动条的话……                  **未通过测试**

**Comment by zhemingloveme** [comment]
经测试：所有问题已经解决！
