### ISSUE TITLE
Tabular 控件升级到最新版，数据加载时可以显示loading效果

### ISSUE THREAD

**Issue by steedos** [steedos/apps#821]
https://github.com/aldeed/meteor-tabular

**Comment by yinlianghui** [comment]
已完成。升级了2.x有问题，只升级到1.6.1了，并download源码到本地修改了部分代码。

**Comment by zhemingloveme** [comment]
经测试：IE11 Chrome android ios    在刚刚登录，或切换工作区，等待获取数据时会显示加载中字样！数据加载完毕，字样消失！
