### ISSUE TITLE
普通用户组织机构，联系人中的排序按钮，点击没有反应，可以和管理员用户一样去掉。

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#828]
![qq 20170116171647](https://cloud.githubusercontent.com/assets/23308088/21977208/33ba0556-dc10-11e6-8fbc-caf29eb0bcef.png)
![qq 20170116172101](https://cloud.githubusercontent.com/assets/23308088/21977209/33f77526-dc10-11e6-8d9b-21028398468a.png)

**Comment by yinlianghui** [comment]
已完成，组织机构的排序去掉了，但是个人联系人因为功能是正常的，所以没有去掉。

**Comment by zhangshanshan2016** [comment]
测试过程：IE，chrome,客户端上测试，组织机构的排序已去掉
