### ISSUE TITLE
河北港口平台，领导审批黑头文件时，常用审批语，不实时同步

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#830]
![default](https://cloud.githubusercontent.com/assets/23308088/22008876/13657cc2-dcba-11e6-91cd-2b5b2dfae252.png)
测试环境：http://steedos.ticp.net:8888/workflow/space/Af8eM6mAHo7wMDqD3/inbox/582aa2557125c1006e000288
账号：caoziyu@hotoa.com

**Comment by zhangshanshan2016** [comment]
测试平台：IE ,Chrome测试
测试过程：建立发文测试，审批语可以同步显示
