### ISSUE TITLE
流程管理员，相关权限整理

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#831]
设置流程管理员给他权限：
![default](https://cloud.githubusercontent.com/assets/23308088/22010191/bfdaf7ea-dcc2-11e6-8b0e-a50c7251a60d.png)
流程管理员在监控箱中点击重定位：
![default](https://cloud.githubusercontent.com/assets/23308088/22010228/ee5c6d10-dcc2-11e6-9b15-7892954b0155.png)
显示没有权限：
![default](https://cloud.githubusercontent.com/assets/23308088/22010239/f81dfdaa-dcc2-11e6-941f-f80470b8d4e1.png)

**应该把流程设计器中设置流程权限改为：谁能查看申请单，并能执行重定位、转签核和删除操作
并且开放对流程管理员的相应权限！**

**Comment by steedos** [comment]
应该把流程设计器中设置流程权限改为：查看申请单，并能执行重定位、转签核操作。

并且开放对流程管理员的相应权限！

删除申请单的权限只有工作区管理员才有。

本功能修改完成之后需要更新帮助文档。

**Comment by zhemingloveme** [comment]
经测试：IE11 手机app浏览器 管理员用户进入流程设计器，选择流程，点击设置流程权限，点击最下端授权用户，然后在此流程中，填写申请单，在流程过程中，登录授权用户账号，可以看到转签核和重定位。权限为可用状态！
