### ISSUE TITLE
PC端审批申请单，使用在线编辑功能，<审阅>默认标记应改为：所有标记

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#833]
![default](https://cloud.githubusercontent.com/assets/23308088/22010927/2a3f29fe-dcc7-11e6-9068-b736af6e75c7.png)
**默认为所有标记，当鼠标滑过文本域时，可以显示具体是谁对此文本域编辑过的详细信息**
![default](https://cloud.githubusercontent.com/assets/23308088/22010929/2cea596c-dcc7-11e6-93c3-8b04d87d615e.png)

**Comment by chenzhipei** [comment]
本地测试没有出现该问题，建议安装正式版office再测试该功能
