### ISSUE TITLE
PC端附件在线编辑功能，删除历史版本，会出现解锁界面

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#834]
![default](https://cloud.githubusercontent.com/assets/23308088/22011309/5a2a0f9c-dcc9-11e6-8150-af3949e436ac.png)
**点击右上角x 按钮删除，提示附件删除成功，但是还需要解锁才可以删除**
![vvv](https://cloud.githubusercontent.com/assets/23308088/22011310/5ad7649e-dcc9-11e6-825c-f10ce0bd7a49.png)
**应该点击右上角x按钮，表单直接就可以删除成功，不会涉及到解锁**

**Comment by sunhaolin** [comment]
fs.unlinkSync(filePath); //由于unlinkSync方法执行后，后面的代码不执行所以将此行代码放至最后

**Comment by zhangshanshan2016** [comment]
测试过程：pc上测试，删除历史版本时不需要解锁
