### ISSUE TITLE
表单模板修改：大众公用、港口能源、申能房产

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#835]
[workflow_template.zip](https://github.com/steedos/apps/files/710400/workflow_template.zip)

修改内容：
1、补齐 html 标签
2、`</br>` 修改为 `<br/>`
3、`{{#formatDate finish_date}}{{/formatDate}}` 替换为`{{formatDate finish_date}}`

**Comment by zhangshanshan2016** [comment]
[workflow_template1.zip](https://github.com/steedos/apps/files/715653/workflow_template1.zip)
所有表单按上述要求进行了修改。

**Comment by zhangshanshan2016** [comment]
[workflow_template1.zip](https://github.com/steedos/apps/files/715674/workflow_template1.zip)

**Comment by zhangshanshan2016** [comment]
[workflow_template2.zip](https://github.com/steedos/apps/files/721712/workflow_template2.zip)

**Comment by zhangshanshan2016** [comment]
测试过程：将大众公用、港口能源、申能房产的表单模板贴到“表单样式”中的“打印模板”，并在“监控箱”中过流对应的流程申请单，打开申请单的中的打印格式，查看打印格式是否正确。

**Comment by baozhoutao** [comment]
[workflow_template3.zip](https://github.com/steedos/apps/files/726071/workflow_template3.zip)

**Comment by baozhoutao** [comment]
[workflow_template2.zip](https://github.com/steedos/apps/files/726259/workflow_template2.zip)

**Comment by baozhoutao** [comment]
[workflow_template最终版.zip](https://github.com/steedos/apps/files/726757/workflow_template.zip)
