### ISSUE TITLE
Android客户端，加班申请表单选择时间框过大

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#837]
![s70117-17063468](https://cloud.githubusercontent.com/assets/23308088/22014329/22128918-dcd8-11e6-97b5-3912571dcc20.jpg)

**Comment by yinlianghui** [comment]
需要按类型分别增加高度设置，代码如下：

> .instance .form-group input[type=datetime-local].form-control,.instance .form-group input[type=date].form-control{
    height: 34px !important;
}
