### ISSUE TITLE
河北港口平台，审批时，切换申请单。下一步骤和下一步处理人不对应

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#845]
测试平台：steedos.ticp.net:8888
测试账号：zhaojianping@portqhd.com
选择代办文件，点击第一张申请单，打开审批层，选择下一步处理人。 **然后切换到第二张申请单，再点击第一张申请单的下一步处理人，**
![2017-01-18 15 14 22](https://cloud.githubusercontent.com/assets/23308088/22054656/a8629710-dd91-11e6-8ad2-c65b433fcc8e.png)
显示出工作区中所有的联系人，而并非指定人员！

**Comment by zhangshanshan2016** [comment]
测试平台：IE，chrome
测试过程：steedos.ticp.net:8888上，切换账户后，处理人显示准确
