### ISSUE TITLE
字体放大功能样式重新调式，可能因最近样式改动较大造成很多新问题，特别是弹出modal的情况。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#846]

**Comment by yinlianghui** [comment]
已完成审批王中选人选组及高级搜索相关问题。

**Comment by zhangshanshan2016** [comment]
测试平台：IE，chrome, App, pc客户端
测试过程：
1.chrome, App, pc客户端中，选人选组弹出框，子表弹出框，审批窗口，传阅等的弹出框都出现了大字体。
2.IE浏览器上，不能进行字体放大；
重新处理一个issue：个性化设置网页字体大小 #653
3.ipad没有测试。
