### ISSUE TITLE
待审核审批窗口有时关闭后会自动重新打开。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#853]
待审核申请单（非会签步骤）如果内容比较少，内容高度没有到足够出现滚动条高度的时候。滚动鼠标滚轮，会出现滚动条，无论向上还是向下滚动，都会弹出审批窗口，且向下滚动弹出的窗口关闭后会自动重新打开。

**Comment by yinlianghui** [comment]
已解决，
1. 请选择一个非会签步骤，且内容高度没有到足够出现滚动条高度的申请单，测试上述问题是否会重现。
2. 请测试其他情况是否正常弹出审批层且能正常审批。

**Comment by zhangshanshan2016** [comment]
测试过程：IE，chrome，app上测试
1.分别建立一个没有滚动条的申请单，滚动鼠标时，没有出现滚动条，审批窗口一直都存在，能正常审批。
2.分别建立一个有滚动条的申请单，只有鼠标滚到底部时出现审批窗口，可以正常关闭审批窗口，能正常审批。
