### ISSUE TITLE
新注册账户没有自动跳转到登录成功后界面（注册成功），而且过一会还报错。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#860]
![image](https://cloud.githubusercontent.com/assets/6219465/22133734/18adc30c-defd-11e6-9d18-3fdbc88f8e37.png)

**Comment by zhangshanshan2016** [comment]
测试过程：IE和Chrome上分别新注册账户注册成功后，直接跳到登陆成功后的界面了，而且控制条也没有报错
