### ISSUE TITLE
账户、密码登录错误，界面报错信息没有国际化

### ISSUE THREAD

**Issue by chenzhipei** [steedos/apps#861]
![image](https://cloud.githubusercontent.com/assets/15027092/22137267/03e218e8-df15-11e6-9eed-be3cf50afef5.png)

**Comment by yinlianghui** [comment]
21及我的服务都是好的，请再确定下。

**Comment by zhemingloveme** [comment]
21是没有问题的，翻译出错和缓存有关，请清理本地缓存后再次尝试登录！
