### ISSUE TITLE
背景图及字体放大设置存入本地存储，下次加载到数据前先应用本地存储的背景及字体设置。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#864]

**Comment by yinlianghui** [comment]
已完成。
测试要点：
1. 刷新网页可以看到比原来更早加载显示背景图片。
2. 在登录界面，将显示上一个用户最后设置的背景图片及字体大小，如果没有才显示默认的背景图片及字体大小。
3. 请反复登录登出系统及切换不同用户的不同设置测试。
4. 上述反复登录登出系统及切换不同用户测试正确的情况下，需要进一步刷新浏览器测试是否正确的规则能保持不变。
5. 请特别注意背景图设置中上传自定义背景图片的情况是否像上述几条规则一样正常工作。
5. 请特别注意手机app的情况，包括但不限于上述几条规则，另外要注意下背景图设置图片列表界面中最后一张为自定义背景图片(第8张)是否能正常显示。

**Comment by zhangshanshan2016** [comment]
测试过程：APP ,IE ,Chrome，pc 客户端
1.切换不同账户时，不同账户的“个性化”设置，互不影响；
2.上传自定义背景图片或者设置了字体大小后，例如在APP上设置后，浏览器上会随之发生相应的改变
