### ISSUE TITLE
传阅：删除传阅，多次点击 删除 x ，导致服务端报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#867]
![image](https://cloud.githubusercontent.com/assets/6194462/22142894/000c5daa-df33-11e6-98ae-f3169d3db99c.png)
![image](https://cloud.githubusercontent.com/assets/6194462/22142904/07b5b0a6-df33-11e6-9f23-53e78f08c20f.png)

**Comment by zhangshanshan2016** [comment]
测试过程：在IE和chrome上分别进行测试，删除多个传阅时，控制台没有报错
