### ISSUE TITLE
手机模式下，底部有翻页按钮时会出现透明背景色，APP只有字体放大时才看得到。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#869]
![](https://static.dingtalk.com/media/lADOn_U-Pc0FAM0C0A_720_1280.jpg_620x10000q90g.jpg)

**Comment by yinlianghui** [comment]
测试时主注意测试字体放大时的效果。

**Comment by zhangshanshan2016** [comment]
测试过程：在beta上测试，字体放大时，底部有翻页没有出现透明背景色
