### ISSUE TITLE
手机上在大字体及超大字体时联系人APP中的个人联系人界面由于顶部操作按钮过多造成界面错乱

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#870]
iphone6s大小的手机界面
![image](https://cloud.githubusercontent.com/assets/6219465/22195639/fd063d94-e183-11e6-8e74-21fa722fe347.png)

电脑上宽度比较小时也有问题。
![image](https://cloud.githubusercontent.com/assets/6219465/22195751/80e88842-e184-11e6-994b-2c7bd50dba21.png)

**Comment by yinlianghui** [comment]
改成放大字体时在手机上不显示搜索框。

**Comment by yinlianghui** [comment]
电脑上窄屏情况下界面错乱问题已解决。

**Comment by zhemingloveme** [comment]
经测试：手机APP个性化设置界面字体大小，可以正常显示联系人！
