### ISSUE TITLE
ios原生app上设置放大字体后没有放大效果

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#872]
庄总之前用模拟器调试过，需要额外设置meta viewport的maximum-scale并且要根据设备宽度及放大率计算设置其width值同步。
另外开发版本的APP是有放大效果的。

**Comment by yinlianghui** [comment]
放弃修改meta viewport的方案，用统一的zoom-large/zoom-extra-large样式类来放大字体，但是要额外设置全局样式来解决部分情况下字体没有放大的问题：
	-ms-text-size-adjust: auto;
	-webkit-text-size-adjust: auto;

**Comment by yinlianghui** [comment]
需要打包测试。

**Comment by zhemingloveme** [comment]
经测试：iphone 7 plus 连接最新打包代码21平台，在App中，点击设置，选择个性化，可以设置显示：标准、大字体、超大字体
