### ISSUE TITLE
计算下一步步骤：修改表单字段，不计算下一步步骤

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#875]
条件步骤条件为判断表单字段值， eg:
![image](https://cloud.githubusercontent.com/assets/6194462/22232449/68c021e4-e224-11e6-90e4-ca66bd45b3df.png)

**Comment by zhangshanshan2016** [comment]
测试过程：新建一个流程，可以根据条件判断的值判来确定下一步审批步骤。
