### ISSUE TITLE
新版手机App，联系人模块姓名是竖的！

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#878]
![qq 20170124205618](https://cloud.githubusercontent.com/assets/23308088/22248080/e5efd134-e277-11e6-92f5-1412f565b6ab.png)
ios和android手机app都有同样的问题！

**Comment by yinlianghui** [comment]
增加了水平滚动条，请测试下联系人及组织机构的基本功能是否正常。

**Comment by zhangshanshan2016** [comment]
测试过程：手机上的组织架构，表格均具有都有滚动条且显示正常，pc上没有滚动条。
