### ISSUE TITLE
从其他APP进入审批王，上次搜索结果没有完全清除。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#879]
![image](https://cloud.githubusercontent.com/assets/6219465/22291892/9a057270-e343-11e6-9eea-457621472832.png)

第一次搜索的时候有两种情况
1.从顶部的流程菜单列表选项筛选的搜索结果。
2.从搜索框输入搜索关键字的搜索结果。
3.其他可能的搜索结果，比如高级搜索结果。
以上几种搜索结果，都要在每次进入APP时清除。

**Comment by steedos** [comment]
这个不严重，可以不处理
