### ISSUE TITLE
登录超时后，显示白屏，再刷新就好了

### ISSUE THREAD

**Issue by steedos** [steedos/apps#881]
控制台报错：Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]

![image](https://cloud.githubusercontent.com/assets/3104826/22576974/e0c4485a-e9f9-11e6-8278-cda246518009.png)

**Comment by steedos** [comment]
昨天清空token后，手机端也出现了这个现象。测试很简单，登录两台设备，在其中一个控制台输入 
Accounts.logoutOtherClients()

**Comment by steedos** [comment]
或许可以用Tracker监测  Meteor.userId()

**Comment by yinlianghui** [comment]
登录信息失效时直接跳转到登录界面可以解决该问题。

**Comment by zhangshanshan2016** [comment]
测试过程：同一个域，同一个工作区，同一个账户，同时在chrome,IE ,手机App上登录后，在chrome的控制台上输入Accounts.logoutOtherClients()后，IE和chrome都跳转到登录界面。
