### ISSUE TITLE
users (initiators) reporting that they dont receive email notification when the request is completed

### ISSUE THREAD

**Issue by steedos** [steedos/apps#884]
manos.k 4:10 PM 
Hello Jack, users (initiators) reporting that they dont receive email notification when the request is completed. Can you please advise on this issue? Thanks!

**Comment by sunhaolin** [comment]
在us.steedos.com上测试，提交到结束节点 申请单可以收到mail；

**Comment by sunhaolin** [comment]
请确认个人设置中 ‘接受邮件通知’  选项是选中状态

**Comment by sunhaolin** [comment]
原因是因为 新用户没有email字段，而发送待审核邮件在使用user.email字段发送邮件；

**Comment by sunhaolin** [comment]
待讨论具体修改方案

**Comment by sunhaolin** [comment]
目前解决方案是让用户将邮件设置为主要邮件即可
