### ISSUE TITLE
申请单查找框，输入一个字母 r 或者 q，客户端死机

### ISSUE THREAD

**Issue by steedos** [steedos/apps#888]
客户端控制台报错 Error invoking SubsManager.subscribe("instance_tabular", "instances", 52b834ed334904438d000002,52b2706c33490457ed000872, [object Object]):  Internal server error

服务端报错： I20170206-13:43:40.031(8)? Exception from sub instance_tabular id L6TcwPsDvHXuhTTXL TypeError: Cannot read property 'current' of undefined
I20170206-13:43:40.032(8)?     at Object.uuflowManager.getStep (packages/steedos_workflow/server/lib/uuflow_manager.coffee:100:9)
I20170206-13:43:40.033(8)?     at getStepCurrentName (packages/steedos_workflow/server/publications/instance_tabular.coffee:52:26)
I20170206-13:43:40.033(8)?     at packages/steedos_workflow/server/publications/instance_tabular.coffee:79:32
I20170206-13:43:40.034(8)?     at Array.forEach (native)
I20170206-13:43:40.034(8)?     at Subscription.<anonymous> (packages/steedos_workflow/server/publications/instance_tabular.coffee:72:6)
I20170206-13:43:40.034(8)?     at packages/matb33_collection-hooks/collection-hooks.js:281:1
I20170206-13:43:40.035(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20170206-13:43:40.035(8)?     at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:280:1)
I20170206-13:43:40.035(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20170206-13:43:40.036(8)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)

**Comment by baozhoutao** [comment]
此问题是由于：旧数据中(3年前)部分instance对应的flow 已被删除，导致程序报错。

**Comment by zhemingloveme** [comment]
经测试：客户端/IE11 chrome Edge浏览器，在申请单查找框中输入字母r或者q，客户端正常响应，浏览器控制台不会报错！
