### ISSUE TITLE
CMS文章列表的时间改成发布日期

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#891]
列表时间格式不变，还是显示为以多久之前。但是详细界面格式变为完整日期。
发布到外网的站点时间也改成发布日期，规则同上。

**Comment by yinlianghui** [comment]
规则要点：
1. 列表时间格式不变，还是显示为以多久之前。但是详细界面格式变为完整日期。
2. 发布到外网的站点时间也改成发布日期，列表及详细界面规则同上 。
3. 新建/编辑文章时发布日期为必填并且默认值为当前时间。

**Comment by zhemingloveme** [comment]
经测试：IE11 手机app浏览器 在CMS中，添加文章，文章中发布日期自动获取系统当前时间！（为必填项）
