### ISSUE TITLE
放大字体后，登录窗口出现水平滚动条

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#897]
测试要点：
1. 在PC的浏览器及客户端，调整窗口的宽度及高度（主要是宽度，要从最大慢慢到最小），整个过程不会出现水平滚动条。
2. 需要测试手机APP。

**Comment by zhemingloveme** [comment]
经测试：手机app和IE11及windows客户端，调整字体大小后，进去登录界面，注销登录，都不会出现水平滚动条
