### ISSUE TITLE
编译本地代码，打包过程中，执行./start.sh脚本，终端报错

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#899]
本地代码apps中执行./build.sh后
在srv／worlflow执行./start.sh终端报错如下：

![2017-02-08 09-29-31](https://cloud.githubusercontent.com/assets/23308088/22719732/e1496d82-ede1-11e6-86b5-9b67f7ad37c8.png)
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
FS.StorageAdapter emit error
{ [Error: ENAMETOOLONG: name too long, open '/srv/workflow/cfs/files/instances/instances-3WgdA4m5xakwGhQt2-合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html']
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: '/srv/workflow/cfs/files/instances/instances-3WgdA4m5xakwGhQt2-合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html' }
EventEmitter {
  createdByTransform: true,
  original: 
   { type: 'text/html',
     size: 15597,
     name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html' },
  metadata: 
   { owner: '55b5c8d1527eca7e9d000423',
     owner_name: '吉淑娴',
     space: '55090bbe527eca33d8000fe0',
     instance: '7Z8dsTjL5n5XY2hgC',
     approve: 'e330c56d-a07d-4bab-8eb3-30eff681d7b7',
     current: true,
     parent: '3WgdA4m5xakwGhQt2' },
  uploadedAt: Tue Jan 24 2017 16:50:52 GMT+0800 (CST),
  _id: '3WgdA4m5xakwGhQt2',
  collectionName: 'instances',
  copies: 
   { instances: 
      { name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html',
        type: 'text/html',
        size: 15597 } },
  collection: 
   EventEmitter {
     storesLookup: { instances: [Object] },
     primaryStore: 
      EventEmitter {
        name: 'instances',
        typeName: 'storage.filesystem',
        adapter: [Object],
        _removeAsync: [Function],
        remove: [Function],
        _transform: [Object] },
     options: { filter: null, stores: [Object], chunkSize: null },
     name: 'instances',
     files: 
      { _makeNewID: [Function],
        _transform: [Object],
        _connection: [Object],
        _collection: [Object],
        _name: 'cfs.instances.filerecord',
        _driver: [Object],
        _restricted: true,
        _insecure: undefined,
        _validators: [Object],
        _prefix: '/cfs.instances.filerecord/',
        before: [Object],
        _hookAspects: [Object],
        after: [Object],
        hookOptions: [Object],
        direct: [Object],
        upsert: [Function] },
     _validators: { download: [Object] } } }
instances
FS.Collection emit error
[Error: Error storing file to the instances store: ENAMETOOLONG: name too long, open '/srv/workflow/cfs/files/instances/instances-3WgdA4m5xakwGhQt2-合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html']
EventEmitter {
  createdByTransform: true,
  original: 
   { type: 'text/html',
     size: 15597,
     name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html' },
  metadata: 
   { owner: '55b5c8d1527eca7e9d000423',
     owner_name: '吉淑娴',
     space: '55090bbe527eca33d8000fe0',
     instance: '7Z8dsTjL5n5XY2hgC',
     approve: 'e330c56d-a07d-4bab-8eb3-30eff681d7b7',
     current: true,
     parent: '3WgdA4m5xakwGhQt2' },
  uploadedAt: Tue Jan 24 2017 16:50:52 GMT+0800 (CST),
  _id: '3WgdA4m5xakwGhQt2',
  collectionName: 'instances',
  copies: 
   { instances: 
      { name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html',
        type: 'text/html',
        size: 15597 } },
  collection: 
   EventEmitter {
     storesLookup: { instances: [Object] },
     primaryStore: 
      EventEmitter {
        name: 'instances',
        typeName: 'storage.filesystem',
        adapter: [Object],
        _removeAsync: [Function],
        remove: [Function],
        _transform: [Object] },
     options: { filter: null, stores: [Object], chunkSize: null },
     name: 'instances',
     files: 
      { _makeNewID: [Function],
        _transform: [Object],
        _connection: [Object],
        _collection: [Object],
        _name: 'cfs.instances.filerecord',
        _driver: [Object],
        _restricted: true,
        _insecure: undefined,
        _validators: [Object],
        _prefix: '/cfs.instances.filerecord/',
        before: [Object],
        _hookAspects: [Object],
        after: [Object],
        hookOptions: [Object],
        direct: [Object],
        upsert: [Function] },
     _validators: { download: [Object] } } }
instances
fileObj emit error
instances
Exception in queued task: Error: Not Found [404]
    at Object.FS.StorageAdapter.createReadStream (packages/cfs_filesystem/filesystem.server.js:60:1)
    at Object.self.adapter.createReadStreamForFileKey (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:83:1)
    at Object.self.adapter.createReadStream (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:91:1)
    at packages/cfs_tempstore/packages/cfs_tempstore.js:372:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at CombinedStream._getNext (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/cfs_tempstore/node_modules/combined-stream/lib/combined_stream.js:83:3)
    at CombinedStream.resume (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/cfs_tempstore/node_modules/combined-stream/lib/combined_stream.js:132:10)
    at CombinedStream.pipe (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/cfs_tempstore/node_modules/combined-stream/lib/combined_stream.js:64:8)
    at saveCopy (packages/cfs_worker/fileWorker.js:176:1)
FS.StorageAdapter emit error
{ [Error: ENAMETOOLONG: name too long, open '/srv/workflow/cfs/files/instances/instances-cuF8FGez6RbqAtnnv-合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html']
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: '/srv/workflow/cfs/files/instances/instances-cuF8FGez6RbqAtnnv-合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html' }
EventEmitter {
  createdByTransform: true,
  original: 
   { type: 'text/html',
     size: 15597,
     name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html' },
  metadata: 
   { owner: '55b5c8d1527eca7e9d000423',
     owner_name: '吉淑娴',
     space: '55090bbe527eca33d8000fe0',
     instance: 'frP2x8rM6HMyCY4K9',
     approve: 'bb673240-8b54-43a8-99ce-31e31ca4e5e7',
     current: true,
     parent: 'cuF8FGez6RbqAtnnv' },
  uploadedAt: Tue Jan 24 2017 16:53:49 GMT+0800 (CST),
  _id: 'cuF8FGez6RbqAtnnv',
  collectionName: 'instances',
  copies: 
   { instances: 
      { name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html',
        type: 'text/html',
        size: 15597 } },
  collection: 
   EventEmitter {
     storesLookup: { instances: [Object] },
     primaryStore: 
      EventEmitter {
        name: 'instances',
        typeName: 'storage.filesystem',
        adapter: [Object],
        _removeAsync: [Function],
        remove: [Function],
        _transform: [Object] },
     options: { filter: null, stores: [Object], chunkSize: null },
     name: 'instances',
     files: 
      { _makeNewID: [Function],
        _transform: [Object],
        _connection: [Object],
        _collection: [Object],
        _name: 'cfs.instances.filerecord',
        _driver: [Object],
        _restricted: true,
        _insecure: undefined,
        _validators: [Object],
        _prefix: '/cfs.instances.filerecord/',
        before: [Object],
        _hookAspects: [Object],
        after: [Object],
        hookOptions: [Object],
        direct: [Object],
        upsert: [Function] },
     _validators: { download: [Object] } } }
instances
FS.Collection emit error
[Error: Error storing file to the instances store: ENAMETOOLONG: name too long, open '/srv/workflow/cfs/files/instances/instances-cuF8FGez6RbqAtnnv-合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html']
EventEmitter {
  createdByTransform: true,
  original: 
   { type: 'text/html',
     size: 15597,
     name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html' },
  metadata: 
   { owner: '55b5c8d1527eca7e9d000423',
     owner_name: '吉淑娴',
     space: '55090bbe527eca33d8000fe0',
     instance: 'frP2x8rM6HMyCY4K9',
     approve: 'bb673240-8b54-43a8-99ce-31e31ca4e5e7',
     current: true,
     parent: 'cuF8FGez6RbqAtnnv' },
  uploadedAt: Tue Jan 24 2017 16:53:49 GMT+0800 (CST),
  _id: 'cuF8FGez6RbqAtnnv',
  collectionName: 'instances',
  copies: 
   { instances: 
      { name: '合同审批-合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称合同名称v.html',
        type: 'text/html',
        size: 15597 } },
  collection: 
   EventEmitter {
     storesLookup: { instances: [Object] },
     primaryStore: 
      EventEmitter {
        name: 'instances',
        typeName: 'storage.filesystem',
        adapter: [Object],
        _removeAsync: [Function],
        remove: [Function],
        _transform: [Object] },
     options: { filter: null, stores: [Object], chunkSize: null },
     name: 'instances',
     files: 
      { _makeNewID: [Function],
        _transform: [Object],
        _connection: [Object],
        _collection: [Object],
        _name: 'cfs.instances.filerecord',
        _driver: [Object],
        _restricted: true,
        _insecure: undefined,
        _validators: [Object],
        _prefix: '/cfs.instances.filerecord/',
        before: [Object],
        _hookAspects: [Object],
        after: [Object],
        hookOptions: [Object],
        direct: [Object],
        upsert: [Function] },
     _validators: { download: [Object] } } }
instances
fileObj emit error
instances
fileObj emit error
instances
Exception in queued task: Error: Not Found [404]
    at Object.FS.StorageAdapter.createReadStream (packages/cfs_filesystem/filesystem.server.js:60:1)
    at Object.self.adapter.createReadStreamForFileKey (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:83:1)
    at Object.self.adapter.createReadStream (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:91:1)
    at packages/cfs_tempstore/packages/cfs_tempstore.js:372:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at CombinedStream._getNext (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/cfs_tempstore/node_modules/combined-stream/lib/combined_stream.js:83:3)
    at CombinedStream.resume (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/cfs_tempstore/node_modules/combined-stream/lib/combined_stream.js:132:10)
    at CombinedStream.pipe (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/cfs_tempstore/node_modules/combined-stream/lib/combined_stream.js:64:8)
    at saveCopy (packages/cfs_worker/fileWorker.js:176:1)
{"line":"82","file":"migrations_server.js","message":"Migrations: Not migrating, control is locked.","time":{"$date":1486517027201},"level":"info"}
Exception in setInterval callback: Error: read ECONNRESET
    at Object.Future.wait (/srv/workflow/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1021:47)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1055:22)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:904:44)
    at packages/raix:push/lib/server/push.api.js:578:32
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    - - - - -
    at exports._errnoException (util.js:907:11)
    at TCP.onread (net.js:557:26)

**Comment by steedos** [comment]
存档，暂不处理
