### ISSUE TITLE
弹出框帮助按钮样式优化。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#901]
![image](https://cloud.githubusercontent.com/assets/6219465/22729335/4a354588-ee1d-11e6-892e-6e794501ff69.png)

**Comment by yinlianghui** [comment]
改成了如下结果：
![image](https://cloud.githubusercontent.com/assets/6219465/22729371/726b3832-ee1d-11e6-8766-3eefec3a0113.png)

![image](https://cloud.githubusercontent.com/assets/6219465/22729390/8024a0e4-ee1d-11e6-867e-17fa947c143f.png)

**Comment by yinlianghui** [comment]
我修改过7个地方，请测试是确定所有可能的地方都改好了。

**Comment by zhangshanshan2016** [comment]
添加帮助链接页面：传阅、转签核、重定位、文件转发、过滤查询申请单、新建申请单、邀请用户。（中文页面均有），取回的中英文还没有添加
