### ISSUE TITLE
抚顺邮件样式修改

### ISSUE THREAD

**Issue by zhangshanshan2016** [steedos/apps#902]
1.邮件包含敏感信息关键字：XXX。请修改后重新发送
![mail1](https://cloud.githubusercontent.com/assets/20197393/22768149/16af2bf4-eebb-11e6-8693-1b7fdd4e0607.png)
2.修改成下图的提示样式和内容
![mail2](https://cloud.githubusercontent.com/assets/20197393/22767983/fe0df482-eeb9-11e6-986b-10faf14ec309.png)
![mail3 png](https://cloud.githubusercontent.com/assets/20197393/22768011/1967c87a-eeba-11e6-9921-b9ebff6212c1.jpg)
3.侧边栏收起展开图标不明显，没有文字提示，考虑换图标和加文字提示
![mail4](https://cloud.githubusercontent.com/assets/20197393/22768264/d4cdbe20-eebb-11e6-9c66-430bc6140fcd.png)

**Comment by zhangshanshan2016** [comment]
1.邮件中敏感字提醒（包含上面的1和2）：[抚顺石化发送验证脚本(包含附件大小限制)5.txt](https://github.com/steedos/apps/files/763102/5.txt)。
上面的第2点，只修改了弹出框里的文字 ，没有修改弹出框的样式。
2.
![default](https://cloud.githubusercontent.com/assets/20197393/22776414/840515b8-eeea-11e6-91b7-ed7fee4cd6b4.PNG)

**Comment by sunhaolin** [comment]
脚本已更新至 抚顺石化服务器
