### ISSUE TITLE
审批王搜索栏样式优化

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#903]
1. 左侧过滤图标按钮去掉
2. 手机上也显示搜索栏
3. 导出下拉按钮，文字写全，改成“导出当月申请单，导出上月申请单...”
4. 高级搜索弹出层在手机上起止时间值没有垂直对齐。
5. 搜索结果几个字大小改成普通大小。

**Comment by yinlianghui** [comment]
测试要点：
1. 重点测试手机APP上的效果，因为我没有测试，特别是时间控件对齐问题。
2. 要测试字体放大的效果。

**Comment by zhemingloveme** [comment]
经测试:IE11 手机浏览器在搜索栏中，点击右边下拉箭头高级搜索，选择流程名水平居中显示，导出按钮下拉菜单为：导出当月申请单，导出上月申请单，导出当年申请单，导出所有申请单！
