### ISSUE TITLE
组织机构中，邀请新用户，用户收到的邮件标题样式有空格(仅以QQ邮箱接收邮件)！

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#908]
管理员用户，在组织架构中邀请新用户，系统提示给用户发送邮件
![qq 20170210154146](https://cloud.githubusercontent.com/assets/23308088/22818356/c7c103ee-efa7-11e6-8482-cf5553a413a5.png)
收到的邮件标题有空格！
标题有空格！
目前测试，cn平台，us平台。只有QQ邮箱这个问题

**Comment by steedos** [comment]
暂不予处理
