### ISSUE TITLE
签核历程传阅处要增加显示“传阅，来自某某某”，方式是鼠标放上去时显示出来。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#911]
由于approve对象在数据库表中只存储了from_user_id并没有存储from_user_name，出于性能考虑，应该在数据库中approve表中增加from_user_name字段

**Comment by yinlianghui** [comment]
请sunhaolin帮在数据库approve的modal中增加用户名称字段，并修改相关流程引擎逻辑。

**Comment by steedos** [comment]
关联任务 https://github.com/steedos/apps/issues/924

**Comment by yinlianghui** [comment]
增加过弹出详细申请单后就不需要该功能了。
