### ISSUE TITLE
手机端的常用意见

### ISSUE THREAD

**Issue by steedos** [steedos/apps#917]
1. 把弹出的意见框中右侧填写框去掉。
2. 单击时把选中的常用意见增加到审批意见最后。
3. 优化增删改常用意见功能。

**Comment by yinlianghui** [comment]
测试要点：
1. 请测试添加/删除/修改常用意见功能是否正常。
2. 请测试拖动排序功能是否正常。
3. 请测试手机APP(ios/android)上上述功能是否正常。
4. 请测试PC各浏览器及PC客户端是否正常（我只测试了chrome及手机）。

**Comment by zhemingloveme** [comment]
经测试：IE11 Edge windos客户端   在审批框中右边点击常用意见按钮，会弹出设置常用意见对话框，点击添加按钮可以添加自定义常用审批意见，添加好后可以点击✎对常用审批意见进行修改，也可以点击X 号按钮对常用审批意见进行删除。点击最右边的拖动按钮可以对常用审批意见进行排序（也可以长按常用审批意见框）
              android和ios  App     同样也可以实现上述功能！
