### ISSUE TITLE
监控箱中，输入关键字进行延时搜索，页面会出现闪烁的情况

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#920]
![qq 20170213092407](https://cloud.githubusercontent.com/assets/23308088/22868206/4bf12c34-f1ce-11e6-8b9f-4df68787422f.png)
在监控箱中陆续输入关键字，会发现页面闪烁。

**Comment by steedos** [comment]
可以考虑搜索框选中时，右侧显示搜索图标，点击搜索图标才出发搜索操作。
