### ISSUE TITLE
调试 IE Zoom 

### ISSUE THREAD

**Issue by steedos** [steedos/apps#925]
想要支持 zoom 的话 IE 浏览器的第一层DIV不能是绝对定位。

**Comment by yinlianghui** [comment]
测试要点：
1. 请确定IE11/Edge三种字体下效果是否正常。
2. 要注意测试所有弹出窗口（每个都测试）三种字体下效果是否正常。

**Comment by zhemingloveme** [comment]
经测试：IE调整3种不同字体均可正常显示！
