### ISSUE TITLE
组织架构中当组织很多时，会出现滚动条，但是滚动条高度不够造成看不到最底部的部门。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#927]

**Comment by yinlianghui** [comment]
测试要点：
找个组织架构很多的地方测试下就行了，需要重点测试客户端APP及手机APP。

**Comment by zhemingloveme** [comment]
经测试：IE11  Edge android   ios   组织架构和个人联系人中，组织架构工作区过多时，会出现滚动条。可以自由调整，显示所有内容
