### ISSUE TITLE
多个后续步骤时，下一步处理人有时没有选择项

### ISSUE THREAD

**Issue by baozhoutao** [steedos/apps#932]

**Comment by baozhoutao** [comment]
此问题是由于：编辑表单字段后， 重新计算下一步步骤有误导致用户选项被清空

**Comment by baozhoutao** [comment]
重现方式：选择步骤后，编辑表单字段，人员选择列表会为空

**Comment by zhemingloveme** [comment]
设置流程审批节点是多个审批步骤，新建表单，选择下一处理步骤，再编辑表单字段。选择下一步处理人可以正常显示！IE11 Edge  Android  IOS均可以正常显示人员选择列表
