### ISSUE TITLE
用户维护自己的 username

### ISSUE THREAD

**Issue by steedos** [steedos/apps#934]
界面可参考Github。功能可参考Steedos Chat

**Comment by sunhaolin** [comment]
Meteor.settings.public.accounts.UTF8_Names_Validation: "[A-Za-z0-9-_.\\u00C0-\\u017F\\u4e00-\\u9fa5]+"

**Comment by zhemingloveme** [comment]
经测试：目前用户在设置——个人信息——账户下面可以看到更改用户名。对用户名进行修改，用户名仅使用汉字，字母，数字，点，连字符和下划线。若输入其他非法字符会有弹窗消息提醒，不可保存使用
