### ISSUE TITLE
“组织架构”在界面缩小时会出现界面缺失的情况，导致无法编辑

### ISSUE THREAD

**Issue by lizheng42** [steedos/apps#935]
![cb 2zd q9 7 04aff g2c6](https://cloud.githubusercontent.com/assets/25809180/23017746/7e0977d0-f476-11e6-9fd5-0ef7e730d41e.png)
![zv9 k3fm5svb h1 wc owcn](https://cloud.githubusercontent.com/assets/25809180/23017747/7e3df794-f476-11e6-81d5-dc83ac0ddca8.png)

**Comment by zhemingloveme** [comment]
经测试：组织架构在小屏幕的时候可以正常的进行编辑。自动响应屏幕的大小，可以兼容目前的所有手机设备！
