### ISSUE TITLE
申请单的单选/多选/下拉/勾选等控件在表格/非表格模式下都样式没有对齐。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#950]
主要是PC上表格模式，及手机上非表格模式问题比较多。

**Comment by yinlianghui** [comment]
测试要点：
1. 所有字段的样式都要正常，包括左右及水平都要注意是否没有正确对齐。
2. 重点测试的字段有：单选/多选/下拉/勾选/选人选组及其弹出的列表中单选多选
3. 表格字段（即子表）中的所有字段类型都要测试，包括主表中的子表列表及弹出的新建/编辑子表项modal框中所有字段类型都要测试。
4. 我测试过IE11/Edge/chrome/mac safari/ios safari/anrdoid brower，其他比如PC客户端面及ios/android APP没有测试，打包后要重点测试我没有测试过的平台，特别是日期时间字段。
5. 在上述基础上需要测试打印/文件转发中作为附件下载/作为邮件内容发送到邮件中的样式。

**Comment by zhemingloveme** [comment]
![qq 20170222132800](https://cloud.githubusercontent.com/assets/23308088/23198492/f856defc-f902-11e6-8145-b9c2645b2a10.png)
IE11 多选字段，表单样式：默认或者是表格    在只读的情况下——没有权限，不允许编辑，审批过程中，只读显示的是新建表单时，勾选的，选中的那两个。
也就是说：这张表单，我在填写时，多选字段是有苹果、香蕉、葡萄可供多选的。然后我选中苹果和葡萄就行提交申请单，在处理人收到这张申请单时。他所看到的就只有，提交人选中的2个内容，如上图所示：苹果、葡萄！

**Comment by zhemingloveme** [comment]
经测试：在23上测试用tianqi@hotoa.com账号在集团公司工作区中新建流程，全字段表单（包括表格和分组），新建表单，填写内容，然后提交下一步处理人。只读权限，样式对齐问题已经解决。切换表单样式默认和表格，对比测试，观察变化，上述问题已经解决！在测试过程中，遇到的其他问题已经另报bug！

URL字段和时间控件居中，有问题待解决，已经和殷老师确认！（URL问题，已经另报bug）

**Comment by zhemingloveme** [comment]
经测试：除已报Issues外，其他问题均已解决！样式在IE11 Edge Android  Ios  mac客户端  windows客户端都可以正常显示！
