### ISSUE TITLE
工作区拥有者在用户管理页面 将自己设置为无效后，工作区列表中就看不到自己工作区了

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#958]
测试时需要考虑管理员的情况

**Comment by yinlianghui** [comment]
![](https://static.dingtalk.com/media/lALPAsaK8Wr0to_NAdzNA7k_953_476.png_620x10000q90g.jpg)

![image](https://cloud.githubusercontent.com/assets/6219465/23846964/11da8af6-080b-11e7-85a3-ce7ab7668215.png)


1. 工作区拥有者/管理员不可以被（任何人）设置为无效。
2. 不可以把拥有者从管理员中删除。
3. 不可以把拥有者/管理员从工作区中删除。

**Comment by zhusijia** [comment]
测试原来的添加删除等功能是否正常，测试工作区拥有者/管理员是否可以被设置为无效，测试拥有者/管理员是否可以从工作中删除，反复将一个人设置为管理员，再取消管理员，再测试上述的两个问题

**Comment by zhemingloveme** [comment]
经测试：把管理员或拥有者设置无效
![image](https://cloud.githubusercontent.com/assets/23308088/24279712/8567adcc-1086-11e7-8165-03408e30e36b.png)
会有弹窗提醒
所以，不能设置管理员和拥有者为无效，其他功能可以正常使用
