### ISSUE TITLE
表单文本框字段，预置下拉选项

### ISSUE THREAD

**Issue by steedos** [steedos/apps#965]
- 需要修改表单设计器，文本类型字段可以设置下拉选项
- 在编辑界面显示下拉选项

使用控件 http://twitter.github.io/typeahead.js/examples/

**Comment by zhemingloveme** [comment]
经测试:IE11  Edge ios  android   管理员用户在流程设计器中表单中，添加文本字段，可以在属性中设置输入选项。在普通用户新建此申请单时，文本框有预设提醒，可以直接点击字段！手机app   android ios均可实现此功能！
