### ISSUE TITLE
流程设计中，若已指定审批岗位的节点，人员发生修改（删除），无法再次对此步骤进行属性编辑

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#968]
![bug](https://cloud.githubusercontent.com/assets/23308088/23204207/9aa30718-f920-11e6-8edb-68b5101c29d6.png)

流程设计器中，已经配置好了处理人（指定审批岗位），当此审批岗位人员被删除或是调动时，流程设计器会提示：步骤中指定的处理人已删除或已停用。这时，我们需要对此节点就行修改，要点击右边的属性按钮。属性按钮无响应!

**Comment by sunhaolin** [comment]
经测试 指定人员会出现此现象，指定岗位并不会

**Comment by zhemingloveme** [comment]
测试后，流程设计器中，审批时指定人员，当人员发生修改（删除）时，流程设计器中会在此节点显示感叹号。审批时指定岗位，当人员发生修改（删除）时，流程设计器不会显示感叹号！
