### ISSUE TITLE
高级搜索，提交日期的截至日期控件，时间显示不全

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#974]
标准字体：
![default](https://cloud.githubusercontent.com/assets/23308088/23287351/c9277080-fa77-11e6-9b08-2d2157cb5079.png)
大字体：
![default](https://cloud.githubusercontent.com/assets/23308088/23287354/ce17171c-fa77-11e6-9f45-6d098d15cd96.png)
超大字体：
![default](https://cloud.githubusercontent.com/assets/23308088/23287429/5239c846-fa78-11e6-9152-5db6b661a2c1.png)

IE11  Edge  Chrome  windows客户端都存在这样的问题

**Comment by yinlianghui** [comment]
注意测试各种字体及浏览器下是否都 正常了，我只测试了chrome。

**Comment by zhemingloveme** [comment]
经测试：IE11  Edge 在分别设置三种字体大小的情况下，在审批王界面，点击高级搜索。日期控件，时间可以正常显示！
