### ISSUE TITLE
mac的Safari浏览器，在表单样式中，内容显示不全

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#980]
![2017-02-24 5 03 23](https://cloud.githubusercontent.com/assets/23308088/23297281/e6b23e82-fab3-11e6-95a7-20bdd4df616d.png)
此mac的屏幕分辨率为：1440x900

小mac 屏幕分辨率为1366x768  显示正常
window10 屏幕分辨率为1920x1080  显示正常

**Comment by steedos** [comment]
后台管理功能，暂不处理
