### ISSUE TITLE
URL字段，应该只允许输入链接！

### ISSUE THREAD

**Issue by zhemingloveme** [steedos/apps#981]
![image](https://cloud.githubusercontent.com/assets/23308088/23298885/4eb090e6-faba-11e6-82b4-15de16c33273.png)

字段类型为URL    应该只允许输入链接，但是现在可以输入任意字符，还可以进行提交。在审批人看到申请单为只读权限时，还可以进行点击，新建窗口显示出错！
![image](https://cloud.githubusercontent.com/assets/23308088/23298926/82492a62-faba-11e6-8cdd-42c221f852f8.png)

填写url字段要做校验，用正则判断是否为url格式，正则格式请到网上找一个，应该有很多，测试通过即可。

**Comment by yinlianghui** [comment]
填写url字段要做校验，用正则判断是否为url格式，正则格式请到网上找一个，应该有很多，测试通过即可。

**Comment by zhangshanshan2016** [comment]
url用正则判断时，只能判断出格式是否正确，但是如果要保证网址的判断是否正确，需要考虑的条件类型太多，所以没必要将url判断做的如此复杂。

**Comment by yinlianghui** [comment]
url校验比较麻烦，直接关掉不处理。
