### ISSUE TITLE
在系统设置的组织构架中如果切换工作区会出现Loading层，并且无法清除。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/apps#983]
注意联系人APP中的组织构架是没有这个问题的。

**Comment by yinlianghui** [comment]
原因是tabular在destroy时要额外设置isLoading属性为False。
而联系人APP中的组织构架是没有这个问题的原因是在那边切换space的时候马上有新的tabular把isLoading属性重置为False了。

**Comment by zhemingloveme** [comment]
经测试：同步最新代码，管理员用户进入组织架构，切换工作区，可以正常进入，不会出现loading界面了！
