### ISSUE TITLE
FSSH: 新增 login_auths 字段

### ISSUE THREAD

**Issue by steedos** [steedos/apps#995]
var logins = {{login_auths}}
var un =  login_auths.ptr.login_name
var pwd = login_auths.ptr.login_password

- login_auths 
  -  ptr
     - login_name
     - login_password
  -  cnpc
     - login_name
     - login_password

**Comment by yinlianghui** [comment]
测试要点：
1. 测试新增 的login_auths 字段脚本功能，注意判断属性是否为空的条件在前台脚本中写，没有在统一的接口中写。
2. 之前的 {{login_name}} {{login_password}} 变量替换的逻辑也保留了，其需要配合app.auth_name属性使用，需要再测试一次。

**Comment by chenzhipei** [comment]
1、更新代码后不做任何修改，可以实现单点登录
2、修改本机单点登录脚本，测试可以实现单点登录
